### PR TITLE
Remove enums from tests

### LINKED ISSUE #5418: Remove enums from tests
As discussed in https://github.com/openlayers/ol3/commit/a096c3dae6b187e2226e1a8fffbd794540ff0b20#commitcomment-17469103 tests should be using the string literals as applications would, not the enums. This only works ATM because the test framework uses the debug build. There are quite a lot of these, all with `goog.require`, and removing them would considerably simplify the dependency structure and change to modules.

I'll work on a PR for this.

### PR DESCRIPTION
**Pull request by probins**
Fixes #5418. Think I've got them all. :-)

### CODE REVIEW

**Comment by probins** [comment]
review anyone?

**Comment by ahocevar** [comment]
Looks good, thanks @probins.

**Comment by ahocevar** [comment]
Oh, I had missed https://github.com/openlayers/ol3/issues/5463#issuecomment-226516869. And I have to admit I see the benefit of having enums. @probins, I don't see anything negative about having these enums in the tests, and they help us test the enums indirectly. That said, I think I'm going to revert this.

**Comment by probins** [comment]
but surely the tests are there to test how apps would use the library. Apps don't use the enums

**Comment by probins** [comment]
I'm not saying there shouldn't be enums, just that they don't belong in the tests

**Comment by ahocevar** [comment]
> but surely the tests are there to test how apps would use the library. Apps don't use the enums

In theory (and of course in computer science school) yes, but many thing we test use internal/unexported variables/functions, so we'll have to run our tests with a debug build for the time being.

**Comment by ahocevar** [comment]
Looking through this changeset again, I think the biggest loss is the link to `ol.TileState` and `ol.ImageState`. If we decide to use string values (e.g. `'loading'`) for those like we do everywhere else, there will be more effort to update the tests.

**Pull request merged**
