### PR TITLE
Add "filter" option to Select interaction

### PR DESCRIPTION
**Pull request by elemoine**
This is a "rebased/squashed" version of https://github.com/openlayers/ol3/pull/3277.

### CODE REVIEW

**Comment by elemoine** [comment]
I'll merge this when/if the Travis build passes.

**Comment by doronhorwitz** [comment]
I realise I'm new around here, but I've been doing a bit of historical research into this issue and found that this filtering functionality might interact with the ```multi``` option. Hence my commenting now on an [old commit](https://github.com/bjornharrtell/ol3/commit/162c47eb3e0f6ea1bab192fb14b8f0c4cea7f5e0) where ```multi``` was introduced, just to draw attention to it.

Two things that might be relevant.
1. ```multi``` allows only the top most feature to be selected when features overlap. What if the top most feature is filtered out?
2. the ```multi``` option only applies for a set operation - ```if (set)``` -, should it not be used also for toggle, add and remove? I realise that this is not directly linked to the pull request, but since this pull request modifies code which directly interacts with ```multi``` perhaps my point can be considered?

**Comment by tschaub** [comment]
@doronhorwitz thanks for bringing this up.  It would be great to have tests that enforced the desired behavior.  I think we need to start getting more strict about including tests with new features.  The previous two minor releases included regressions with the select interaction.  It would be unfortunate to repeat that again for 3.4.

**Comment by tremby** [comment]
Disappointed this didn't make it in to 3.4. I was hoping to avoid needing a custom build of OL3 for our project but I'll miss the deadline if I don't now, presuming you stick to the monthly release schedule. Hopefully this makes it in to the next release, regardless.

**Comment by sweco-sebhar** [comment]
I can admit that I did not consider the conditional select logic at all when implementing multi, having problems grasping the details of it. It probably should affect the conditional select logic too.

With "`multi` allows only the top most feature to be selected when features overlap", did you mean when `multi` is false?

**Comment by bjornharrtell** [comment]
I can admit that I did not consider the conditional select logic at all when implementing multi, having problems grasping the details of it. It probably should affect the conditional select logic too.

With "multi allows only the top most feature to be selected when features overlap", did you mean when multi is false?

**Comment by doronhorwitz** [comment]
I'm going to bring the entire conversation back here. Instead of jumping between this pull request and the commit where ```multi``` was introduced.

@bjornharrtell, you are correct, when I said *"```multi``` allows only the top most feature to be selected when features overlap"*, I did mean when ```multi``` is false.

Referring to your [comments](https://github.com/bjornharrtell/ol3/commit/162c47eb3e0f6ea1bab192fb14b8f0c4cea7f5e0#commitcomment-10461557) in the commit where ```multi``` was introduced. I'm not sure I fully understand. I would think that a either a click or a shift+click would only select (or toggle) the top most feature when ```multi``` is false. Meaning that the multi logic should consider set operations.

**Comment by elemoine** [comment]
> 1. multi allows only the top most feature to be selected when features overlap. What if the top most feature is filtered out?

If setting `multi` to `false` means that only the top most feature is selected then I think no feature should be selected when that top most feature is filtered out. And I think that the behavior the current patch provides… Do you agree with that behavior?

**Comment by bjornharrtell** [comment]
@elemoine, that is only true for the case when set operations are not used. If set operations are used (for instance by pressing shift-click) all overlapping features are selected.

@doronhorwitz, you are right I didn't test your [fiddle](http://jsfiddle.net/doronhorwitz/022nnszd/) properly - both features are indeed selected with a single shift-click on the overlapping area even with `multi: false` which does seem wrong to me too. I suppose this is the same behaviour as before multi was introduced so I'm not sure how @elemoine and others feel about changing the behaviour.

**Comment by elemoine** [comment]
@doronhorwitz and @bjornharrtell, I don't see anything wrong with this particular patch. If there are problems with `multi` then we should create separate issues/PRs for these problems. I'll add tests and merge this if you agree.

**Comment by bjornharrtell** [comment]
@elemoine I agree.

**Comment by bjornharrtell** [comment]
I welcome efforts to create separate issues/PRs and for reference I'll just add that SelectOptions is not marked as stable but in effect the default behaviour is `multi: false` for simple selections and `multi: true` for set selections. The same behaviour can be observed before `multi` was introduced in the select-features example with careful examination. Shift-clicking *on* a border will select both features as they will fall within the tolerance of forEachFeatureAtPixel. Clicking without shift will select only the top most feature.

**Comment by doronhorwitz** [comment]
Sure, I agree.

**Comment by elemoine** [comment]
I've added tests enforcing the current behavior. I'm going to merge this when Travis reports success. Feel free to create new GitHub issues and continue the discussions in these issues.

**Comment by tschaub** [comment]
Ok, I think I've convinced @elemoine to see it another way.  While it's fresh, I'll record it here.  I'll try to find time to put together a pull request with changes to the code and tests - but if anybody else gets there first, I think we have consensus that this is the way it should be:

Use case 1 (click selects all features) - I have a vector source with "pet" features (dogs and cats).  I want a click to select all pets under the pointer.  This works with no special options.

Use case 2 (click selects some features) - Given the same vector source, I want a click to select all the cats under the pointer - even those that might be under dogs.  This works by setting `{filter: catsOnly}`.

Use case 3 (select one feature) - Now I want the user to be able to select one cat only (even if it is under a dog).  This should work by setting `{filter: catsOnly, multi: false}`.

**Pull request merged**
