### PR TITLE
Update to closure-util 1.6

### PR DESCRIPTION
**Pull request by elemoine**
And fix the ENAMETOOLONG error that occurs on Windows. See https://github.com/openlayers/closure-util/pull/68.

### CODE REVIEW

**Comment by fredj** [comment]
closure-util 1.6.1 is now published

**Comment by elemoine** [comment]
Branch updated. Waiting for Travis…

**Comment by elemoine** [comment]
Works now. Thanks @fredj!

**Comment by fredj** [comment]
Please merge

**Pull request merged**
