### PR TITLE
Support minZoom in ol.source.Stamen

### LINKED ISSUE #4853: Support minZoom in ol.source.Stamen
[These lines](https://github.com/openlayers/ol3/blob/13a981c94be6e4c79f54e1fdd1f052c39f46163b/src/ol/source/stamensource.js#L108-L109) have a `FIXME` which we might be able to remove, right?

AFAICT our tilegrid supports `minZoom`.

The `FIXME` wass added in 6d6188ea791b7d6033f9e0c2aeae9cccf004199d (nearly 3 years ago).

### PR DESCRIPTION
**Pull request by fredj**
Fixes #4853

### CODE REVIEW

**Comment by fredj** [comment]
@marcjansen can you take a look at this PR? thanks

**Comment by marcjansen** [comment]
This will need to wait until tomorrow. But then I promise to review this.

**Comment by marcjansen** [comment]
This looks very good to me, @fredj. Example works as expected, tests pass and the diff looks nice. 

Thanks for taking on this three year old [`FIXME`](https://github.com/openlayers/ol3/commit/6d6188ea791b7d6033f9e0c2aeae9cccf004199d).

Please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
