### PR TITLE
Use the correct TileCoord transform function

### LINKED ISSUE #3721: TileJSON sources not rendering correctly
Git bisect points to b05193fa454a963b33e6c5965181abde9b45b7fa.

image

I'm not sure this only affects TileJSON sources, but I see the same issue with the [popup](http://openlayers.org/en/master/examples/popup.html), [drag features](http://openlayers.org/en/master/examples/drag-features.html), [limited extent](http://openlayers.org/en/master/examples/layer-extent.html), and all other examples that [use TileJSON sources](http://openlayers.org/en/master/examples/?q=tilejson).

Seems like a good opportunity to add a rendering test for regressions.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #3721.

### CODE REVIEW

**Comment by marcjansen** [comment]
* popup example :white_check_mark: 
* vector-icon example :white_check_mark: 
* drag-features example :white_check_mark: 
* layer-extent example :white_check_mark: 
* layer-group example :white_check_mark: 
* min-max-resolution example: :white_check_mark: 
* semi-transparent-layer example: :white_check_mark: 
* tile-load-events example: :white_check_mark: 
* tilejson example: :white_check_mark: 
* tileutfgrid example: :white_check_mark: 
* topojson example: :white_check_mark: 

Definitively better than before :grin: 

Looks good to me, please merge.

**Comment by bartvde** [comment]
Any chance of adding a rendering test like @tschaub suggested?

**Comment by marcjansen** [comment]
Yeah that'd be cool. Even some unit tests for the tiled sources would be cool, coverage isn't so great there: see [tilejsonsource](https://coveralls.io/builds/2625554/source?filename=src%2Fol%2Fsource%2Ftilejsonsource.js) and [tileutfgridsource](https://coveralls.io/builds/2625554/source?filename=src%2Fol%2Fsource%2Ftileutfgridsource.js)

**Comment by ahocevar** [comment]
I'm adding unit tests. In this case it's all about using the correct tile coord, and that's better tested with unit tests than with rendering tests.

**Comment by elemoine** [comment]
Thank you @ahocevar!

**Pull request merged**
