### PR TITLE
Export getTileRangeForExtentAndZ and getZForResolution from ol.tilegrid.TileGrid

### LINKED ISSUE #5502: Please expose several public methods of ol.tilegrid.TileGrid in public api
Please expose the following methods of ol.tilegrid.TileGrid.prototype in your api:

1. ol.tilegrid.TileGrid.prototype.getZForResolution
2. ol.tilegrid.TileGrid.prototype.getTileRangeForExtentAndZ

I have implemented CartoDb Torque Layer for OpenLayers. I would like to contribute this implementation back to CartoDb and it is imposible without these methods.   Thanks.

### PR DESCRIPTION
**Pull request by fredj**
fixes #5502

### CODE REVIEW

**Comment by ahocevar** [comment]
Not sure about `#getTileRangeForExtentAndZ` - we have kept tile ranges internal until now, and I think we should keep it like this.

**Comment by ashchurova** [comment]
Maybe I ask why you prefer keeping #getTileRangeForExtentAndZ internal? It returns range of tiles based on extent and zoom values. Are there complications from making it available to developers? Because to me the method is harmless if you know what I mean.

I can tell you my reasons for this request - in my implementation of Ol Torque's Layer I need to get tthe range of tiles that should me loaded based on the current extent and pass them to tourge's engine to load them. In Ol the only way I have found so far is by calling the method above. I don't think there is a need to reinvent the wheel if the functionality is already there.  If there is an alternative way to get the tile range based on the extent  I would love to know. Thanks.

**Comment by ahocevar** [comment]
@ashchurova It would be easier to discuss this if we could see your code. Because other tile layer sources defer to the map's tile queue for loading tiles.

The reason why I'm hesitant to make `#getTileRangeForExtentAndZ` exportable is that the whole concept of tile ranges is currently being kept internal. If we start exposing `ol.TileRange`, we have to commit to it. The method itself may be harmless, but `ol.TileRange` and its API is quite awkward and not something our users should be confronted with.

**Comment by ahocevar** [comment]
@ashchurova How about providing an `ol.tilegrid.TileGrid#forEachTileCoordInExtent` method, which you would call like this:
```js
myTileGrid.forEachTileCoordInExtent(function(tileCoord) {
  // do something with tileCoord
});
```

**Comment by ashchurova** [comment]
@ahocevar  Fair enough. I am waiting for legal to approve my request today. They have already forked Torque under https://github.com/bloomberg/torque and I will commit my changes to that repository.

ol.tilegrid.TileGrid#forEachTileCoordInExtent would also work. That would be great.

Basically this is the short snippet of code but you will get the idea:

`   var zoom =  this._tileGrid.getZForResolution(this._view.getResolution());
    var extent = this._view.calculateExtent(this._map.getSize());
    var tileRange = this._tileGrid.getTileRangeForExtentAndZ(extent, zoom);
    
 this._addTilesFromCenterOut(tileRange, zoom);
`

**Comment by ashchurova** [comment]
@ahocevar though I need to be able to pass the extent as well so the signature should be like: 
 
```javascript
myTileGrid.forEachTileCoordInExtent(extent, function(tileCoord) {
  // do something with tileCoord
});
```

**Comment by ahocevar** [comment]
See #5509 for an implementation of the method I suggested above.

**Comment by ashchurova** [comment]
@ahocevar looks great. Thank you.

**Comment by fredj** [comment]
continues in #5509

**Pull request closed without merging**
