### PR TITLE
Use the maintained slimerjs package

### LINKED ISSUE #5005: Custom build
I've a got a lot errors on a custom building like:

```
ERR! compile /home/www/ol3/node_modules/closure-util/.deps/library/c00d1243c49bb8dad16f671f09a3facded9f3cd9/closure/goog/array/array.js:55: ERROR - Name Array in JSDoc is implicitly nullable.
ERR! compile Please add a ! to make it non-nullable, or a ? to make it explicitly nullable.
ERR! compile  * @typedef {Array|NodeList|Arguments|{length: number}}
ERR! compile              ^
```

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #5005.

### CODE REVIEW

**Comment by ahocevar** [comment]
Yay! Works for me locally on OSX, and Travis is happy too. Bye-bye slimerjs-edge.

**Comment by fredj** [comment]
LGTM

**Comment by tsauerwein** [comment]
:+1:

**Comment by marcjansen** [comment]
I am not so sure.

I changed an expected image so the rendering test fails (in a browser), but the error is only reported when run on the commandline:

```bash
$ make test-rendering 
node tasks/test-rendering.js
Gecko: 38.0.5

Script Error: [JavaScript Error: "Error: expected '48.60' to be below 1.5" {file: "http://127.0.0.1:3001/node_modules/expect.js/index.js" line: 96}]
       Stack:
         -> http://127.0.0.1:3001/node_modules/expect.js/index.js: 96

ol.rendering.Map #pan() tests the canvas renderer
Error: Error: expected '48.60' to be below 1.5 (http://127.0.0.1:3001/node_modules/expect.js/index.js:96)

1 test(s) failed.
```

image

**The return code of `make test-rendering` is `0` i.e. `success`, though.**

I think if we switch back to plain `slimerjs` we need to include the grepping of `stdout` against `test(s) failed`.

**Comment by marcjansen** [comment]
Something like

```diff
diff --git a/tasks/test-rendering.js b/tasks/test-rendering.js
index 04095e0..1332129 100644
--- a/tasks/test-rendering.js
+++ b/tasks/test-rendering.js
@@ -38,8 +38,17 @@ serve.createServer(function(err, server) {
       url + '/test_rendering/index.html'
     ];
 
-    var child = spawn(slimerjs.path, args, {stdio: 'inherit'});
+    var child = spawn(slimerjs.path, args, {stdio: 'pipe'});
+    var output = '';
+    child.stdout.on('data', function(data) {
+      output += data.toString();
+    });
     child.on('exit', function(code) {
+      var failedTestsRegExp = /[1-9][\d]* test\(s\) failed\./g;
+      if (failedTestsRegExp.test(output)) {
+        process.stderr.write('Test failures detected.\n');
+        code = 1;
+      }
       process.exit(code);
     });
   });
```

works for me.

**Comment by ahocevar** [comment]
Thanks @marcjansen, I updated the pull request with a modified version of your suggestion. Can you take another look please?

**Comment by marcjansen** [comment]
Works great now. Thanks for updating, @ahocevar.

Please merge if the build also passes on travis.

**Comment by tsauerwein** [comment]
The return code always being 0 was the original reason we used `slimerjs-edge`. But the pragmatic work-around by Mark is a good idea. Maybe we should match for "All tests passed", because there might be other reasons that running the tests fails, e.g. https://github.com/ahocevar/ol3/blob/fa17196cb3f4d08c7340e50b68a4b9466d0002b2/test_rendering/test.js#L28

**Comment by marcjansen** [comment]
> Maybe we should match for "All tests passed", …

I'd be OK with that as well.

**Comment by ahocevar** [comment]
Updated pull request to test for "All tests passed."

**Comment by marcjansen** [comment]
Also easier to read an reason about. Plus one for merging

**Comment by tsauerwein** [comment]
Thanks Andreas!

**Comment by marcjansen** [comment]
Yeah, thanks!

**Pull request merged**
