### PR TITLE
Avoid unnecessary nesting in ol.Overlay

### PR DESCRIPTION
**Pull request by tonio**
So that the positioned element is the one passed to `ol.Overlay`, not its parent.

One of my motivation to do it is to be able to set CSS transitions on my overlay’s element:
```css
.overlay {
  transition: top .2s, left .2s;
}
```

And then to have animated transition when setting position.

### CODE REVIEW

**Comment by fredj** [comment]
`bootstrap.min.js` can be removed from `examples/overlay.html`

**Comment by elemoine** [comment]
This needs rebasing here :-( I'll merge it as soon it is rebased. This has waited for too long already.

**Comment by fredj** [comment]
Upgrade notes must be added

**Comment by bartvde** [comment]
Any chance this can get rebased before 3.5.0 ?

**Comment by ahocevar** [comment]
I'm closing this now due to lack of activity. @tonio, please reopen if you're able to address the remaining concerns.

**Pull request closed without merging**
