### PR TITLE
Avoid use of goog.array.clone with arrays

### PR DESCRIPTION
**Pull request by tschaub**
When we know we're dealing with arrays (instead of something array like), use array prototype methods.

### CODE REVIEW

**Comment by elemoine** [comment]
Looks good. Thanks.

**Comment by bartvde** [comment]
Should we write some of these up in our code guidelines?
Or are they written up somewhere already?
Also things like the recent goog.object.set with 2 arguments which should not be used.

**Comment by elemoine** [comment]
Adding this to code guidelines would make sense to me. We already have a "coding style" section in the CONTRIBUTING.md file: https://github.com/openlayers/ol3/blob/master/CONTRIBUTING.md#follow-openlayers-3s-coding-style.

**Comment by bartvde** [comment]
cool I'll go through recent tickets and add them

**Pull request merged**
