### PR TITLE
Set language_in and language_out options to ECMASCRIPT5_STRICT

### LINKED ISSUE #3341: Set language_in and language_out compiler options to ECMASCRIPT5_STRICT
The code is already assumed to be `ECMASCRIPT5_STRICT`: https://github.com/openlayers/ol3/blob/master/config/ol.json#L35

### PR DESCRIPTION
**Pull request by fredj**
Fixes #3341

### CODE REVIEW

**Comment by elemoine** [comment]
What are the effects of using that?

**Comment by fredj** [comment]
`"use strict";` is added by the compiler to the output file.
According to [developer.mozilla.org] (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode): "strict mode code can sometimes be made to run faster than identical code that's not strict mode."

**Comment by elemoine** [comment]
LGTM. Why is this still wip?

**Comment by fredj** [comment]
@gberaudo just tell me that we need to make sure that projects builded along with ol3 still works

**Comment by gberaudo** [comment]
These projects use their own, separate, configuration files so it should be OK.

**Comment by fredj** [comment]
I also wanted to test if the mode is really activated because the documentation says that: 
"To invoke strict mode for an entire script, put the exact statement "use strict"; (or 'use strict';) **before any other statements**."

And it's not our case, we have a wrapper around the code (from #3039)

**Comment by fredj** [comment]
The strict mode is not activated by the browser because the statement is not the first one in the function.
We currently have:
```js
(function(root, factory) {
    if (typeof define === "function" && define.amd) {
        define([], factory);
    } else if (typeof exports === "object") {
        module.exports = factory();
    } else {
        root.ol = factory();
    }
}(this, function() {
    var OPENLAYERS = {};
    'use strict';
    var l, aa = aa || {}, ba = this;
    function m(b) {
...
```

But it should be:
```js
(function(root, factory) {
    if (typeof define === "function" && define.amd) {
        define([], factory);
    } else if (typeof exports === "object") {
        module.exports = factory();
    } else {
        root.ol = factory();
    }
}(this, function() {
    'use strict';
    var OPENLAYERS = {};
    var l, aa = aa || {}, ba = this;
    function m(b) {
...
```

**Comment by fredj** [comment]
Second issue (described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#.22Securing.22_JavaScript)).

In the compiled code, there's `var ba = this` statement (that's `goog.global = this`) but this is prohibited is strict mode unless the `this` is explicitly bound to the function.

**Comment by fredj** [comment]
Closing in favor of #3366

**Pull request closed without merging**
