### PR TITLE
Move typedefs to separate file

### PR DESCRIPTION
**Pull request by probins**
As discussed at length in #5299. I've split the changes into separate commits so the changes should be easier to follow.

After this PR, there are no `goog.require`s for typedefs apart from the 2 problem cases. I checked the api docs and it all looks ok.

The WFS typedefs are the only api ones in a sub-sub-namespace. When I put these in typedefs.js, not only were there compiler warnings/errors, but test.js decided to join in the fun and failed with "TypeError: undefined is not an object (evaluating 'ol.format.WFS.FeatureCollectionMetadata')
   in global code at http://127.0.0.1:3001/test/loader.js/home/travis/build/probins/ol3/src/ol/typedefs.js:389". Rather than spend time working out what this error was due to (presumably to do with the namespace), I moved these 2 typedefs to their own file, which resolves all problems with them. IMHO, it would not be a big deal renaming these to `ol.format.WFSFeatureCollectionMetadata` so they could go in `typedefs.js` with all the others. Strictly speaking, it would be an api-breaking change, but is not likely to affect many people and IMHO would not justify a major version number. However, I'll leave that to someone else to decide.

`ol.vec.Mat4.Number` is still outstanding, so #5299 should remain open until #5138 is resolved.

If there are any other outstanding PRs  which change typedefs, they will probably conflict with this one. And future PRs which add typedefs should add them to the new file not to the module code.

### CODE REVIEW

**Comment by ahocevar** [comment]
@probins:
> IMHO, it would not be a big deal renaming these to ol.format.WFSFeatureCollectionMetadata so they could go in typedefs.js with all the others. Strictly speaking, it would be an api-breaking change.

I do not think we consider types part of the API, because they are not exposed by the compiled library. Such a change would only affect the few users who compile the library together with their application. If mentioned in the upgrade notes, this should not be a hard change to make for these users.

**Comment by ahocevar** [comment]
I need to look at this a bit closer to see what these circular dependencies are about. But wouldn't these problems all go away if typedefs had just flat names, either directly in the `ol` namespace, or without namespace at all?

**Comment by probins** [comment]
@ahocevar yes, the issues are caused by the namespace, not the actual typedef itself. The namespace is created by `goog.provide`, so the 'owner', as the compiler calls it, is the main file for the namespace, which has a `goog.provide` so will create the namespace if not already present. This leads to 2 issues if there is no `goog.provide` for the namespace in the typedefs file:
* if the owner refers to the typedef, it 'depends' on it so the typedef has to come first but if the typedef file has no `goog.provide` for the namespace the compiler throws a 'namespace defined before its owner' warning
* application code compiled with the library may not use the namespace, so the 'owner' isn't present and the namespace never created, which leads to a compiler error. This case occurs when compiling the examples, as 2 of them refer to `ol.raster.Pixel` but the `ol.raster` namespace is not otherwise used, and never created.

Is that clear?

Several of the sub-namespaces have only non-api namespaces, so these could be renamed and put in the `ol` namespace. For the api ones, I doubt whether many people are using the WFS ones (the number may even be 0), but it's more likely that people are using, say, `ProjectionLike`, and it's a nuisance to have to change these references if the type name is changed - not a show-stopper, but a nuisance.

**Comment by ahocevar** [comment]
Thanks for the good explanation @probins. Like I said, I'm all in favour of renaming typedefs so they do not cause problems.

To move this forward, are you going to make the renaming here, or should that be done in a follow-up pull request?

**Comment by probins** [comment]
It's probably simpler if we do the renaming in a separate PR, then we can have discussion about api-breaking there and not hold up the basic project of moving the typedefs out of the code.

**Comment by ahocevar** [comment]
Alright, thanks @probins.

**Comment by gberaudo** [comment]
Sorry I was at Foss4g-fr conference this week, with a very bad internet connection and I could not follow as much as I would have wanted.

For me the situation is still quite confusing and it would have been better to investigate the full solution before merging.

Are we going to move the typedefs symbols out of any namespace? That would be insane as making the symbols globals they would conflict with any other library or system symbol.
Should everything be in ol? We may still have internal conflicts.
Should it be one more level? Why not two or three or more?

If the issue is only namespace ownership then moving typedefs to a dedicated `olt` hierarchy could have been a solution (it is what we do for `olx` and `oli`). It would have broken all typedefs but we could have provided a migration script for the library itself and for all users of the library.

**Comment by probins** [comment]
not sure I understand the problem

> making the symbols globals they would conflict with any other library or system symbol

typedefs are not exported anywhere, so they aren't symbols, and they aren't globals. 'api' in this case only means that they should appear in the docs.

IMO we can keep them in `ol`. Even when we switch to ES6, they can still stop there; with a `goog.provide`, GCC can continue to use them.

`olx` is different. The names of the options are exported and should not be renamed by the compiler. In any case, #4931 proposes changing these to `@record`.

**Comment by gberaudo** [comment]
They are symbols for the compiler and these symbols could conflict with other symbols (typedefs, enum, constructor...) coming from other libraries. All toplevel symbols are global.

When you are compiling several libraries together, it will fail if there are symbol conflicts.

**Comment by probins** [comment]
so we leave them in the `ol` namespace

**Comment by tschaub** [comment]
Having a dot in the name is arbitrary.  `ol.foo.Bar` is no less likely to conflict than `ol_foo_Bar`.  Both would be problems only when compiling together with a library that happens to pick the same name for a typedef, enum, constructor, etc.  The difference between the two is that the second one is uglier.

I imagine we'll revisit this with ES6 modules.  Having dots in the names will be awkward there.  TypeScript handles this with `export interface`.

**Comment by probins** [comment]
what's the procedure with change logs? Should I have put the changes in `upgrade-notes.md` rather than creating a new 3.16 file?

**Comment by ahocevar** [comment]
> Should I have put the changes in upgrade-notes.md rather than creating a new 3.16 file

Yes indeed. I had missed that during the review, because I did not look at the file name. Thanks for asking.

**Comment by probins** [comment]
ok, another PR coming up ...

**Pull request merged**
