### PR TITLE
fix ol.source.Vector#getFeaturesAtCoordinate

### PR DESCRIPTION
**Pull request by alvinlindstam**
As noted in https://github.com/openlayers/ol3/issues/3703, ol.source.Vector#getFeaturesAtCoordinate sometimes returns empty when it should return matching features.

Currently, it only returns features containing the coordinate, while the docs state that it should return all intersecting geometries. This PR changes this.

While doing this, I noted that ol.geom.Circle and ol.geom.LinearRing doesn't implements ol.geom.Geometry's abstract intersectsExtent method. This means that using this method will fail on any source containing those geometries. I'll open an issue about implementing intersectsExtent on those geometries. Perhaps that should be fixed, and these tests updated, before merging this PR?

### CODE REVIEW

**Comment by alvinlindstam** [comment]
However, i just realized that omitting geometry.intersectsExtent from some features might be deliberate. 

I guess that LinearRings does not intersect an extent that is completely contained within it, which would match the expected behaviour of getFeaturesAtCoordinate.

But is ol.geom.Circle a round LineString or a round Polygon? Should circle.intersectsExtent return true or false for an extent completely contained by the circle? Should ol.source.Vector#getFeaturesAtCoordinate return true or false for a coordinate within the circle? The expected behaviour is probably depends on the application, and the style of the circle (filled->true, non-filled->false).

**Comment by alvinlindstam** [comment]
I created a pull request for ol.geom.Circle#intersectsExtent here: https://github.com/openlayers/ol3/pull/3764

**Comment by marcjansen** [comment]
I commented https://github.com/openlayers/ol3/issues/3703#issuecomment-109248047 and would wait from input of the @-mentioned people.

**Comment by jonataswalker** [comment]
While this is not merged, ol.source.Cluster.getFeaturesAtCoordinate() is completely unusable. As mentioned, [ol.geom.Geometry.prototype.containsCoordinate](https://github.com/openlayers/ol3/blob/aa90c97ba3ffd59a0fba99669cce8702ed790d09/src/ol/geom/geometry.js#L134) always returns false.

**Comment by ahocevar** [comment]
I'm not sure how to proceed with this, because the relevant information is scattered across too many places. I'm closing this due to lack of activity, and would suggest a new ticket that summarises the problems and potential solutions.

**Pull request closed without merging**
