### PR TITLE
Merge in changes from the 3.11.1 release

### PR DESCRIPTION
**Pull request by tschaub**
This branch addresses regressions in the 3.11.0 release.

 - [X] #4403
 - [X] #4405
 - [X] #4406

### CODE REVIEW

**Comment by ahocevar** [comment]
@tschaub I also merged the fix for #4405 into this branch now. I'll add tests for #4408 in a separate pull request against master.

**Comment by bartvde** [comment]
looking into #4406 now which seems to be a regression as well

**Comment by marcjansen** [comment]
Shall we all try to concentrate on tests for our next point-release? We (including myself) have added way too many regressions in both 3.10 and 3.11. What do think?

**Comment by bartvde** [comment]
+100

**Comment by ahocevar** [comment]
@marcjansen Oh yes. +1.

**Comment by tschaub** [comment]
I'm going to update the description here to list the known regressions we're addressing in this release.

**Comment by tschaub** [comment]
Thanks for the work on this @ahocevar and @bartvde.  I couldn't find any regression related to #4409, so I've decided not to call that a blocker for 3.11.1.  There may very well be a bug, but I'll cut 3.11.1 now to get these fixes in.

**Pull request merged**
