### PR TITLE
Select the uppermost feature

### LINKED ISSUE #3218: Hectic movement of icons while hovering
I encountered a problem with the new release (3.2.0 that is). When icons are are close to each other and the map has a select interaction with condition: mouseMove this problem occurs. While moving the mouse over the icons the selected icon erratically changes. 
I would expect the selected icon to be the one laying directly under the mouse (like in version 3.1.1) or to be the icon of the feature which is nearest to the pointer.
I made a fiddle to demonstrate the issue:
http://jsfiddle.net/simon_seyock/45e1ddu1/1/

Greets and thanks,
Simon

### PR DESCRIPTION
**Pull request by fredj**
This is an attempt to fix #3218

### CODE REVIEW

**Comment by fredj** [comment]
A build is available at http://fredj.io/ol/ol-3221.js

**Comment by fredj** [comment]
Seems to work: http://jsfiddle.net/fredj/59ht45wu/

**Comment by bjornharrtell** [comment]
Thanks!

**Comment by ahocevar** [comment]
This change looks like the right fix to me. Thanks, and please merge.

**Comment by fredj** [comment]
Thanks for the review

**Comment by tschaub** [comment]
Thanks for tackling this @fredj!

**Pull request merged**
