### PR TITLE
[wip] Add new layout option to olx.format.ReadOptions

### PR DESCRIPTION
**Pull request by fredj**
To be able to choose between `XYZ` (the default) or `XYM`.

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for any review

**Comment by gberaudo** [comment]
+1

**Comment by ahocevar** [comment]
Having this new option in `olx.format.ReadOptions` and `olx.format.WriteOptions` results in documentation that suggests this is supported in all other feature formats too. So I think you should at least document in `olx.format.ReadOptions.prototype.layout` and `olx.format.WriteOptions.prototype.layout` for which formats this option is implemented.

In addition, I think the option should be named `geometryLayout`, not just `layout`.

**Comment by fredj** [comment]
I'm wondering if `olx.format.WriteOptions.prototype.layout` make sense.

**Comment by fredj** [comment]
replaced by #3388

**Pull request closed without merging**
