### PR TITLE
Possibility to restrict the type of features you can select

### PR DESCRIPTION
**Pull request by acanimal**
The `ol.interaction.Select`was modified to allow specify a `type` property, which is an array of geometry types, that allows to restrict the kind of geometries we can select. See: #3257 
An empty array '[]`means any geometry can be selected.

I also have created a new sample.

I documented the new property in the olx.js file but seems the apidoc tasks doesn't generates the API correctly. Need some help.

### CODE REVIEW

**Comment by acanimal** [comment]
I have some problems documenting in olx.js so code doesn't pass the CI. Now, seems all correct.

**Comment by tschaub** [comment]
As suggested in #3257, if we are going to add an option, I think it should be `filter` (`function(ol.Feature):boolean`).

**Comment by acanimal** [comment]
working on...

**Comment by acanimal** [comment]
I close this PR. For some reason it is duplicated at #3277

**Pull request closed without merging**
