### PR TITLE
Enable tests for ol.geom.flat.reverse

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by elemoine** [comment]
Good catch.

Do we have a CLA from you?

**Comment by icholy** [comment]
I just submitted it.

**Comment by icholy** [comment]
@elemoine were you able to verify that I submitted a CLA?

**Comment by elemoine** [comment]
I'm not the one receiving CLA submissions. @tschaub?

**Comment by tschaub** [comment]
@elemoine it looks to me like you do have edit rights to the [ICLA form](https://docs.google.com/spreadsheet/viewform?formkey=dGNNVUJEMXF2dERTU0FXM3JjNVBQblE6MQ) responses.  I found the responses by going to the [CLA readme](https://github.com/openlayers/cla), clicking on the ICLA form, finding the "edit this form" button, and then clicking "view responses."  Yes, there are outdated docs around and we should migrate to CLAHub.

**Comment by elemoine** [comment]
I'm not seeing the "edit this form" button for some reason.

**Pull request merged**
