### PR TITLE
Pass null as forEachFeatureAtPixel layer arg for unmanaged layers

### LINKED ISSUE #4114: Draw interaction does not work as expect when there is a select interaction
```
diff --git a/examples/draw-features.js b/examples/draw-features.js
index b7cb4ce..5f13bae 100644
--- a/examples/draw-features.js
+++ b/examples/draw-features.js
@@ -2,6 +2,7 @@ goog.require('ol.Map');
 goog.require('ol.View');
 goog.require('ol.geom.Polygon');
 goog.require('ol.interaction.Draw');
+goog.require('ol.interaction.Select');
 goog.require('ol.layer.Tile');
 goog.require('ol.layer.Vector');
 goog.require('ol.source.MapQuest');
@@ -46,6 +47,8 @@ var map = new ol.Map({
   })
 });
 
+map.addInteraction(new ol.interaction.Select());
+
 var typeSelect = document.getElementById('type');
 
 var draw; // global so we can remove it later
```

screen shot 2015-09-15 at 19 26 23

Is there an obvious reason why this combination of interactions should be avoided?

### PR DESCRIPTION
**Pull request by ahocevar**
See https://github.com/openlayers/ol3/pull/4143#issuecomment-154518582.

Fixes #4114.

### CODE REVIEW

**Comment by ahocevar** [comment]
@bartvde, you may want to have a look to see how this affects #4114.

**Comment by bartvde** [comment]
#4114 is this still the same @ahocevar with this change
Assuming you mean if I still see the issue in your branch?

**Comment by ahocevar** [comment]
@bartvde I meant you should look at my branch to see if it makes your life easier, so you don't need a code snippet like the one you posted in your application.

Your issue is unlikely to be fixed with this branch, but it might. Because now forEachFeatureAtPixel is only called once for features that are on multiple unmanaged layers.

**Comment by ahocevar** [comment]
@bartvde I added a commit that fixes #4114. Please review.

**Comment by bartvde** [comment]
thanks @ahocevar I can confirm that this now fixes my issue from #4114
I'll do a review of the code tomorrow morning if no one gets to it before then.

**Comment by bartvde** [comment]
LGTM @ahocevar does this deserve a mention in the release notes?

**Comment by ahocevar** [comment]
I can add that, yes.

**Comment by ahocevar** [comment]
Done @bartvde.

**Comment by bartvde** [comment]
LGTM @ahocevar please merge if Travis agrees again

**Pull request merged**
