### PR TITLE
Ignore index.html in example list

### LINKED ISSUE #3685: Don't include index.html in example list
Load http://openlayers.org/en/master/examples/ and search the page for `undefined`

### PR DESCRIPTION
**Pull request by fredj**
Fixes #3685

### CODE REVIEW

**Comment by bartvde** [comment]
@fredj I cannot reproduce your original issue?

**Comment by fredj** [comment]
ol3_example_undef

**Comment by bartvde** [comment]
ah I misunderstood you and used the search box in the example page

**Comment by bartvde** [comment]
LGTM

**Comment by fredj** [comment]
> ah I misunderstood you and used the search box in the example page

Sorry, it wasn't clean at all !

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
