### PR TITLE
Remove ol.style.ImageState and use ol.ImageState instead

### LINKED ISSUE #5799: ol.ImageState vs ol.style.ImageState
We have two enums for the loading state of an image:
 * `ol.ImageState`: https://github.com/openlayers/ol3/blob/v3.18.0/src/ol/imagebase.js#L9-L17
 * `ol.style.ImageState`: https://github.com/openlayers/ol3/blob/v3.18.0/src/ol/style/image.js#L5-L13

We should only keep one

### PR DESCRIPTION
**Pull request by fredj**
fixes #5799

### CODE REVIEW

**Comment by ahocevar** [comment]
Good to merge! I assume you were planning to rename ol.ImageState to ol.Image.State as part of #5794.

**Comment by fredj** [comment]
`ol.ImageState` renamed to `ol.Image.State`

**Comment by ahocevar** [comment]
Nice, please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
