### PR TITLE
Adjust iframe's position of GetFeatureInfo examples

### PR DESCRIPTION
**Pull request by jonataswalker**
wrong

Adjusted to:

adjusted

Fixes https://github.com/openlayers/ol3/issues/4182

### CODE REVIEW

**Comment by jonataswalker** [comment]
I don't understand why I have other commits in this PR. Is this a problem?

**Comment by marcjansen** [comment]
Yes, we will not merge PRs with unintended commits. You can however change this PRs branch as often as you want and even `--force push` after a rebase. Alternatively, just close this PR and create a new PR from a clean branch.

**Comment by jonataswalker** [comment]
Ready for review.

**Comment by marcjansen** [comment]
Good to go now, thanks @jonataswalker.

**Pull request merged**
