### PR TITLE
Do not rotate map canvas after composition

### LINKED ISSUE #5004: updated 3.12.1 => 3.14.2 and got blurry view
Before:

After:

As you can see both tile layer and vector labels layer are blurry. What can cause such problem?
Now I'm trying to find out which version is causing the problem.

### LINKED ISSUE #5067: Rendering issues with the immediate API
In 3.13.0, it was possible to use `precompose` and `postcompose` along with the immediate rendering API to clip layer rendering to a geometry.  See this example clipping a layer to a polygon: http://jsfiddle.net/yqwyp8md/

v3 13 0

In 3.14.2, the same example shows nothing rendered for the layer: http://jsfiddle.net/s4jrdqdc/

v3 14 2

In master (with the current hosted build of master), the example sort of works.  It renders initially, but then flashes during rotation, and will disappear completely when the map is resized: http://jsfiddle.net/r87meu6c/

master

### PR DESCRIPTION
**Pull request by ahocevar**
This requires to draw tile layers to an intermediate canvas again, but only when the view is rotated.

Fixes #5004.
Fixes #5067.

### CODE REVIEW

**Comment by ahocevar** [comment]
@tschaub, you might want to take a look at this, because it fixes #5067 and brings back the rendering quality from v3.13.1, while keeping things as simple as previously in master.

**Comment by tschaub** [comment]
Checkin it.

**Comment by tschaub** [comment]
Rendering looks really nice.

**Comment by tschaub** [comment]
This looks great.  The rendering tests are helpful.  The examples I tested work well.  Please merge.

**Pull request merged**
