### PR TITLE
Upgrade to geodesicflatgeom.js

### PR DESCRIPTION
**Pull request by bill-chadwick**
Changes in preparation for an upgraded graticule that will be able to
show grids of any projection, not just a lat/lon EPSG:4326 grid.

Make the basic path interpolate and transform function public. It will
be used for generating sets of points a fixed horizontal distance apart
on EPSG:3857.

Add public functions for drawing horizontal and vertical grid lines in
one projection in another projection where they may be curves.

### CODE REVIEW

**Comment by elemoine** [comment]
Thanks for the PR. I'll review it.

**Comment by bill-chadwick** [comment]
Eric,

The interpolate+transform function (was named line_) is a generic one,
useful for transforming a path between one projection and another.

It has nothing to do with geodesics itself, hence my earlier observation
that it might sit better elsewhere in the ol3 class structure.

The Great Circle and Meridian functions do generate geodesics for spherical
source coordinate systems (4326).

Parallels (on 4326) are not geodesics.

It might be that my new 'customMeridian' and 'customParallel' would be
better named 'vertical' and 'horizontal' say and use

x and y variables rather than lon and lat.

I added the new functions at the bottom of the file to minimise the github
diff. I believe you prefer methods in alpha order.

These changes are all perhaps a bit tricky because of the bad fit of the
methods with the geodesic namespace and the filename geodesicflatgeom.js

Bill.

**Comment by elemoine** [comment]
> Changes in preparation for an upgraded graticule that will be able to
> show grids of any projection, not just a lat/lon EPSG:4326 grid.

A non lon/lat graticule will always be represented as horizontal and vertical lines right? So I don't understand why you'd use the subdivision algorithm when creating a non lon/lat graticule.

**Comment by bill-chadwick** [comment]
Eric,
The British National Grid on a Web Mercator is made up of curves. UTM grid
on  Web Mercator map will be too. A BNG grid on  BNG map will be horizontal
and vertical lines.

See the graticule and Bing examples here http://www.bdcc.co.uk/ol3/examples/
.

The subdivision nicely matches the curves with the map resolution using the
minimum of line segments. Just like the great circle curves shown on a Web
Mercator map using the same geodesic flat geom interpolate code.

The graticule on the ol3 Sphere Mollweide example has a lat lon graticule
that has curved parallels and meridians.

Bill

**Comment by bill-chadwick** [comment]
Eric,
My suggestion might be to move the subdivision function to a new module.
Leave just the great circle function in the existing module and move the
meridian and parallel functions into the graticule module (as private) I
doubt they are used elsewhere.
Bill

**Comment by elemoine** [comment]
Thanks @bill-chadwick. Quick question: why is the Web Mercator graticule not a cartesian grid on the Bing map?

**Comment by bill-chadwick** [comment]
Eric,

A regular horizontal / vertical grid on Web Mercator would show Web
Mercator coordinates. However such a grid is not very useful - it does not
show points a fixed distance in metres apart, because scale changes with
latitude. The WM graticule I propose first draws a horizontal parallel and
vertical meridian intersecting at the view centre. After that parallels and
meridians are drawn as a locii of points a fixed distance apart. The
parallels stay straight and horizontal but get closer together near the
poles. The meridians are curves showing how scale changes with latitude.
This is where the subdivision algorithm comes in again. If on my examples
page you look at the UK map with graticules and turn on the WM graticule
you will see its meridians are parrallel, equally spaced verticals.

The scale bar control shows the scale at the centre of the view.

I cant see many use cases for the WM graticule other than as a glorified
scale bar or to demonstrate the properties of the WM projection.

To be useful with grid references, the BNG and UTM graticules will in the
near term need labels.

Back on my Bing example, you shuld see a very good fit for the BNG
graticule with the grid on the map - at all extremes of the UK.

Does that help?

Bill

**Comment by bill-chadwick** [comment]
This link

http://en.wikipedia.org/wiki/Mercator_projection#/media/File:World_Scale_from_DMA_Series_1150_map.png

shows how scale changes with latitude.

**Comment by bill-chadwick** [comment]
In an earlier post I should have written 

The parallels stay straight and horizontal but get further apart near the poles.

**Comment by ahocevar** [comment]
@elemoine Are you going to take another look at this?

**Comment by elemoine** [comment]
> @elemoine Are you going to take another look at this?

Not sure. @bill-chadwick, is this something you think we should have/do?

**Comment by bill-chadwick** [comment]
I still stand by my suggestion of 30th March. Move the subdivision to say
ol.proj and the meridian and parallel functions into the graticule.

The subdivision is used to map a single straight line segment in one
projection to a curve in another.

I think now perhaps that the graticule should always just show a lat/lon
grid and maybe a new grid.js be used for a regular equidistant grid on BNG,
UTM and other 'local' projections where the grid lines are vertical and
horizontal (on their own projection).

BNG and UTM grids etc on Web Mercator (made up of curves) can come later.

I will not be able to do any work on this fir a couple of weeks.

Bill

**Comment by bill-chadwick** [comment]
Actually the source path for the subdivision may be a curve between point a
and point b rather than a straight line e.g when computing great circle or
geodesic points rather tham meridians or parallels.

**Comment by bill-chadwick** [comment]
I am going to have another go at this now. First up I have re-synced my branch to the OL3 master and will start again with fresh updates.

**Pull request closed without merging**
