### PR TITLE
closure-compiler v20150729 compatibility

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by tschaub** [comment]
This looks ok to me, but it's a bit unfortunate.

Can you update the title to better describe what this is about ("20150729 compatibility" is pretty obscure)?  It would also be nice to have the description explain why these `missingProvide` comments are here.

**Comment by elemoine** [comment]
I am also interested to know why we need to add these `@suppress {missingProvide}` annotations.

**Comment by fredj** [comment]
With the new compiler, every classes tagged with `@constructor` must by provided with `goog.provide`.

We can either add a `@suppress {missingProvide}` annotation or provide the class even if it is not used.

**Comment by elemoine** [comment]
+1 for adding the `goog.provide`. We'll need them anyway when compiling together with ol3.

**Comment by fredj** [comment]
`ol.SelectEvent` and `ol.ModifyEvent` should probably be renamed to `ol.interaction.SelectEvent` and `ol.interaction.ModifyEvent`

**Comment by elemoine** [comment]
Very nice @fredj. LGTM.

**Comment by fredj** [comment]
Thanks for the review @elemoine.

**Pull request merged**
