### PR TITLE
Add tile loading events to image tile sources

### PR DESCRIPTION
**Pull request by tschaub**
This adds `tileloadstart`, `tileloadend`, and `tileloaderror` type events to tile sources.

### CODE REVIEW

**Comment by tschaub** [comment]
Here's the example demonstrating a simple progress bar monitoring tile loading for a single source:
http://tschaub.net/ol-tile-load-events/examples/tile-load-events.html

**Comment by bartvde** [comment]
This looks like a solid piece of much welcome work @tschaub 
LGTM

**Comment by tschaub** [comment]
Thanks for the review @bartvde.  I reworded that [commit message](https://github.com/tschaub/ol3/commit/199fcb05e3fc643bc95a050b3b318285f460b494).  Will merge when Travis goes green.

**Comment by tschaub** [comment]
Now that we [register an additional listener](https://github.com/openlayers/ol3/blob/b8e3deb7566999b713579aef654606832ce5229a/src/ol/source/tileimagesource.js#L124-L125) for tile events, it will be nice to avoid creating tiles that are not needed.  These listeners aren't unregistered until the tile cache for a source [is full](https://github.com/openlayers/ol3/blob/b8e3deb7566999b713579aef654606832ce5229a/src/ol/tilecache.js#L50).  See #3246 for a change that avoids unnecessary tile creation.

**Comment by bartvde** [comment]
hey @tschaub forgot to ask, but do you have plans to add events for image sources as well or not? If not, I can probably take a crack at it.

**Comment by tschaub** [comment]
@bartvde yes - I'd like to do the same.  But I'm not working on it currently, so it would be great if you wanted to take it on.  If I do find some time for it, I'll open a ticket first to indicate that I'm working on it.

**Comment by elemoine** [comment]
Nice work @tschaub.

**Pull request merged**
