### PR TITLE
Better docs for ol.ENABLE_[WEBGL|CANVAS|DOM]

### PR DESCRIPTION
**Pull request by elemoine**
@ahocevar, this is my modest replacement for https://github.com/openlayers/ol3/pull/4016 :)

### CODE REVIEW

**Comment by probins** [comment]
somewhat off-topic, but why is DOM not api?

**Comment by elemoine** [comment]
> somewhat off-topic, but why is DOM not api?

Probably because it's currently useless for the user.

**Comment by probins** [comment]
in which case, why not delete it?

**Comment by ahocevar** [comment]
Nice improvement, thanks @elemoind. Please merge.

@probins `ol.has.DOM` is used internally (ok, only once, so could be replaced with `ol.ENABLE_DOM`. But that can be handled seperately if we decide to do so.

**Comment by elemoine** [comment]
Thanks @ahocevar.

**Pull request merged**
