### PR TITLE
Call the change callback when a non idle tile is removed from the queue

### PR DESCRIPTION
**Pull request by fredj**
This PR fixes the side-by-side example (#4431), the regression was introduced in #3895

### CODE REVIEW

**Comment by tschaub** [comment]
@fredj thanks for digging into this.  Do you understand how a tile in the queue becomes non-idle without the change callback being called?  It would be easier to understand if we only called the "change" callback in a change listener.

**Comment by fredj** [comment]
probably because an other map loaded it

**Comment by tschaub** [comment]
This suggests we should register a listener when a tile is added to the queue - not only when `loadMoreTiles` is called.

**Comment by fredj** [comment]
Calling `this.tileChangeCallback_()` tells the other map that it must `this.Map#render` because a tile is loaded. I don't know if this change is enough

**Comment by fredj** [comment]
This change fixes the side by side example but
b7e

**Comment by marcjansen** [comment]
😆

**Comment by bartvde** [comment]
LOL I feel like this very often ;-)

**Comment by tschaub** [comment]
Let's make sure we get a solid fix in here.  Calling the change callback when there is no change feels like it will come back to haunt us.  I think the root of the issue is that we are not listening for change until too late.

**Comment by fredj** [comment]
> This suggests we should register a listener when a tile is added to the queue - not only when `loadMoreTiles` is called.

Yes, good suggestion

**Comment by fredj** [comment]
See https://github.com/openlayers/ol3/compare/master...fredj:tilequeue_listen_in_enqueue for a better solution

**Comment by bartvde** [comment]
@fredj can you PR the better solution? And maybe close this one?

**Comment by fredj** [comment]
@bartvde now in #4536

**Pull request closed without merging**
