### PR TITLE
Add new use_strict option to the build config

### PR DESCRIPTION
**Pull request by fredj**
Optional flag to create an ECMAScript 5's strict mode build. Default is false.

### CODE REVIEW

**Comment by gberaudo** [comment]
Looks good.

**Comment by elemoine** [comment]
LGTM too. It would be good to know what @tschaub thinks about this before merging.

**Comment by fredj** [comment]
It works when `umd` is `true` but I haven't check without

**Comment by fredj** [comment]
work when `umd` is false

**Comment by fredj** [comment]
@tschaub: do you agee with this change?

**Comment by tschaub** [comment]
I think this is probably safe enough since it is opt in.  Though we may surprise people who try to concatenate our full build together with another script that is not strict.

I think it would be safer to use strict mode for the function that we create in the wrapper only.  But I know the change wouldn't be as clean.

@fredj what do you think about function as opposed to script level strict?

**Comment by fredj** [comment]
I've activated the strict mode in my project (builded with ol3 using closure-util).

`build.json`:
```json
{
  "compile": {
    "output_wrapper": "(function(){%output%}).call(window);",
    "language_in": "ECMASCRIPT5_STRICT"
  }
}
```

**Pull request closed without merging**
