### PR TITLE
AssertionError in WMTS.optionsFromCapabilities.

### PR DESCRIPTION
**Pull request by bartvde**
This method is only checking the first object of the 'gets' array.  The 'KVP' encoding is contained within the 2nd object of the WMTS capabilities document returned by ArcGIS.  Shouldn't this code evaluate the entire array?

    ...
    } else {
    var gets = wmtsCap['OperationsMetadata']['GetTile']['DCP']['HTTP']['Get'];

    var constraint = goog.array.find(gets[0]['Constraint'],
        function(elt, index, array) {
          return elt['name'] == 'GetEncoding';
        });
    var encodings = constraint['AllowedValues']['Value'];
    if (encodings.length > 0 && goog.array.contains(encodings, 'KVP')) {
      requestEncoding = ol.source.WMTSRequestEncoding.KVP;
      urls.push(/** @type {string} */ (gets[0]['href']));

      }
    }
    goog.asserts.assert(urls.length > 0);

### CODE REVIEW

**Comment by bartvde** [comment]
PR attached, TIA for any review.

**Comment by ahocevar** [comment]
Looks good.

**Comment by elemoine** [comment]
Thanks for fixing this @bartvde.

**Comment by Manfred73** [comment]
Hi,

I'm also getting an AssertionError when doing ol.source.WMTS.optionsFromCapabilities:

`
Uncaught AssertionError: Assertion failed: default value contained in values - ol-debug.js:4600
`

I'm using mapcache with some regex dimension for TIME parameter, like so:

```
   <source name="wind_area" type="wms">
      <getmap>
         <params>
            <REQUEST>GetMap</REQUEST>
            <LAYERS>wind_area</LAYERS>
         </params>
      </getmap>
      <http>
         <url>http://mapserverurl.com/cgi-bin/mapserv?map=/var/www/mapserver/mapfile.map</url>
      </http>
   </source>
   <tileset name="wind_area">
      <source>wind_area</source>
      <cache>disk</cache>
      <grid>WGS84</grid>
      <grid>g</grid>
      <format>PNG</format>
      <metatile>4 4</metatile>
      <metabuffer>0</metabuffer>
      <expires>0</expires>
      <dimensions>
         <dimension type="regex" name="TIME" default="2016-01-01T18:00:00.000Z">20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9][0-9][0-9]Z</dimension>
      </dimensions>
   </tileset>
```

In the front-end application we first do a getCapabilities request and parse the xml being returned:

```
    getCapabilities: function () {

        var url = http://mapcacheurl.com/mapcache/wmts?SERVICE=WMTS&REQUEST=GetCapabilities&VERSION=1.3.0";
        var oReq = new XMLHttpRequest();
        oReq.open("GET", url, false);
        oReq.send();

        var parser = new ol.format.WMTSCapabilities();
        var result = parser.read(oReq.responseText);

        return result;
    }
```

So far, all goes well.
But when we do the optionsFromCapabilities call (where result is the parsed xml from the getCapabilities function), we get the AssertionError:

```
        var options = ol.source.WMTS.optionsFromCapabilities(result,
            {layer: name, matrixSet: 'WGS84'}); 
```

After doing some debugging within ol-debug.js, the error seems to be related to the dimensions part of the xml (lines of code 119791 - 119805), specifically within lines 119797 - 119798 where the assertion is done; elt['Value'] evaluates to the regex value ["20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9][0-9][0-9]Z"] which does not match with the default value of "2016-01-01T18:00:00.000Z":

```
119791  var dimensions = {};
119792  if ('Dimension' in l) {
119793    l['Dimension'].forEach(function(elt, index, array) {     // elt = Object {Identifier: "TIME", Default: "2016-01-01T18:00:00.000Z", Value: Array[1]}, index = 0, array = [Object]
119794      var key = elt['Identifier'];     // key = "TIME"
119795      var value = elt['Default'];     // value = "2016-01-01T18:00:00.000Z"
119796      if (value !== undefined) {
119797        goog.asserts.assert(ol.array.includes(elt['Value'], value),
119798            'default value contained in values');
119799      } else {
119800        value = elt['Value'][0];
119801      }
119802      goog.asserts.assert(value !== undefined, 'value could be found');
119803      dimensions[key] = value;
119804    });
119805  }
```

The corresponding part within the xml from the getCapabilities is as follows:

```
<Layer>
<ows:Title>wind_area</ows:Title>
<ows:WGS84BoundingBox>
<ows:LowerCorner>-180.000000 -90.000000</ows:LowerCorner>
<ows:UpperCorner>180.000000 90.000000</ows:UpperCorner>
</ows:WGS84BoundingBox>
<ows:Identifier>wind_area</ows:Identifier>
<Style isDefault="true">
<ows:Identifier>default</ows:Identifier>
</Style>
<Format>image/png</Format>
<Dimension>
<ows:Identifier>TIME</ows:Identifier>
<Default>2016-01-01T18:00:00.000Z</Default>
<Value>
20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9][0-9][0-9]Z
</Value>
</Dimension>
<TileMatrixSetLink>
<TileMatrixSet>WGS84</TileMatrixSet>
</TileMatrixSetLink>
<TileMatrixSetLink>
<TileMatrixSet>g</TileMatrixSet>
</TileMatrixSetLink>
<ResourceURL format="image/png" resourceType="tile" template="http://mapcacheurl.com/mapcache/wmts/1.0.0/wind_area/default/{TIME}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png"/>
</Layer>
```

Is there a way to get this working with regex or should we use a different approach with regards to the TIME parameter?

**Comment by M2R1998** [comment]
how get identify in arcgis tile map server at openlayers 4.6.5

**Pull request merged**
