### PR TITLE
Add the OpenLayers logo and the OSGeo-project badge to README 

### LINKED ISSUE #4760: add OSGeo project badge to website
Would like to ask that the OSGeo project logo be added to the project website.

(We will also be removing the http://www.osgeo.org/openlayers landing page and directing visitors directly to http://openlayers.org)

### PR DESCRIPTION
**Pull request by marcjansen**
This PR suggests to add two images to our README:

* our very own logo (copied from the [openlayers.github.io](https://github.com/openlayers/openlayers.github.io/blob/build/assets/logo.svg)) repository
* the "OSGeo project" badge (copied from the [OSGeo SVN](https://trac.osgeo.org/osgeo/browser/marketing/logo/svg/OSGeo_project.svg))

Fixes #4760

### CODE REVIEW

**Comment by tschaub** [comment]
image

ugh ...

image

blech.

**Comment by marcjansen** [comment]
Is that screenshot from a checkout or from the 'github-view-file', @tschaub?

**Comment by marcjansen** [comment]
Ok got it. Will update.

**Comment by marcjansen** [comment]
I have opened a PR for updating the openlayers website here: openlayers/openlayers.github.io#57

If people agree to merge that one, the src-attributes vcan be changed to link to the resources on the website.

**Pull request closed without merging**
