### PR TITLE
Downgrade to mocha@2.3.4

### PR DESCRIPTION
**Pull request by tschaub**
See https://github.com/openlayers/ol3/pull/4726#issuecomment-175750681.

Also related:
 * mochajs/mocha#2060
 * mochajs/mocha#2060

And more upgrade hazards:
 * mochajs/mocha#2080 (see also the hanging tests on #243)

Before upgrading mocha, let's confirm `npm test` works locally and that the output is readable on Travis.

### CODE REVIEW

**Comment by tschaub** [comment]
Before:

image

After:

image

**Comment by marcjansen** [comment]
This looks good to me, thanks and please merge!

**Comment by boneskull** [comment]
@tschaub @marcjansen et al

Please see [this build](https://travis-ci.org/boneskull/mocha/builds/105518636) with the proposed fix, and [the summary of changes](https://github.com/boneskull/mocha/blob/master/CHANGELOG.md#245--2016-01-28).

If everything looks good, I will merge and release this so you guys can get back on track with new versions.

**Comment by marcjansen** [comment]
Thanks for pinging us, @boneskull. We'll definitely check this.

**Comment by tschaub** [comment]
Thanks @boneskull.  Here's a build in progress: https://travis-ci.org/openlayers/ol3/builds/105522588

All looks good locally.  Thanks for the work on this, and for reaching out about the fix.

**Pull request merged**
