### PR TITLE
Force a map render when the view is not updated

### LINKED ISSUE #4674: Tiles loading issue
- http://openlayers.org/en/master/examples/simple.html
 - pan

-> the tiles are not loaded

The issue is not present in the latest release (v3.12.1)

### PR DESCRIPTION
**Pull request by fredj**
Fixes #4674

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for any review

**Comment by ahocevar** [comment]
It would be interesting to understand why this is needed: why is the animating hint reset properly, but not the interacting hint?

If it fixes the issue, then please merge. A nicer fix would be a better way to notify renderers of view hint changes.

**Comment by ahocevar** [comment]
Do you think #4581 breaks other things too @fredj? If so, another solution would be to revert my changes from #4581 for now, and then implement something where renderers can get notified of hint changes without forcing a render.

**Comment by fredj** [comment]
I've only found the issue with the pan without kinetic but I didn't test everything.

**Comment by fredj** [comment]
ok, let's revert #4581 and find a better solution

**Comment by tschaub** [comment]
Late to the part here, but I found this a pretty nice solution.  Did anybody find other issues with #4581?

**Comment by ahocevar** [comment]
I tested mouse rotation and did not find any issues with #4581.

**Comment by fredj** [comment]
https://github.com/openlayers/ol3/issues/4674#issuecomment-171569706 from @petrsloup :
"Yes, this seems to be happening for me only when zooming and dragging *simultaneously*."

**Comment by ahocevar** [comment]
> "Yes, this seems to be happening for me only when zooming and dragging simultaneously."

How do I do that? I tested on my mobile now: dragging and pinch-zooming simultaneously works fine.

**Pull request closed without merging**
