### PR TITLE
Optionally enable hidpi support for Bing

### LINKED ISSUE #6031: BingMaps missing HiDPI setting
Bing Maps added support for HiDPI/Retina/Hi-PPI maps in 2015:

https://blogs.bing.com/maps/2015/02/12/high-ppi-maps-now-available-in-the-bing-maps-ajax-control

There currently seems to be no way to set the flag in `ol.source.BingMaps`. Will there be support for this?

### PR DESCRIPTION
**Pull request by bartvde**
fixes #6031

### CODE REVIEW

**Comment by bartvde** [comment]
thanks @ahocevar I am trying to find out if we are allowed to use this

**Comment by rbrundritt** [comment]
I'm on the Bing Maps team. It is find to use these high DPI tiles. However we recommend using "&dpi=d2" not "&dpi=d1" when the pixel ratio is 2.

**Comment by bartvde** [comment]
thank you @rbrundritt will make that change

**Comment by bartvde** [comment]
@rbrundritt it seems with ```&dpi=d2``` we don't get roads after a certain zoom level, and labels are omitted also for aerial with labels after a certain zoom level? Also what does the device parameter actually do? Is ```device=mobile``` needed for Desktop Retina screens as well? Any further guidance appreciated. TIA.

Compare 
[d1 & device mobile]
https://ecn.t3.tiles.virtualearth.net/tiles/h1202020200211.jpeg?g=5413&mkt=en-us&dpi=d1&device=mobile

[d2 & device mobile]
https://ecn.t3.tiles.virtualearth.net/tiles/h1202020200211.jpeg?g=5413&mkt=en-us&dpi=d2&device=mobile

[just device mobile]
https://ecn.t3.tiles.virtualearth.net/tiles/h1202020200211.jpeg?g=5413&mkt=en-us&device=mobile

**Comment by rbrundritt** [comment]
Ah, a few issues here. The dpi=2 setting is for our dynamic tile service which the newer Bing Maps controls use. The dynamic tile URL's are not yet returned by the Bing Maps REST imagery service, so open layers doesn't have access to those tiles yet. Continue using dpi=1 for now. In 6 months or less the REST imagery service will likely be updated to return the dynamic tile url's. Once that is done the dpi=2 parameter will work and is better suited for pixel density ratio for 2 or higher. dpi=1 is meant for pixel density ratios between 1 and 2 (i.e. 1.5) and is for roads. device=mobile is needed to access the high dpi tiles. This is a legacy name as this functionality was added originally for mobile devices, as there weren't any high DPI desktops at the time (years ago). The team can't change the name without breaking existing apps.

**Comment by bartvde** [comment]
thanks @rbrunditt all clear now

**Comment by bartvde** [comment]
@ahocevar is this still good to merge? Or you want to look over it again?

**Comment by bartvde** [comment]
thanks!

**Pull request merged**
