### PR TITLE
Release v3.19.1

### PR DESCRIPTION
**Pull request by marcjansen**
This is PR for the `v3.19.1` patch release.

Here is how I got there:

```bash
# create a branch off the v3.19.0 tag
git checkout -b release-v3.19.1 v3.19.0
# cherry pick the merges we are interested in
git cherry-pick -m 1 767bec4dc7a77cb6555b7eddac3fc75883a654ad
git cherry-pick -m 1 7834a95210c2bc1d67ed32f9109b7868564065b8
git cherry-pick -m 1 d90bfbde588d56b7be0304b7dfa1399386e4986a
git cherry-pick -m 1 04f070b159a2e2f3bb5bd5b6489bfd0b424acf8c
# create the changelog
./tasks/changelog.sh v3.19.0.. > changelog/v3.19.1.md
# edit the changelog, then add and commit
git add changelog/
git commit -m 'Changelog for v3.19.1'
# edit package.json, then add and commit
git add package.json
git commit -m 'Update package version to 3.19.1'
```

Both the diff of this PR and the changelog look as expected.

The above stzeps are from the [wiki-notes](https://github.com/openlayers/ol3/wiki/Release-Procedure) and @bartvde s suggestions.

Now this pull request cannot be merged.

I was also wondering which commit should get the new `v.3.19.1` tag? If I first merge (as it says on the wiki), and then tag, the v3.19.1 release would contain too many commits, right?

Should I alternatively tag the commit which changes the `package.json`.

I need advice on how to continue as I am a bit confused.

Anyone able to support me, @openlayers/ol3

### CODE REVIEW

**Comment by bartvde** [comment]
Here is what I had for 3.17.1 for instance: https://github.com/openlayers/ol3/pull/5557

**Comment by bartvde** [comment]
Good question on the tag though, I think I always just did this on master after the merge

**Comment by marcjansen** [comment]
I just force pushed here a new branch with the steps from the inital comment, I hope I haven't messed with someone.

> Good question on the tag though, I think I always just did this on master after the merge, but as you say this will then include other stuff as well?

Yes, that's what I understand…

The confict that doesn't allow me to merge is in `changelog/upgrade-notes.md` btw.

**Comment by marcjansen** [comment]
I will resolve the conflict manually and tag the commit 6092e6ecbb8fa5c9cb1e845abc31d2a333395bfb afterwards.

**Comment by ahocevar** [comment]
@marcjansen What I always do for a patch release is the following:

* Create a branch off the previous release tag (in this case v3.19.1)
* Cherry-pick the commits that should be included in the patch release
* Proceed with the release steps from the wiki

Does this help?

**Comment by marcjansen** [comment]
OK I am stuck and need advice.

> I will resolve the conflict manually and tag the commit 6092e6e afterwards

I did the following:

```bash
# in my clone with in an up-to-date master
# merge this branch, expect a merge conflict
git merge release-v3.19.1
# fix up the (trivial) conflict, add and commit
git add changelog/upgrade-notes.md
git commit
# push the commit to master at upstream
# upstream points to https://github.com/openlayers/ol3.git
git push upstream master
```

The last command fails with

```
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/openlayers/ol3.git'
```

I then undid these changes and started again from an up-to-date master-branch
```bash
# in my clone with in an up-to-date master
# checkout this branch
git checkout release-v3.19.1
# merge in the up-to-date master, expect merge conflict
git merge master
# fix up the (trivial) conflict, add and commit
git add changelog/upgrade-notes.md
git commit
# push the changed release-v3.19.1 to upstream
# upstream points to https://github.com/openlayers/ol3.git
git push upstream release-v3.19.1
```

The above leads to the following:

* This PR no longer has merge conflicts (good)
* This PRs diff only contains the changes to the `changelog/`-directory and the `package.json` (bad, I guess).

I then undid the above merge and pushed here again.

What do my fellow @openlayers/ol3 team members suggest to do?

PS: I won't have too much time to finish this today, but could continue after the weekend.

**Comment by marcjansen** [comment]
> @marcjansen What I always do for a patch release is the following:
>
> * Create a branch off the previous release tag (in this case v3.19.1)
>

I did this

>
> * Cherry-pick the commits that should be included in the patch release
>

Do you pick the explicit commits or the merge commit? Does this make any difference?

>
> * Proceed with the release steps from the wiki
>

I would, but currently cannot merge, see above

>
> Does this help?
>

All feedback helps me.

**Comment by ahocevar** [comment]
> Do you pick the explicit commits or the merge commit? Does this make any difference?

The merge commits - otherwise you'll get conflicts.

**Comment by marcjansen** [comment]
A part of the problem is that the past patch releases (so it seems to me) usually didn't need to mangle with `changelog/upgrade-notes`. This time we have a comment which only applies to `3.19.1`, coming from our change of the behaviour of the canvas fills.

TBH, one could think of leaving that change (#6034) out, and hope that the merge would be possible then. PR #6039 (fixing sth. from #6034) would than also not be part of this patch release.

**Comment by marcjansen** [comment]
>> Do you pick the explicit commits or the merge commit? Does this make any difference?
> The merge commits - otherwise you'll get conflicts.

Cool, I did that here as well.

**Comment by ahocevar** [comment]
Try to merge without fast-forward:
```
git merge --no-ff release-v3.19.1
```
If you're still stuck, I can take on this patch release if you want me to.

**Comment by marcjansen** [comment]
> `git merge --no-ff release-v3.19.1`

If I do this (supposedly on `master`), I won't be able to push to the master here at the `openlayers/ol3`-repo.

Did you mean

```
git merge --no-ff master
```

when on this branch (`release-v3.19.1`)

**Comment by marcjansen** [comment]
>  I can take on this patch release if you want me to

That would be very kind, otherwise we have to postpone until next week. Thanks for the offer, I'll take it and let you decide if you want to do it now, or wait until next week.

Thanks for the feeback friends.

**Comment by ahocevar** [comment]
> when on this branch (release-v3.19.1)

No, when on master.

**Comment by ahocevar** [comment]
Click the "Use the command line" link below for the full instructions.

**Comment by marcjansen** [comment]
@ahocevar. this doesn't help. master is protected against pushes.

or do I misunderstand this...

**Comment by ahocevar** [comment]
Usually github detects when you manually merge a pull request and should not block it.

**Comment by ahocevar** [comment]
I just tried with '--dry-run', and it works for me. Does it work for you too, or do you want me to perform the push @marcjansen?

**Comment by marcjansen** [comment]
please try, I am mostly offline now. thanks for taking over.

**Comment by marcjansen** [comment]
cool that it worked for you... it failed for me previously....

**Comment by ahocevar** [comment]
I'm finishing the release process for v3.19.1 now.

**Comment by marcjansen** [comment]
Hey @ahocevar, does the 3.19.1 release really only contain the four fixes?

**Comment by ahocevar** [comment]
Oops @marcjansen - your pull request was against master instead of v3.19.0. So our 3.19.1 release contains all changes since we branched off v3.19.0.

**Comment by ahocevar** [comment]
Too bad I did this with `brain: 'off'` configured.

**Comment by bartvde** [comment]
that's the same mistake I made then for 3.17.1, we should make this more explicit in the release procedure

**Comment by bartvde** [comment]
Actually it has happened before as well, we are not alone: https://github.com/openlayers/ol3/pull/5192

**Comment by bartvde** [comment]
Ignore that last one, that is only the merge of the version change, but it seems this was done differently in the past

**Comment by bartvde** [comment]
hey @ahocevar but even this one was against master: https://github.com/openlayers/ol3/pull/5829

**Comment by ahocevar** [comment]
Yes, my comment above was wrong. It is correct to merge the release branch into master, but the tag needs to be created before merging. So the above was my mistake, not @marcjansen's.

**Pull request merged**
