### PR TITLE
Use an abstract base class instead of IVectorContext

### PR DESCRIPTION
**Pull request by gberaudo**
By having the abstract methods in the base class, subclasses can simply
override the methods they actually provide.
Additionally, this change fixes a regression in webgl canvas immediate.

### CODE REVIEW

**Comment by tschaub** [comment]
This is looking good (with the removal of the interface as discussed).

> Additionally, this change fixes a regression in webgl canvas immediate.

Can you provide a link to the ticket or describe the issue a bit more so if it comes up again we can refer to this fix?

**Comment by gberaudo** [comment]
The interface is now completly removed.

The call to `replay.replay()` on the `IVectorContext` interface was not checked by closure.
This method is not part of the interface and it seems closure allows anything in that case.

By using an (abstract) type, we are required to cast to the appropriate type and then closure will complain if the parameters become wrong.

Please @tschaub, merge if it is good.

**Comment by tschaub** [comment]
Looks great @gberaudo.

**Comment by elemoine** [comment]
Good change.

**Pull request merged**
