### PR TITLE
Add imageSize regression test for ol.source.ImageWMS

### PR DESCRIPTION
**Pull request by ahocevar**
Added test as follow-up on #4408.

### CODE REVIEW

**Comment by marcjansen** [comment]
Gjslint now complaints that `image` is declared but not used.

**Comment by ahocevar** [comment]
Ok, another attempt then...

**Comment by ahocevar** [comment]
Now Travis is finally happy :smile:

**Comment by marcjansen** [comment]
Looks good to me. Please merge.

**Pull request merged**
