### PR TITLE
Add paragraph about supported browsers and polyfills

### PR DESCRIPTION
**Pull request by ahocevar**
See https://github.com/openlayers/ol3/pull/5516#issuecomment-231028871.

### CODE REVIEW

**Comment by probins** [comment]
there is currently a para on browser support in the introduction tutorial, which probably needs updating or replacing by what you're proposing here.

**Comment by marcjansen** [comment]
Thanks for this, Andreas

**Comment by ahocevar** [comment]
Thanks for the hint @probins, I updated the pull request with a change to that section too.

**Comment by ahocevar** [comment]
I now also updated the quickstart doc.

**Comment by marcjansen** [comment]
LGTM, please merge and thanks.

**Pull request merged**
