### PR TITLE
Improve vector tiles

### PR DESCRIPTION
**Pull request by vmx**
The vector tiles don't implement everything that is expected according to the documentation. This pull requests implements at least parts of it.

### CODE REVIEW

**Comment by elemoine** [comment]
@vmx, I am curious to know what your use-case is for this. Also, note that `forEachFeature` may generate the same feature multiple times. This will happen if the feature spans multiple tiles. Do you think that's a problem?

**Comment by vmx** [comment]
@elemoine It's what comes out of my WIP on the vector tile merging. I agree that the `forEachFeature` isn't really useful, the `addFeature` event is. So I guess I should remove the `forEachFeature` commit for now, but update the doc strings instead (as the docs say those functions are supported).

I would hope that I get my feature merging done, and if I do I think the `forEachFeature` would make sense again.

**Comment by elemoine** [comment]
> I would hope that I get my feature merging done, and if I do I think the forEachFeature would make sense again.

As I said on Twitter, my plan is to work on a different approach where the features are not merged together in the source, and Canvas clipping is used to avoid rendering problems on the tile boundaries.

**Comment by vmx** [comment]
@elemoine The use case is a different one. The feature merging will probably always be optional. It's not about the rendering, but if you want to interact with the features, like hovering them. Or will this also be addressed with your work?

**Comment by elemoine** [comment]
> @elemoine The use case is a different one. The feature merging will probably always be optional. It's not about the rendering, but if you want to interact with the features, like hovering them. Or will this also be addressed with your work?

No it won't.

**Comment by vmx** [comment]
I'm closing this one for now as it isn't fully thought through yet.

**Pull request closed without merging**
