### PR TITLE
Example usability improvements

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request adds the ability to cloak api keys and makes relative urls of additional resources work for copy/paste and in JSFiddle.

### CODE REVIEW

**Comment by bartvde** [comment]
LGTM @ahocevar please merge if Travis agrees

**Comment by marcjansen** [comment]
Some of the changes are also in your vector tiles PR, right, Andreas?

**Comment by ahocevar** [comment]
@marcjansen Right, I'm going to rebase that one afterwards - should simplify the review.

**Comment by marcjansen** [comment]
:+1:

**Pull request merged**
