### PR TITLE
Webgl polygons and lines (experiment)

### PR DESCRIPTION
**Pull request by gberaudo**
Basic support for rendering polygons with WEBGL.
Status:
[x] PolygonGeometry
[x] MultPolygonGeometry
[x] Fill with color
[x] Stroke with line width and color
[ ] picking / hit detection
[ ] feature skipping
[ ] Render to the eye?

### CODE REVIEW

**Comment by gberaudo** [comment]
Added experimental LineString and Polygon stroke.

**Comment by gberaudo** [comment]
After discussion at the code sprint we decided not to merge this PR yet.

**Comment by gberaudo** [comment]
vecor-labels-notext

**Comment by marcjansen** [comment]
Awesome work so far.

**Comment by fredj** [comment]
note: we probably don't need https://github.com/openlayers/libtess/ anymore

**Comment by NathanWilkins-NOAA** [comment]
Is there a timeline on when this will be merged into master/what remains to be done before it is? I'm very interested in making webgl my primary renderer.

**Comment by gberaudo** [comment]
There are many things to do and no timeline yet.
What should be done includes: 
- handle lines better (triangulation, joins, smoothing).
- handle picking (getFeaturesAtPixel), skipping features (not drawing some features of a layer).

**Comment by ahocevar** [comment]
Any update on the timeline?

**Comment by gberaudo** [comment]
@ahocevar, unfortunately there is still no timeline for this feature.
Interested persons may contact Camptocamp for founding the whole or part of the effort.

**Comment by bartvde** [comment]
@gberaudo does it make sense to keep this PR open or should we close it since we don't expect any work on it in the near future?

**Comment by gberaudo** [comment]
You are right @bartvde. If someone is interested in continuing the PR, feel free to reopen.

**Comment by sweco-sebhar** [comment]
Rebased on master with resolved conflicts https://github.com/bjornharrtell/ol3/commits/webgl_polygons.

**Pull request closed without merging**
