### PR TITLE
Allow to delete the starting or ending vertex

### LINKED ISSUE #3708: Can't delete end vertex of linestring
There are several outstanding issues for interaction.Modify, but afaics this one hasn't been raised. Looks like ol.interaction.Modify.prototype.removeVertex_ isn't allowing for this possibility, as one of left/right will be undefined in this case. So you can only delete a vertex within the linestring, not one of the end vertices.

### PR DESCRIPTION
**Pull request by rmichaelis**
Hi, 
With this PR, I would like to fix #3708 and to have the ability to delete the starting or ending vertex of a ```ol.geom.LineString```
Could someone please review ?

### CODE REVIEW

**Comment by probins** [comment]
I can take a look at this when I'm back home at the end of the week

**Comment by probins** [comment]
thanks for tackling this @rmichaelis. Just tested various moves/deletes/adds with my own code, and this LGTM. Anyone from the core team want to take a look?

**Comment by ahocevar** [comment]
Looks good to me too. @rmichaelis, can you please submit a [CLA](https://github.com/openlayers/cla) so we can merge this? Thanks.

**Comment by rmichaelis** [comment]
Thanks for the review.
The CLA has been submitted.

**Comment by ahocevar** [comment]
Thanks @rmichaelis. Would you be able to add a unit test?

**Comment by rmichaelis** [comment]
@ahocevar I'll add a unit test this week.

**Comment by rmichaelis** [comment]
I've just added my first tests. 
I hope that it is what you're expecting.

**Comment by probins** [comment]
it would be good if this one could be included in the next release, though I'm not sure the merge commit is wanted.

**Comment by rmichaelis** [comment]
Is someone awaiting an action from me before merging this PR ?

**Comment by ahocevar** [comment]
Thanks @rmichaelis. Sorry, this simply got lost in the queue. Merging now.

**Pull request merged**
