### PR TITLE
Example sources in examples dir and built examples in build/examples

### LINKED ISSUE #3547: Rename examples_src to examples
I'd like it if the built examples could go in `build/examples`.  This would make it easier to search for things in our sources (if you exclude `build` when searching) and people would be less prone to accidentally editing the built examples.

The slight downside of this is that after `npm start` you browse to `http://localhost:3000/build/examples/` to view the examples (instead of `http://localhost:3000/examples/`).  An alternative would be to rework things in a bigger way and run the development server with a different root, but I'm trying to make incremental improvements.

Any other opinions?

### PR DESCRIPTION
**Pull request by tschaub**
This moves the example sources to the `examples` directory.  When `tasks/build-examples.js` is run, built examples are in the `build/examples` directory.

Resources that are only required by examples are in the `examples/resources` directory (previously these were in `resources` at the root of the repo).  Example resources that don't need to be in the repo are loaded from a CDN.  I hope we can continue to pare down the resources required by our examples instead of adding more.

When running the development server (`tasks/serve.js` or `npm start`), you can browse the examples at http://localhost:3000/build/examples/.  I'm sure people will be confused when they try http://localhost:3000/examples/ (which serves the source example index.html without any content).  But I think this is still a usability improvement to have all built artifacts in the build directory.

One awkward bit is that the examples need the same relative path to `ol.css` in the development server and when deployed as part of the website.  For now, the `tasks/serve.js` script copies `css/ol.css` to `build/css/ol.css` every time the examples are built.  This is not ideal, but there are other things I'd like to change about `tasks/serve.js` before making a larger change.

Fixes #3547.

### CODE REVIEW

**Comment by elemoine** [comment]
Thank you very much for the huge effort on this @tschaub! To me, this is going in the right direction. I'd say feel free to merge when you think this is ready (and when the Travis build passes).

**Comment by tschaub** [comment]
Notes for posterity:

 * Protocol relative URLs will bite you (in Phantom for example)
 * Phantom's `--ignore-ssl-errors` option doesn't get around SSL handshake failures

**Comment by tschaub** [comment]
Ok, this is officially not fun any more.  Phantom fails because `$` is not defined in the `graticule.html` example, but the others work.  And of course the same passes for me locally.  So now we've got transient network issues making things fail.

I'd love to have simpler examples that didn't load Bootstrap and jQuery.  I'm not feeling like putting copies of the same back in our repo or having an extra build step that copies them in place.  So I'm going to ditch this effort for now.

**Comment by tschaub** [comment]
All passing now, but I'd like to make sure the `check-examples` target isn't unstable.

**Comment by tschaub** [comment]
This seems obvious in retrospect, but here's the key bit from debugging Phantom on Travis:
```
Resource request error: 6 ( "SSL handshake failed" ) URL: "https://code.jquery.com/jquery-1.9.1.min.js" 
```

So, protocol relative URLs [were a mistake](https://twitter.com/paul_irish/status/588502455530311680), we should [always load resources via SSL](https://www.eff.org/encrypt-the-web-report), but we have to remember not to because Travis can't shake hands.

**Comment by tschaub** [comment]
It may be that there is a PhantomJS option that will save us.  Testing.

**Comment by tschaub** [comment]
Ok, when Travis gives the green light, this should be good to go.

I've taken some liberties in adding commits that are not just about renaming `examples_src` to `examples`.  Having spent an inordinate amount of time debugging Phantom failures on Travis, I felt I was justified in cleaning up some other things that have been annoying me for a while.  Namely:

 * The `example-behavior.js` script is now named `common.js`
 * Instead of `exampleNS`, this script creates a `common` object
 * The `lint` task now runs on this script
 * There are no more base64 / binary data / UTF-8 strings utilities in this script

For those following along at home, though I removed the use of jQuery from a number of our examples, the examples do still load jQuery and it should be safe to use now that Phantom runs with the appropriate options on Travis.  I think it would be nice *not* to lean to heavily on it (or any jQuery plugins), but I think it is more sensible to use code in the examples that people will understand rather than duplicating jQuery-like functionality in our `common.js` script.  So, my preference is for straight DOM where practical, falling back to jQuery where the reduced verbosity makes the examples easier to follow.

**Comment by elemoine** [comment]
I agree with all your changes. Please merge before Travis changes his mind :-)

**Comment by tschaub** [comment]
> I agree with all your changes. Please merge before Travis changes his mind :-)

Thanks @elemoine.

**Comment by marcjansen** [comment]
Very impressive work, @tschaub. Thanks for taking so much time.

**Comment by bartvde** [comment]
I got tricked today by browsing to examples from the index page instead of to build/examples

Is there a way to hide this link or another solution?

**Pull request merged**
