### PR TITLE
Make make fail on requires and whitespace errors

### LINKED ISSUE #3638: make check does not fail on missing goog.require
And currently we have one missing `goog.require`:
```
Running jshint...
2015-04-28 17:03:02,039 check-requires: test/spec/ol/interaction/modifyinteraction.test.js:84 missing goog.require('ol.geom.Point')
2015-04-28 17:03:02,266 check-requires: 0 unused goog.requires, 1 missing goog.requires
node tasks/build.js config/ol.json build/ol.js
info ol Parsing dependencies
```
Is this intentional? cc @elemoine

### PR DESCRIPTION
**Pull request by elemoine**
Fixes #3638.

### CODE REVIEW

**Comment by ahocevar** [comment]
Looks great, thanks for fixing this so quickly. Please merge.

On a side note: is something broken with coveralls or with the way we use it? It does not run coverage tests any more.

**Comment by elemoine** [comment]
> On a side note: is something broken with coveralls or with the way we use it? It does not run coverage tests any more.

It should. https://github.com/openlayers/ol3/blob/master/.travis.yml#L15

I'd like to understand this and fix it asap.

**Comment by elemoine** [comment]
`make test-coverage` does not work locally for me:

```
node tasks/test-coverage.js
• copy src files to backup folder
• copy src files to instrumentation folder
• instrumenting every src file
fs.js:543
fs.writeSync = function(fd, buffer, offset, length, position) {
                                                            ^
Error: ENOENT, no such file or directory '/home/elemoine/src-instrumented/ol3/src/ol/animation.js'
    at Error (native)
    at Object.fs.openSync (fs.js:443:18)
    at Object.fs.writeFileSync (fs.js:989:15)
    at /home/elemoine/src/ol3/tasks/test-coverage.js:144:8
    at Array.forEach (native)
    at foundAllJavaScriptSourceFiles (/home/elemoine/src/ol3/tasks/test-coverage.js:139:9)
    at f (/home/elemoine/src/ol3/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/home/elemoine/src/ol3/node_modules/glob/glob.js:132:7)
    at Glob.EventEmitter.emit (events.js:107:17)
    at Glob._finish (/home/elemoine/src/ol3/node_modules/glob/glob.js:171:8)
make: *** [test-coverage] Error 1
```

@marcjansen any idea what's going on here?

**Comment by elemoine** [comment]
corveralls did run for https://github.com/openlayers/ol3/pull/3637, which does use the Makefile rather than build.py. So the corveralls problem seems to unrelated to the Makefile.

**Comment by ahocevar** [comment]
@marcjansen I got past @elemoine's point locally, but I get stuck here:

```
$ cat coverage/lcov.info | ./node_modules/.bin/coveralls

/Users/ahocevar/projects/ol3/node_modules/coveralls/bin/coveralls.js:18
        throw err;
              ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by marcjansen** [comment]
I am pretty sure that coveralls has some problems right now.

**Comment by elemoine** [comment]
The problem I have locally on my machine is different. It has nothing to do with coveralls.

**Comment by marcjansen** [comment]
> make test-coverage does not work locally for me:

That may be because you ran it twice? Or that a file was deleted? @bartvde opened issues wrt this: #3508 & #3506

Please try to remove the `coverage` folder in your checkout and try again.

**Comment by elemoine** [comment]
> That may be because you ran it twice? Or that a file was deleted? @bartvde opened issues wrt this: #3508 & #3506
> 
> Please try to remove the coverage folder in your checkout and try again.

Does not work for me. I still get the same error.

**Comment by marcjansen** [comment]
> @marcjansen I got past @elemoine's point locally, but I get stuck here:

This is most likely because you cannot simply post to coveralls when you aren't registered with them. Where did you run the `cat coverage/lcov.info | ./node_modules/.bin/coveralls` line?

Locally this will not work, on your fork of `ol3` only if you enabled coveralls for it. On `openlayers/ol3` this should work because uit is a registered service.

But I am seeing starnge cocveralls errors / pending checks as well in other repos: see e.g. KaiVolland/geoext3#7 or KaiVolland/geoext3#9

**Comment by marcjansen** [comment]
> Does not work for me. I still get the same error.

I want to reproduce this... give me some minutes.

**Comment by elemoine** [comment]
@marcjansen I get this error:

```
Error: ENOENT, no such file or directory '/home/elemoine/src-instrumented/ol3/src/ol/animation.js'
```

which indicates that the `test-coverage.js` task expects that `src-instrumented` directory is in `/home/elemoine`, which is not the case obviously.

**Comment by ahocevar** [comment]
Thanks for the explanation @marcjansen. I created https://github.com/lemurheavy/coveralls-public/issues/508.

**Comment by marcjansen** [comment]
@elemoine : This is the source: https://github.com/openlayers/ol3/blob/master/tasks/test-coverage.js#L142 That is a very lame to detect the path where we want to write. I do not have the time to fix this, sorry.

**Comment by elemoine** [comment]
@marcjansen I found the issue. This line in `test-coverage.js`:

```js
var outfile = file.replace(/\/src\//, '/src-instrumented/');
```

My `ol3` directory in under `/home/elemoine/src` on my machine, so this replace does not do the right thing in my case.

**Comment by marcjansen** [comment]
I was faster :-)

**Comment by marcjansen** [comment]
See #3643

**Pull request merged**
