### PR TITLE
Use imgSize when provided

### PR DESCRIPTION
**Pull request by ahocevar**
Alternative to #5035.

### CODE REVIEW

**Comment by ahocevar** [comment]
This is now ready for review.

**Comment by fredj** [comment]
LGTM

**Comment by tschaub** [comment]
Should this be marked as fixing #3220?

**Comment by ahocevar** [comment]
Definitely. Thanks @tschaub.

**Comment by GeoDodo** [comment]
Yes it works. Great work. Thank you!

**Pull request merged**
