### PR TITLE
Four small fixes (all found using phpstorm)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by tschaub** [comment]
Thanks for this @stweil.  I'd like to switch from JSHint to ESLint at some point soon.  The two `.js` issues would have been caught by ESLint rules.

**Comment by tschaub** [comment]
It doesn't look like we have a [CLA](https://github.com/openlayers/cla/blob/master/signed-agreements.md) on file for you.  Would you be able to [submit one](https://docs.google.com/spreadsheet/viewform?formkey=dGNNVUJEMXF2dERTU0FXM3JjNVBQblE6MQ)?

**Comment by stweil** [comment]
Am 12.02.2015 um 19:59 schrieb Tim Schaub:
>
> It doesn't look like we have a CLA 
> <https://github.com/openlayers/cla/blob/master/signed-agreements.md> 
> on file for you. Would you be able to submit one 
> <https://docs.google.com/spreadsheet/viewform?formkey=dGNNVUJEMXF2dERTU0FXM3JjNVBQblE6MQ>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openlayers/ol3/pull/3233#issuecomment-74129954>.
>

Done.

**Comment by tschaub** [comment]
Thanks for the contribution!

**Pull request merged**
