### PR TITLE
Report on installed versions in Travis

### PR DESCRIPTION
**Pull request by tschaub**
Checking to see how our cached `node_modules` might affect things.

### CODE REVIEW

**Comment by fredj** [comment]
What about to always display the version with `npm ls --depth=0`?

**Comment by tschaub** [comment]
That could be useful @fredj.

I was just suspicious here because I didn't see the updated Phantom getting installed in the log for [build 105115206](https://travis-ci.org/openlayers/ol3/builds/105115206).  So I was wondering if `npm install` wasn't doing what we want with the cached `node_modules`.  But on digging deeper I see that there was a [previous build](https://travis-ci.org/openlayers/ol3/builds/104777530) for the same branch where the correct version of Phantom was installed, and the cached `node_modules` for this branch was used in the subsequent build.

**Comment by tschaub** [comment]
@fredj I repurposed this to report on all versions based on your suggestion.  This serves as a sanity check at least.

**Comment by fredj** [comment]
+1

**Pull request merged**
