### PR TITLE
GML3 tests time out in unit tests

### PR DESCRIPTION
**Pull request by bartvde**
I hope it's just the tests that are slow and not the format parser or serializer. Anyway, here is some output from the tests:
```
  1451 passing (30s)
  1 failing
  1) ol.format.GML3 when parsing TOPP states GML writes back features as GML:
     timeout of 4000ms exceeded
```

### CODE REVIEW

**Comment by bartvde** [comment]
PR attached @ahocevar

**Comment by ahocevar** [comment]
Thanks @bartvde. One suggestion: now that there are no `#equals()` (and maybe other test methods) test error messages added to the xmleql error message any more, maybe you could replace "test failed for" with something that says that node1 and node2 are not equal? Would make it easier to understand the test output.

**Comment by bartvde** [comment]
good point @ahocevar I will make it so we will have the same output as before with e.msg

**Comment by ahocevar** [comment]
Great work @bartvde. Please merge when Travis gives the ok.

**Comment by bartvde** [comment]
thanks for all the help @ahocevar

**Pull request merged**
