### PR TITLE
Remove bin/check-requires.py

### PR DESCRIPTION
**Pull request by fredj**
The `missingProvide` and `missingRequire` compiler checks are already checking
if the `goog.require` and `goog.provide` are correct.

See https://github.com/openlayers/ol3/pull/3960#issuecomment-127635513

Comments welcome

### CODE REVIEW

**Comment by fredj** [comment]
The js files in test are not checked anymore

**Comment by tschaub** [comment]
Looks good to me.  Thanks @fredj.

**Comment by elemoine** [comment]
A bit unfortunate that the test files are not checked anymore.

**Comment by ahocevar** [comment]
Are you very unhappy with this @elemoine, or can we merge it?

**Comment by fredj** [comment]
This is not ready to merge; I want to check at this PR

**Comment by tschaub** [comment]
@fredj any additional work you want to do here?

**Comment by fredj** [comment]
See #4644 (I closed the PR by mistake and cannot reopen it)

**Pull request closed without merging**
