### PR TITLE
Wmts featureinfo

### PR DESCRIPTION
**Pull request by bianchimro**
This is a first implementation of the method ol.source.WMTS.getGetFeatureInfoUrl.
It adds an example of WMTS GetFeatureInfo and the method implementation.

This implementation is working only for WMTSRequestEncoding == 'KVP', and the example covers this case.

### CODE REVIEW

**Comment by sarametz** [comment]
I built on this by adding REST encoding functionality along with populating this from the WMTS capabilities in #3150. Please have a look at it if you're interested.

**Comment by ahocevar** [comment]
Unfortunately we never finished this review, and in the meantime too much has changed to make the build pass again with a simple merge. @bianchimro, any chance you'd be able/willing to finalize this work? I'm closing the pull request for now, but please reopen if you continue working on it.

**Comment by emirandamaqueda** [comment]
I write this code, to solve this issue: 
`var view= map.getView();
var source= layer.getSource();
var resolution= view.getResolution();
var tilegrid= source.getTileGrid();
var tileResolutions= tilegrid.getResolutions();
var zoomIdx, diff=Infinity;

for(var i=0; i<tileResolutions.length; i++){
    var tileResolution= tileResolutions[i];
    var diffP= Math.abs(resolution-tileResolution);

    if(diffP<diff){
        diff=diffP;
        zoomIdx=i;
    }

    if(tileResolution<resolution) break;
}

//Getting parameters
//Reference: OpenLayers.Layer.WMTS.getTileInfo
var tileSize= tilegrid.getTileSize(zoomIdx);
var tileOrigin= tilegrid.getOrigin(zoomIdx);

var fx = (this.coordinate[0] - tileOrigin[0]) / (resolution * tileSize);
var fy = (tileOrigin[1] - coordinate[1]) / (resolution * tileSize);
var tileCol = Math.floor(fx);
var tileRow = Math.floor(fy);
var tileI= Math.floor((fx - tileCol) * tileSize);
var tileJ= Math.floor((fy - tileRow) * tileSize);
var matrixIds= tilegrid.getMatrixIds()[zoomIdx];
var matrixSet= source.getMatrixSet();

//Realizar la solicitud
Ext.Ajax.request({
    method:'GET',
    scope:this,
    
    url: layer.url,
    params:{
        SERVICE: 'WMTS',
        REQUEST: 'GetFeatureInfo',
        VERSION: source.getVersion(),
        LAYER: source.getLayer(),
        INFOFORMAT: infoFormat,
        STYLE: source.getStyle(),
        FORMAT: source.getFormat(),
        TileCol: tileCol,
        TileRow: tileRow,
        TileMatrix: matrixIds,
        TileMatrixSet: matrixSet,
        I: tileI,
        J: tileJ
    },
    
    callback:function(){...}
})`

We can use this code to write a function like WMS.getGetFeatureInfoUrl becase all we need is this parameters calculation.
I proved it on projections EPSG:4326 and EPSG:3857 and it's rules ok

**Comment by jbelien** [comment]
Absolutely awesome ! Thanks a lot @ghost ! Works like a charm 🎉 

Just a small typo :
```javascript
var fx = (this.coordinate[0] - tileOrigin[0]) / (resolution * tileSize);
```
should be :
```javascript
var fx = (coordinate[0] - tileOrigin[0]) / (resolution * tileSize);
```

**Comment by Bibi56** [comment]
And another remark: zoom must be integer so call

    // the algorithm works on integer zoom level so temporary 
    var zoom = view.getZoom();
    var iZoom = Math.round(zoom);
    if (zoom != iZoom) {
        view.setZoom(iZoom);
    }

before and

     if (zoom != iZoom) {
        view.setZoom(zoom);
    }

after. No redraw as the zoom is reset after.

**Pull request closed without merging**
