### PR TITLE
Build broken because of epsg.io problem

### PR DESCRIPTION
**Pull request by ahocevar**
Currently the build fails on master. This is an attempt to fix it.

cc @bartvde

### CODE REVIEW

**Comment by ahocevar** [comment]
Wrong fix.

**Comment by ahocevar** [comment]
https://github.com/klokantech/epsg.io/issues/103 is the problem, and it happens with the http://openlayers.org/en/v3.11.2/examples/wms-image-custom-proj.html example.

**Comment by klokan** [comment]
I am sorry for this issue. It should be fixed on the EPSG.io side now...

**Comment by klokan** [comment]
I have restarted the travis on master and it seems everything is now fine. This ticket can be closed probably.

**Comment by bartvde** [comment]
thanks @klokan

**Pull request closed without merging**
