### PR TITLE
Add a 'condition' option to ol.interaction.Modify

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
FYI, I need this new option to not add a vertex to a linestring when the right click is used:
```js
new ol.interaction.Modify({
  condition: ol.events.condition.mouseActionButton,
  ...
});
```

Thanks for any review

**Comment by ahocevar** [comment]
Wouldn't ol.events.condition.mouseActionButton be a better default than what we currently have? Also, the docs could be a bit more verbose, e.g. 'Condition that determines whether the event will be considered to add a vertex to the sketch.'.

**Comment by fredj** [comment]
> Wouldn't ol.events.condition.mouseActionButton be a better default than what we currently have?

I suspect that `ol.events.condition.mouseActionButton` will break the edition on touch devices (I will check)

> Also, the docs could be a bit more verbose, e.g. 'Condition that determines whether the event will be considered to add a vertex to the sketch.'.

Yes, good suggestion

**Comment by fredj** [comment]
That it: `ol.events.condition.mouseActionButton` always returns false on touch devices

**Comment by ahocevar** [comment]
Ok, thanks for investigating. So let's keep the default as it is.

**Comment by fredj** [comment]
I've updated the code and added a `ol.events.condition.primaryAction` condition that works with all the devices.

I want to do more tests on touch device

**Comment by fredj** [comment]
ready for review, thanks

**Comment by ahocevar** [comment]
Very nice. Please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
