### PR TITLE
Don't unlisten image twice when disposing an ol.ImageTile

### LINKED ISSUE #3325: tilecache > DEFAULT_TILE_CACHE_HIGH_WATER_MARK will show error
ol.js show Uncaught AssertionError: Assertion failed
when tilecahcer > ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK

default

i change ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK=20
http://fiddle.jshell.net/s2evvztt/
open fiddle and zoom in 
or use ol.js and load tilecache over 2048 (ol.DEFAULT_TILE_CACHE_HIGH_WATER_MARK = 2048;)

### PR DESCRIPTION
**Pull request by fredj**
Fixes #3325

### CODE REVIEW

**Comment by ahocevar** [comment]
Your change implies that `#disposeInternal()` might be called more than once, which makes me suspicious. Do we call it manually somewhere?

**Comment by fredj** [comment]
If the `ol.ImageTile` is disposed after the image has loaded, calling `this.unlistenImage_()` raises an error because of [this check](https://github.com/openlayers/ol3/blob/master/src/ol/imagetile.js#L167)

**Comment by elemoine** [comment]
I have the same patch in one of branches. I think it is correct. We dispose of tiles in `ol.TileCache#expireCache`, and the cache may contain tiles that are still in the idle state.

**Comment by ahocevar** [comment]
I still think that the underlying issue is somewhere else. So if you want to merge this, please add a BIG FAT TODO reminding us to investigate this properly.

**Comment by elemoine** [comment]
> I still think that the underlying issue is somewhere else.

I don't get it Andreas. `disposeInternal` calls `unlistenImage_`, which currently assumes that the image is in loading (or error) *state. That assumption is wrong, as the image may be in idle or loaded state.

**Comment by fredj** [comment]
`disposeInternal` can't be called more that once; `goog.Disposable#dispose` is [taking care of that](https://github.com/google/closure-library/blob/master/closure/goog/disposable/disposable.js#L176-L179).

The problem is that we may call `unlistenImage_` more that once: in `handleImageError_` / `handleImageLoad_` and then in `disposeInternal`

**Comment by ahocevar** [comment]
If the above reasoning is true, then the following - more straightforward - version of `disposeInternal` should fix the issue too:
```js
ol.ImageTile.prototype.disposeInternal = function() {
  if (this.state == ol.TileState.LOADING || this.state == ol.TileState.ERROR) {
    this.unlistenImage_();
  }
  goog.base(this, 'disposeInternal');
};
```
Am I right?

**Comment by elemoine** [comment]
> Am I right?

Not quite, because `handleImageError_` also calls `unlistenImage_`. So this should work:

```js
ol.ImageTile.prototype.disposeInternal = function() {
  if (this.state == ol.TileState.LOADING) {
    this.unlistenImage_();
  }
  goog.base(this, 'disposeInternal');
};
```

**Comment by ahocevar** [comment]
:+1:, the above would make me happy.

**Comment by fredj** [comment]
Eric's proposal is more explicit, will change

**Comment by elemoine** [comment]
Another option would be to change the `unlistenImage_` function itself.

Instead of

```js


/**
 * Discards event handlers which listen for load completion or errors.
 *
 * @private
 */
ol.ImageTile.prototype.unlistenImage_ = function() {
  goog.asserts.assert(!goog.isNull(this.imageListenerKeys_));
  goog.array.forEach(this.imageListenerKeys_, goog.events.unlistenByKey);
  this.imageListenerKeys_ = null;
};
```

it would be:

```js


/**
 * Discards event handlers which listen for load completion or errors.
 *
 * @private
 */
ol.ImageTile.prototype.unlistenImage_ = function() {
  if (!goog.isNull(this.imageListenerKeys_)) {
    goog.array.forEach(this.imageListenerKeys_, goog.events.unlistenByKey);
    this.imageListenerKeys_ = null;
  }
};
```

**Comment by ahocevar** [comment]
The previous proposal was more explicit. I always like to know the exact state from reading the code. Just checking whether there are still listeners registered does not look like an exact state to me.

**Comment by elemoine** [comment]
> The previous proposal was more explicit. I always like to know the exact state from reading the code. Just checking whether there are still listeners registered does not look like an exact state to me.

I see what you mean!

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
