### PR TITLE
Support multiple featureTpes in GML parser

### PR DESCRIPTION
**Pull request by bartvde**
Details and previous discussions are here: 
https://groups.google.com/forum/#!topic/ol3-dev/g0Ka2f96cD0
A simple WFS GetFeature response in GML3 from two layers with only osm_id as useful data:
http://pastebin.com/FfnfCeeK

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/5742071-gml-parser?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### CODE REVIEW

**Comment by ahocevar** [comment]
@bartvde, do you want to look into this again?

**Comment by bartvde** [comment]
yes I'll revisit this today @ahocevar 
thanks for the nudge, I had forgotten about this one actually ;-)

**Comment by bartvde** [comment]
@ahocevar I've added a commit that does what you suggested here https://github.com/openlayers/ol3/pull/2910#issuecomment-68199876

**Comment by ahocevar** [comment]
Looks good now. I only had one comment about better documentation. When addressed, please merge.

**Pull request merged**
