### PR TITLE
Extended class definition to note the source only read 'features'.

### PR DESCRIPTION
**Pull request by acanimal**
GeoJSON source is limited to read features from GeoJSON. This is not well explained in the docs and people can be confused.

### CODE REVIEW

**Comment by acanimal** [comment]
Solved some troubles with the doc format and gslint.

**Comment by tschaub** [comment]
I think it's a good idea to clarify documentation for the GeoJSON source and I appreciate your efforts @acanimal.  However, I think this still could use a bit of work before being merged.

I also think we should remove the `AUTHORS.md` file altogether.  It is not an accurate representation of the library contributors, and there are other means of generating a list of contributors if needed.

I don't have time to assist with the doc language right now, but wanted to at least leave my comments.

**Comment by elemoine** [comment]
I agree with @tschaub that this needs more work before being merged. For example, I don't think there's enough context for the reader to be able to make sense of the added text.

**Comment by acanimal** [comment]
Sorry, but I don't understand what do you want. It is a simply doc comment to avoid user confusions (I saw that "confusion" two times in the forum until now). 
It is the same case some time ago, where you update the the ol.format.GML and ol.format.WFS indicating the supported versions, due some question made in the forum. 

What are you suggesting? Rewrite it? More extensive explanation? Anyway, I think the API doc must be relatively concise and not much extensive.

Let me know and I'll do it.

**Comment by elemoine** [comment]
I think I'd first say that there are three ways to pass GeoJSON features to the source, through the `url/urls`, `text` and `object` constructor options, with possibly one short example for each. Then we can explain that the source expects GeoJSON features, and that it won't work if GeoJSON geometries are passed.

**Comment by acanimal** [comment]
Ok, I got it. I will review this and other sources.
Thanks.

**Comment by tschaub** [comment]
Another alternative is to discuss support for loading geometries or geometry collections.

**Comment by acanimal** [comment]
I vote for that, for GeoJSON formed by geometries load them and create the
corresponding features.
Anyway, I think also enhance documentation is a main tasks.

Any objection if I close this ticket and create a new one to implement
reading geometries?

Thanks.

**Comment by acanimal** [comment]
I think it must return a feature per geometry. I'm thinking, for example,
on reading a set of point heometriea. I would like each point was a
different feature, to style them different, and not a feature with many
point geometries.

|----------------------------------------------------------------
| The book of OpenLayers 3 - http://kcy.me/x29y
| OpenLayers Cookbook: http://kcy.me/ar2b
| Blog: http://www.acuriousanimal.com/blog
| Twitter: @acanimal
|----------------------------------------------------------------

**Comment by oobrien** [comment]
@acanimal Came across this, as I was looking for my ol.interaction.DragAndDrop to handle geometry-only JSONs, e.g. https://mapit.mysociety.org/area/2247.geojson - is it worthwhile me raising a ticket to implement reading of geometries in ol.format.GeoJSON (wrapping each one in a feature) or is it by design that OL wouldn't allow these? Thanks.

**Pull request closed without merging**
