### PR TITLE
Update proj4 version to 2.3.6

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
https://github.com/proj4js/proj4js/pull/144 fixes this issue

**Comment by fredj** [comment]
https://github.com/openlayers/ol3/blob/master/examples_src/sphere-mollweide.html#L9 needs to be updated

**Comment by ahocevar** [comment]
> https://github.com/openlayers/ol3/blob/master/examples_src/sphere-mollweide.html#L9 needs to be updated
@fredj That resource is already available, so you may want to cherry-pick 6f761fda3397761d0b8cce185a864f713824fa12 and then merge.

**Comment by fredj** [comment]
@ahocevar thanks for the proj4 fixup !

**Pull request merged**
