### PR TITLE
Bugfix: "Cannot read property 'firstElementChild' of null" (WFS)

### PR DESCRIPTION
**Pull request by brianreavis**
Occurs when the WFS FeatureCollection is empty.

### CODE REVIEW

**Comment by bartvde** [comment]
hey @brianreavis thanks for this, can you please add a testcase and format the code according to the guidelines, e.g. always ```{``` for if else. Also a code block is duplicated in your PR:

```
node = node.firstElementChild;
+  if (!goog.isDefAndNotNull(node)) return null;
```

**Comment by elemoine** [comment]
Too bad this is not enforced by the linter. Maybe there is an option we can pass to jshint.

**Comment by brianreavis** [comment]
@bartvde Yeah, I can add in the brackets. The code block is intentionally duplicated:
```js
// original line:
node = node.firstElementChild.firstElementChild;

// expanded form:
node = node.firstElementChild;
node = node.firstElementChild;
```

**Comment by bartvde** [comment]
ah okay I'd use ``||`` in that case (and a single if statement) for more code clarity

**Comment by bartvde** [comment]
or protect the for loop with:

```
if (goog.isDefAndNotNull(node.firstElementChild) && goog.isDefAndNotNull(node.firstElementChild.firstElementChild)) {
```

**Comment by brianreavis** [comment]
@bartvde @elemoine Okay, this should be good to go now

**Comment by bartvde** [comment]
thanks @brianreavis last step would be to clean up the git history with a git rebase, are you familiar with that?

**Comment by brianreavis** [comment]
Done. Does OL have any plans on relaxing the style? The strictness (line length in particular) is making code readability and contribution a mess.

**Comment by bartvde** [comment]
@brianreavis have you submitted a CLA already? https://github.com/openlayers/ol3/blob/master/CONTRIBUTING.md#contributor-license-agreement

**Comment by brianreavis** [comment]
Done...

**Comment by bartvde** [comment]
thanks for your contribution and patience @brianreavis

**Comment by elemoine** [comment]
> Done. Does OL have any plans on relaxing the style?

I'd say that we're pretty happy with what we use :-)

**Pull request merged**
