### PR TITLE
Add /examples/index.js to .gitignore

### PR DESCRIPTION
**Pull request by fredj**
The file is created by `tasks/build-examples.js`

### CODE REVIEW

**Comment by ahocevar** [comment]
+1

**Comment by elemoine** [comment]
Strange. I don't think tasks should create files inside the `examples` dir.

**Comment by tschaub** [comment]
> The file is created by tasks/build-examples.js

With #3558, the `build-examples.js` task only generates files in the `build/examples` directory.

**Comment by tschaub** [comment]
> Strange. I don't think tasks should create files inside the examples dir.

#3598

`git clean -f`

**Comment by probins** [comment]
thanks for that. I was just about to investigate why examples-list was in there. `git clean` removes it

**Pull request merged**
