### PR TITLE
Take the pixelRatio into account when computing the gutter

### LINKED ISSUE #5272: Layer displaced using pixelRatio and gutter at same time
Hi, I have prepared this fiddle: http://jsfiddle.net/xe2Lwm6o/25/

As you see, in script I add two layers, one with gutter=0 and another one with gutter=100.

The problem is the layer with gutter=100 is displaced (don't pay attention to labels, only state borders).

Changing the line "pixelRatio: 2" to "pixelRatio: 1" fixes the issue.

I have tried to examine Openlayers source code to try to find the problem, with no luck.

My hypothesis is that somewhere, multiplying by pixelRatio might be missing?

### PR DESCRIPTION
**Pull request by fredj**
Fixes #5272

### CODE REVIEW

**Comment by ahocevar** [comment]
An additional test that verifies the correct gutter size for a tile of known size and pixel ratio would be great.

**Comment by agustincaballero** [comment]
Hi, I've tested your modifications with this conditions:
Tile size: 350
Pixelratio: 2.5
gutter: 150

I get a request to mapserver with this dimensions:
&WIDTH=1625&HEIGHT=1625

(350+150*2)*2.5 = 1625

This means it is working perfectly!!! Thanks a lot

**Comment by ahocevar** [comment]
Actually I was hoping for a unit test.

**Comment by agustincaballero** [comment]
Sorry, this is the first issue I post on github. 
Of course, I am aware of the concept of unit test, but can you extend what you mean by "unit test" in this context? I will be pleased to make any test required.

**Comment by ahocevar** [comment]
@agustincaballero My comment was addressed to @fredj, because he created the pull request.

**Comment by fredj** [comment]
I've planned to add unit tests (probably next week)

**Comment by fredj** [comment]
Rendering tests added, thanks for any review (ping @ahocevar )

**Comment by ahocevar** [comment]
Thanks @fredj. Looks great, please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
