### PR TITLE
Adding missing provide for SelectFilterFunction

### PR DESCRIPTION
**Pull request by pgiraud**
Please review.

### CODE REVIEW

**Comment by pgiraud** [comment]
This breaks application builds with closure complaining with the following error:
```
node_modules/openlayers/externs/olx.js:2606: ERROR - Bad type annotation. Unknown type ol.interaction.SelectFilterFunction
```

**Comment by elemoine** [comment]
Good catch. Please review.

**Comment by pgiraud** [comment]
I suppose you meant "please merge". Have you had enough sleep? :-p

**Comment by elemoine** [comment]
I was following a discussion at the same time.

**Pull request merged**
