### PR TITLE
Fix canvas replay which broke with 31a68e2

### PR DESCRIPTION
**Pull request by ahocevar**
See https://github.com/openlayers/ol3/pull/4192#commitcomment-13582218

### CODE REVIEW

**Comment by marcjansen** [comment]
Nice catch, Andreas. Thanks for fixing this. Please merge.

**Comment by tschaub** [comment]
For anybody else reading along at home and looking for something to do, we could use a test that renders labels (using the Canvas renderer).

**Comment by marcjansen** [comment]
A visual test, or not?

**Comment by tschaub** [comment]
> A visual test, or not?

Even basic unit tests would let us refactor with impunity.  I know there was discussion about this ad nauseum in Schladming, but the alternative is that we let our users discover regressions.

**Pull request merged**
