### PR TITLE
Do not clip canvas for vector layers when wrapping the world

### LINKED ISSUE #3705: Vector layer "wrapX" option clip rendering of polygons over 180° or -180°
For :
- polygon over -180° (or 180°), 
- the "wrapX" option of vectorLayer to true
- canvas rendering

Polygon rendering is clip in [-180°, 180]. This works well with wrapX option to false (but I like this option...)

### PR DESCRIPTION
**Pull request by ahocevar**
Maybe an alternative to #3794, which does not have the [mentioned issues](https://github.com/openlayers/ol3/pull/3794#issuecomment-111882987).

cc @jcarbou

Fixes #3705.

### CODE REVIEW

**Comment by jcarbou** [comment]
I try this solution but it don't fix all use cases. Here some screenshots for polygon below :

```javascript
new ol.Feature(new ol.geom.Polygon([[
	[14356899.274664743,4296331.475114204],[15491836.270643039,6018304.848322656],[17800846.021081645,6957563.051890902],[19288004.843398035,7701142.463049095],
	 [22379729.76347684,7544599.429121055],[24688739.513915446,6801020.01796286],[25823676.509893745,5313861.19564647],[26606391.679533947,4609417.542970287],
	 [27036885.022836063,3161394.479135908],[25941083.785339773,2535222.3434237447],[24062567.378203284,3552752.063956011],[22027507.93713875,3474480.546991989],
	 [19679362.428218137,4531146.0260062665],[17683438.745635614,4061516.9242221434],[15491836.270643039,3865838.131812092],[14356899.274664743,4296331.475114204]
]]))
```

Current ol3 master sources with clip commented (Pull request #3806 TBC) :
image

Pull request #3794 :
image

An other use case is "large polygon" (see my previous posts in #3794).

Validating that if found a new use case who doesn't work for this pull request #3806 and mine #3794. Zooming a polygon over dateline but with the frameStateExtent that does'nt cross date line. I fix it  and pull changes on #3794. See below this use case fixed (same example  polygon):

image

**Comment by ahocevar** [comment]
Sorry @jcarbou, from your description above it is not clear to me what this pull request does not solve that #3794 does. Can you please try to rephrase?

**Comment by Jebjum** [comment]
@ahocevar I think what @jcarbou might have been pointing out is that the polygon will appear differently depending on what points appear first in the sequence. For example create a box with the four points:

[160, 20], [-160, 20], [-160, -20], [160, -20] - for me the "left half" is hidden/cut off at the dateline

[-160, 20], [-160, -20], [160, -20], [160,20] - for me, this box appears as two reflected triangles across the dateline

**Comment by jcarbou** [comment]
Sorry my English isn't my main quality... and I'm not a Github master. 

I misunderstood the pull request #3806. I don't see the tab "File changed" (I'm not pround of this point). So my previous post is irrelevant.

I think your pull request if simplier but It don't  slove 2 use cases : 

Test Case :

```javascript
new ol.Feature(new ol.geom.Polygon([[
	[14356899.274664743,4296331.475114204],[15491836.270643039,6018304.848322656],[17800846.021081645,6957563.051890902],[19288004.843398035,7701142.463049095],
	 [22379729.76347684,7544599.429121055],[24688739.513915446,6801020.01796286],[25823676.509893745,5313861.19564647],[26606391.679533947,4609417.542970287],
	 [27036885.022836063,3161394.479135908],[25941083.785339773,2535222.3434237447],[24062567.378203284,3552752.063956011],[22027507.93713875,3474480.546991989],
	 [19679362.428218137,4531146.0260062665],[17683438.745635614,4061516.9242221434],[15491836.270643039,3865838.131812092],[14356899.274664743,4296331.475114204]
]]))
```

1) Zoom on polygon that cross date line with a extent (view extent) who don't cross date line => polygon disapear

Wolrd zoom... perfect !
image

Now zoom on the right of this polygon (California & Mexico)  => The polygon disapear

image

Reason : the prepareFrame function find the polygon, but ol.render.canvas.Replay.prototype.appendFlatCoordinates exclude all points (Try do draw it "on the right and hidden part of the world", that is good for other use cases).

The pull request #3794 fix it using method  ol.render.canvas.Replay.prototype.drawFlatCoordinatesForViewExtent that test this situation for each geometry (polygon, line) and generate a translated geometry.

2) The same polygon draw 2 time on a extent with width smaller than wold

OK this sentence isn't very clear. A screenshot, with the same test case polygon, of pull request #3806 result :

image

And another of the pull request #3794 :

image

Reason : the prepareFrame function find the polygon and ol.render.canvas.Replay.prototype.appendFlatCoordinates draw all point.. but  just one polygon.

The pull request #3794 fix it using too the method  ol.render.canvas.Replay.prototype.drawFlatCoordinatesForViewExtent that test this situation for each geometry (polygon, line) and generate a duplicated and translated geometry.

I think a complete solution can be mix of these 2 pull requests.

2 other points (detail / performances) :

A) If wrapX is set to true the user can wrap (left or right) and after zoom to a extent lower than worlwidth. In most cases this zoom isn't in projectionextent and optimisations of this projectionextent aren't apply (only one replay group, don't search features in projection extent but oly in view extent). A idea can be optimise that if 
- viewextent width is lower than world
- viewextent don't intersect projectionExtent
- if projectionExtent contains unwrapped viewExtent (viewExtent modulo worlWidth) 
=> use default and optimise way(on replayGroup and selection of feature in unwrapped viewExtent)

B) The ol.renderer.canvas.VectorLayer.prototype.composeFrame method , if wrapX to true and theprojectionExtent don't contains viewExtent, generate to much replayGroup in some case. Example : The view extent is -1080°,-1060° => 4 ReplayGroup created but only one is needed. I propose a modification of this code in the pull request #3794  to optimise that (It's just optimisation)

**Comment by ahocevar** [comment]
Thanks for the good explanations. I understand now what the remaining issue is. I will update #3806 accordingly.

**Comment by ahocevar** [comment]
@jcarbou I am closing this pull request. Instead, I'll continue to review #3794. Maybe I can come up with some suggestions for simplification, and maybe you can think of simplifications too now that you saw my insufficient solution.

**Comment by ahocevar** [comment]
Actually I'm reopening this, because it seems that #3794 has the same issues.

**Comment by ahocevar** [comment]
Updated pull request to make the replay extent wide enough to cover a coordinate range of -540° to +540°, like in @jcarbou's pull request #3794.

**Comment by ahocevar** [comment]
Anyone able to review this so it can get into the 3.7 release?

**Comment by bartvde** [comment]
LGTM @ahocevar

**Pull request merged**
