### PR TITLE
Remove unused functions

### PR DESCRIPTION
**Pull request by fredj**
Remove some unused and non api functions

### CODE REVIEW

**Comment by ahocevar** [comment]
Out of curiousity, how do you identify these?

**Comment by bartvde** [comment]
Right was wondering the same, is there a compiler option or something?

**Comment by ahocevar** [comment]
Also, do we have unused API functions? Just asking because you mentioned "non api functions".

**Comment by fredj** [comment]
> Out of curiousity, how do you identify these?

I just looked at `ol.array`, `ol.coordinate`, `ol.size` and `ol.TileRange`and `git grep`ed the (non api) functions name.

**Comment by fredj** [comment]
> Also, do we have unused API functions? Just asking because you mentioned "non api functions".

Yes probably but I didn't check

**Comment by fredj** [comment]
@ahocevar, @bartvde is it good to merge?

**Comment by ahocevar** [comment]
Thanks @fredj, great work!

**Comment by fredj** [comment]
Thanks for the review

**Comment by ischas** [comment]
> Also, do we have unused API functions? Just asking because you mentioned "non api functions".

Out of curiosity, how will you identify these since you don't know which API functions are used by developers using OL3?

**Comment by bartvde** [comment]
Indeed @ischas , we can only check which API functions are not used by the library itself, but still they can be used by applications. So no need to look for those IMHO.

**Pull request merged**
