### PR TITLE
ol.format.TWKB

### PR DESCRIPTION
**Pull request by bjornharrtell**
With the TWKB format getting ready for production use with PostGIS 2.2 I think it would be nice to support it out of the box in a future OpenLayers release. This is a naive implementation using GeoJSON conversion. Future work could parse directly to OpenLayers features.

### CODE REVIEW

**Comment by marcjansen** [comment]
We once already had a PR for TWKB

**Comment by bjornharrtell** [comment]
Yes but that effort was abandoned and later removed for more or less good reasons. It was a fairly complex implementation done directly as a part of ol3 where as this PR suggest to use the twkb library as a dependency.

For reference the previous attempt was #1615, #1717, #1718.

**Comment by sweco-sebhar** [comment]
I've come to the conclusion that custom formats is better plugged in as a custom loader for Vector sources. #3833 proposes to add a similar option for TileVector sources.

Implementing a format as a part of the OpenLayers code base does not makes good sense until it is mainstream and popular.

**Comment by fredj** [comment]
> This PR can be closed.

**Pull request closed without merging**
