### PR TITLE
Support OGC WKT proj4 def.units and def.to_meter

### PR DESCRIPTION
**Pull request by tbarsballe**
Fix for https://github.com/openlayers/ol3/issues/4233
Depends on https://github.com/proj4js/proj4js/pull/157 (Will not pass tests without this change).

### CODE REVIEW

**Comment by tbarsballe** [comment]
Updated to be compatible with different DATUMs (don't store unit name as key value, just use conversion factor)

**Comment by ahocevar** [comment]
Thanks, this change looks good. Only thing is we have a very picky linter, which does not like the formatting of your changes:
```
Running gjslint...
----- FILE  :  /home/travis/build/openlayers/ol3/src/ol/proj/proj.js -----
Line 157, E:0110: Line too long (84 characters).
----- FILE  :  /home/travis/build/openlayers/ol3/test/spec/ol/proj/proj.test.js -----
Line 498, E:0110: Line too long (82 characters).
Line 498, E:0002: Missing space before "+"
Line 499, E:0110: Line too long (81 characters).
Line 499, E:0002: Missing space before "+"
Line 500, E:0002: Missing space before "+"
Line 501, E:0002: Missing space before "+"
Line 504, E:0110: Line too long (84 characters).
Line 504, E:0002: Missing space before "+"
Line 505, E:0002: Missing space before "+"
Line 506, E:0002: Missing space before "+"
Line 534, E:0002: Missing space before "*"
Line 534, E:0002: Missing space after "*"
Line 536, E:0002: Missing space before "*"
Line 536, E:0002: Missing space after "*"
Line 536, E:0110: Line too long (82 characters).
Found 16 errors, including 0 new errors, in 2 files (484 files OK).
```
This is why the CI tests fail for this pull request. Are you able to update it? If not let me know, and I'll do it before I merge it.

**Comment by tbarsballe** [comment]
I can update it.

**Comment by ahocevar** [comment]
Cool, thanks. For the paper work, since this appears to be your first contribution, can you also sign a [CLA](https://github.com/openlayers/cla) please?

**Comment by tbarsballe** [comment]
Linting fixed, ICLA signed.
Build is now failing due to https://github.com/proj4js/proj4js/pull/157

**Comment by ahocevar** [comment]
I just published proj4.js v2.3.12. If you set that version in package.json, the build should pass again.

**Comment by tbarsballe** [comment]
Updated package.json

**Comment by ahocevar** [comment]
Nice, thanks for this great first-time contribution @tbarsballe.

**Comment by marcjansen** [comment]
Agreed, a very nice contribution, thanks!

**Pull request merged**
