### PR TITLE
fixing comment

### PR DESCRIPTION
**Pull request by jachym**
This line does not work with closure compiler (in "very strict" mode).

IMHO this will fix it

### CODE REVIEW

**Comment by elemoine** [comment]
How do you activate the "very strict mode". I'd like to reproduce the issue.

**Comment by jachym** [comment]
java -client -XX:+TieredCompilation -jar bower_components/closure-compiler/compiler.jar --jscomp_error accessControls --jscomp_error ambiguousFunctionDecl --jscomp_error checkDebuggerStatement --jscomp_error checkRegExp --jscomp_error checkTypes --jscomp_error checkVars --jscomp_error const --jscomp_error constantProperty --jscomp_error deprecated --jscomp_error duplicate --jscomp_error duplicateMessage --jscomp_error es5Strict --jscomp_error externsValidation --jscomp_error fileoverviewTags --jscomp_error globalThis --jscomp_error internetExplorerChecks --jscomp_error invalidCasts --jscomp_error missingProperties --jscomp_error strictModuleDepCheck --jscomp_error typeInvalidation --jscomp_error undefinedNames --jscomp_error undefinedVars --jscomp_error unknownDefines --jscomp_error uselessCode --jscomp_error visibility --language_in ECMASCRIPT5_STRICT --jscomp_off=externsValidation --compilation_level=ADVANCED --js ....


or in other words:

    command = [variables.JAVA,
               '-client',
               '-XX:+TieredCompilation',
               '-jar',
               variables.CLOSURE_JAR,
               '--jscomp_error', 'accessControls',
               '--jscomp_error', 'ambiguousFunctionDecl',
               '--jscomp_error', 'checkDebuggerStatement',
               '--jscomp_error', 'checkRegExp',
               '--jscomp_error', 'checkTypes',
               '--jscomp_error', 'checkVars',
               '--jscomp_error', 'const',
               '--jscomp_error', 'constantProperty',
               '--jscomp_error', 'deprecated',
               '--jscomp_error', 'duplicate',
               '--jscomp_error', 'duplicateMessage',
               '--jscomp_error', 'es5Strict',
               '--jscomp_error', 'externsValidation',
               '--jscomp_error', 'fileoverviewTags',
               '--jscomp_error', 'globalThis',
               '--jscomp_error', 'internetExplorerChecks',
               '--jscomp_error', 'invalidCasts',
               '--jscomp_error', 'missingProperties',
               #'--jscomp_warning', 'nonStandardJsDocs',
               '--jscomp_error', 'strictModuleDepCheck',
               '--jscomp_error', 'typeInvalidation',
               '--jscomp_error', 'undefinedNames',
               '--jscomp_error', 'undefinedVars',
               '--jscomp_error', 'unknownDefines',
               '--jscomp_error', 'uselessCode',
               '--jscomp_error', 'visibility',
               '--language_in', 'ECMASCRIPT5_STRICT',
               '--jscomp_off=externsValidation',
               '--compilation_level=%s' % level]


produces:


    bower_components/openlayers3/src/ol/format/topojsonformat.js:400: ERROR - Bad type annotation. expected closing }
     * @type {Object.<string, function(TopoJSONGeometry, Array, ...[Array]): ol.geom.Geometry>}
                                                               ^
    bower_components/openlayers3/src/ol/format/topojsonformat.js:400: ERROR - Bad type annotation.   type not recognized due to syntax error
     * @type {Object.<string, function(TopoJSONGeometry, Array, ...[Array]): ol.geom.Geometry>}
                                                               ^

    2 error(s), 0 warning(s)

**Comment by elemoine** [comment]
I cannot reproduce the problem in ol3. What compiler version do you have? I have v20141120 here.

**Comment by fredj** [comment]
This comment was recently fixed, see https://github.com/openlayers/ol3/pull/3199

**Comment by elemoine** [comment]
@jachym, based on @fredj's comment, it looks like you are not using the latest master.

**Comment by jachym** [comment]
@elemoine: no :-( I'm on v3.2.1 :-/

**Pull request closed without merging**
