### PR TITLE
Add ol.source.ImageArcGISRest

### PR DESCRIPTION
**Pull request by llambanna**
ol.source.ImageArcGISRest is added so a single image can be retrieved which is required when labelling is applied to the underlying map service.
it's similar to ol.source.ImageWMS

usage:

```javascript

var layer = new ol.layer.Image({
  source: new ol.source.ImageArcGISRest({
    url: "http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StateCityHighway_USA/MapServer",
  })
});


```

### CODE REVIEW

**Comment by llambanna** [comment]
so is this needed or not? i'm using it, so i thought it would be of use to the main project.

is there some other hoops i need to jump through before it can be added? please tell me so i can do what needs to be done.

**Comment by bartvde** [comment]
This is not a clean PR so we cannot merge it. Look at the history.

**Comment by bartvde** [comment]
seems to be superseded by #3859

**Comment by llambanna** [comment]
thanks for having a look, but no, it's not superseded by #3859. 
this is something entirely different - it's a non-tiled ArcGIS rest source, which is useful when dealing with labelled map services.

#3859 is adding an additional option into TileArcGISRest source of crossOrigin.

i'll open another pull request when i've got everything working properly on my desktop.

**Comment by llambanna** [comment]
i've rebased my change into a single commit.

**Comment by bartvde** [comment]
something is still wrong, your PR included a commit which it shouldn't

**Comment by llambanna** [comment]
I don't know how that got in there. I'll close this one and start another one.

**Comment by llambanna** [comment]
closing as replaced by #3880

**Pull request closed without merging**
