### PR TITLE
Update tutorials

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
Related to https://github.com/openlayers/ol3/issues/5005

**Comment by gberaudo** [comment]
// cc @ahocevar

**Comment by ahocevar** [comment]
Looks good, thanks @gberaudo.

**Comment by gberaudo** [comment]
Thanks for the quick review and merge @ahocevar.

**Comment by probins** [comment]
what effect does removing "goog.dom.ASSUME_STANDARDS_MODE=true" have?

**Comment by fredj** [comment]
See https://github.com/google/closure-library/blob/master/closure/goog/dom/dom.js#L59-L63

**Comment by probins** [comment]
yes, but that doesn't explain what effect removing has. @gberaudo calls it 'disturbing' in the commit msg; if it's disturbing, why's it in the config/*json files?

**Comment by gberaudo** [comment]
It is disturbing for a tutorial, where we should focus on the most important points.
This define is a micro optimization, which is still usind in the last example of the closure.md tutorial.

**Pull request merged**
