### PR TITLE
Use ratio when calculating ImageWMS width and height

### LINKED ISSUE #4403: WMS layer shift in >= 3.11.0
When adding WMS layer according to example at http://openlayers.org/en/v3.10.1/examples/wms-image.html with OpenLayer 3.11, the WMS is shifted. 

3.10. Works well

For testing, see 

http://jsfiddle.net/jachymc/cw30xa9z/

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #4403.

### CODE REVIEW

**Comment by tschaub** [comment]
This looks like it corrects the single image WMS example (on a non-retina device at least).  It would be great to get in a regression test for this, but I think a patch release is more urgent.

Thanks for the fix.  Please merge.

**Comment by ahocevar** [comment]
I was planning to add tests for this anyway, but decided to look into #4405, the other serious regression, first.

**Comment by ahocevar** [comment]
BTW, fixed for Retina displays too.

**Comment by tschaub** [comment]
Thanks @ahocevar.

The downside of using a branch as the base for patches is that the continuous-integration/travis-ci/pr job doesn't run.  I just pushed a change to our Travis config to make the continuous-integration/travis/push job run for branches named like `/^v.*\.x$/`.  Not as convenient since we don't get the commit status updated on a PR.  But we can check the build status periodically (e.g. https://travis-ci.org/openlayers/ol3/builds/90780614).

The alternative is to commit patches to master and then cherry-pick.  But that brings potential for conflicts.

**Pull request merged**
