### PR TITLE
Fix source.UrlTile URL expansion

### PR DESCRIPTION
**Pull request by gberaudo**
Fix the issue and add a test for spotting regressions.

### CODE REVIEW

**Comment by gberaudo** [comment]
Closes #4765 (replace).
Fixes #4764.

**Comment by ahocevar** [comment]
Thanks @gberaudo.

**Comment by ahocevar** [comment]
Since I'm involved here as commit author, I'd appreciate a review from someone from @openlayers/core. Thanks.

**Comment by tschaub** [comment]
Looks great.  Thanks for the fix and the tests.  Please merge.

**Comment by gberaudo** [comment]
Thanks for the quick review and merging.

**Pull request merged**
