### PR TITLE
Make olx.view.FitOptions.padding optional

### PR DESCRIPTION
**Pull request by gberaudo**
Make it consistent with other attributes.

### CODE REVIEW

**Comment by tsauerwein** [comment]
Small typo in the commit message, otherwise that looks good! Thanks for fixing!

**Comment by gberaudo** [comment]
Thanks for the review @tsauerwein. I fixed the commit message. Please merge if it looks good to you.

**Comment by gberaudo** [comment]
Great, even increaded coverage!

**Comment by tsauerwein** [comment]
Thanks!

No idea why the coverage has changed..

**Pull request merged**
