### PR TITLE
Remove pystache dependency

### PR DESCRIPTION
**Pull request by fredj**
And use the mustache node module instead.

### CODE REVIEW

**Comment by elemoine** [comment]
Could you please explain the change to bin/pyglslunit.py?

**Comment by fredj** [comment]
`bin/pyglslunit.py` now returns a json string used by [mustache](https://www.npmjs.com/package/mustache) to generate the final js file.

**Comment by elemoine** [comment]
> bin/pyglslunit.py now returns a json string used by mustache to generate the final js file.

I see.

Can you also confirm that the `mustache` node module won't be downloaded when doing `npm install openlayers`? I guess having `mustache` be a dev dependency will prevent that.

**Comment by fredj** [comment]
> Can you also confirm that the `mustache` node module won't be downloaded when doing `npm install openlayers`? I guess having `mustache` be a dev dependency will prevent that. 

`mustache` is not download with:
```
npm install git://github.com/fredj/ol3#rm_pystache

```

**Comment by elemoine** [comment]
Ok, thanks for testing. Feel free to merge this.

**Comment by fredj** [comment]
thanks for the review

**Pull request merged**
