### PR TITLE
Rework build-examples.js task

### PR DESCRIPTION
**Pull request by tschaub**
This is a minor reworking of the `build-examples.js` task.  The changes here avoid reading all CSS and JS files twice, refactor the plugin a bit, and change things to use YAML lists for resources instead of comma delimited strings.

I'm in the process of changing the tasks related to building examples, I'd like to merge in this minor change to the task before going further.

### CODE REVIEW

**Comment by elemoine** [comment]
Very nice. Please merge when Travis is happy.

**Comment by tschaub** [comment]
As mentioned in 825c6b0, this change also makes it so example HTML files are treated as HTML.  If we want to have example markdown files instead (for some examples), we can just use the [`metalsmith-markdown` plugin](https://www.npmjs.com/package/metalsmith-markdown) before the `augmentExamples` plugin.  This simplifies the role of the `augmentExamples` plugin a bit.  I scanned the example HTML files looking for markdown in the content and didn't see any.  If there is some we can add the other plugin or change it to markup.  Markdown in the doc metadata is still supported.

**Comment by elemoine** [comment]
Thanks for the explanations. Please merge when Travis is happy.

**Comment by elemoine** [comment]
> I'm in the process of changing the tasks related to building ps, I'd like to merge in this minor change to the task before going further.

I realize that both `tasks/parse-examples.js` and `bin/exampleparser.py` generate `examples/example-list.js` (https://github.com/openlayers/ol3/pull/1630). The former is run at `npm install` time, while the second is run when the `examples` target of `build.py` is run.

So we have `build.py` targets and node tasks, with some duplication. It looks like we have some mess we need to clean… But I guess we should first agree on objectives.

It sounds to me that, when the node tasks were added, one of the objectives was to create a (lighter) parallel build system aimed to eventually replace the pake-based build system. But pake and `build.py` are still there, and they provide things that the node tasks do not provide.

Here are questions I would have:

* Do we still want to get rid of pake and `build.py`?
* Can we do with just node, npm and node tasks?
* Or do we also need/want a make-like system like pake, grunt or gulp?

Opinions?

**Comment by tschaub** [comment]
> I realize that both tasks/parse-examples.js and bin/exampleparser.py generate examples/example-list.js (#1630). The former is run at npm install time, while the second is run when the examples target of build.py is run.

This has changed with #3542.  `bin/exampleparser.py` and `tasks/parse-examples.js` are gone.

**Pull request merged**
