### PR TITLE
Use winding number algorithm for linearRingContainsXY

### PR DESCRIPTION
**Pull request by bjornharrtell**
Found out about this algorithm in another project and it seems nice so I propose to replace the old one.

### CODE REVIEW

**Comment by bartvanandel** [comment]
Why? Is it faster?

**Comment by bjornharrtell** [comment]
Is is slightly faster in some cases and as fast in all cases according to the author. It can also handle non simple polygons.

Sources:
https://en.wikipedia.org/wiki/Point_in_polygon
http://geomalgorithms.com/a03-_inclusion.html

**Comment by bartvanandel** [comment]
Interesting! I think your latter point is even more important: for polygons with self-intersections the currently used Crossing Number algorithm will give wrong answers in the parts where the polygon overlaps with itself an even number of times. The Winding Number algorithm does not have this problem.

**Comment by marcjansen** [comment]
hey @bjornharrtell,  any chance of adding tests for   non simple polygons?

**Comment by bjornharrtell** [comment]
You got it @marcjansen. :)

**Comment by marcjansen** [comment]
Thanks for adding the tests, @bjornharrtell. Is it just me or are these tests passing with or without changing the algorithm?

I still think this looks good, but just want to confirm.

**Comment by bjornharrtell** [comment]
The test `returns true for point inside an overlap of a non-simple polygon` should fail with the existing algorithm. I just cherry picked d34409846fc47d9499a1c52a98c28a4968c011d1 on master and it fails as expected. Though I noticed that I had forgot to change the description of the test cases, I've fixed that now.

**Comment by marcjansen** [comment]
Thanks for this @bjornharrtell.

**Pull request merged**
