### PR TITLE
Quick-fix running tests with PhantomJS

### LINKED ISSUE #4384: Build fails on Travis
The tests don't pass on Travis. Here are the errors:

```
  1807 passing (16s)

  7 failing

  1) ol.source.Raster constructor defaults to "pixel" operation:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)

  

  2) ol.source.Raster constructor allows operation type to be set to "image":

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)

  

  3) ol.source.Raster #setOperation() allows operation to be set:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)

  

  4) ol.source.Raster #setOperation() updates and re-runs the operation:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)

  

  5) ol.source.Raster beforeoperations allows data to be set for the operation:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)

  

  6) ol.source.Raster afteroperations gets called after operations are run:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)

  

  7) ol.source.Raster afteroperations receives data set by the operation:

     Uncaught TypeError: 'undefined' is not an object (evaluating 'buffers[0].byteLength') (http://127.0.0.1:3001/test/loader.js/home/travis/build/openlayers/ol3/build/ol.ext/pixelworks.js:37)
```

Does anyone know what the problem is?

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #4384.

I'll come up with a better (and more persistent) fix when I look into #4377, which is related.

### CODE REVIEW

**Comment by bartvde** [comment]
LGTM

**Comment by ahocevar** [comment]
@bartvde Let's see if Travis thinks so too ;-)

**Comment by bartvde** [comment]
Travis agrees ;-)

**Comment by elemoine** [comment]
Thanks for this temporary fix @ahocevar! Please merge.

**Comment by marcjansen** [comment]
This should  be closed. Imho.

**Comment by marcjansen** [comment]
Sorry, nevermind

**Pull request merged**
