### PR TITLE
Remove unrequired requires

### PR DESCRIPTION
**Pull request by probins**
Whilst thinking some more about conversion to ES6 modules, I noticed that there's some inconsistency in the `goog.require`s. In map, for example, `ol.Coordinate`, `ol.Pixel`, `ol.PreRenderFunction` and `ol.PostRenderFunction` are not used in the code, but only for defining a type in the docs comments, so in module terms, there is no import. `ol.Coordinate` does not have a `goog.require`, whereas the other 3 do. As the compiler doesn't, er, require a require for these, ISTM it would simplify the conversion if these unneeded requires were removed. There are probably others around, and I'll submit other PRs if I spot them. The first baby step towards ES6 modules :smile:

### CODE REVIEW

**Comment by tschaub** [comment]
We have an unsolved problem for people who might want to use `manage_closure_dependencies`.  If the types are not in the dependency tree (i.e. not explicitly `goog.require()`'d), the Compiler will fail (see #4945).  So this is potentially exacerbating that problem.

Even in the ES6 modules world, we'll have to somehow depend on the appropriate `@typedef`s to pass code to the Compiler.  We could have a single `types.js` file to handle this (this would be prepended to a bundle before passing to the compiler).  But it may be nicer from a development standpoint to have types defined throughout the library and imported/required only where they are used.

Anybody else have thoughts on the subject?

Either way, I think this could be merged (though it increases the lurking `manage_closure_dependencies` issue).

**Comment by probins** [comment]
I don't know if it affects anything, but `manage_closure_dependencies` has now been deprecated, as of February release.

**Comment by fredj** [comment]
`manage_closure_dependencies` was renamed to `dependency_mode=LOOSE`.
see https://github.com/google/closure-compiler/blob/3ad2498/src/com/google/javascript/jscomp/CommandLineRunner.java#L449-L454

**Comment by gberaudo** [comment]
There are tricky cases with typedefs.

In https://github.com/gberaudo/ol3/commit/2ff8a1b7d8dd0246edf9113a22da8585a0c97779 the require was missing from `ol/source/source.js` but the type error occured in `ol/source/bingmapssource.js`.

With one file per type it is easy for a user to find a type, be it constructor, enum or typedef since the location of the file directly depend on the type name. With a single file the user needs to know about the typedefs file and then browse a huge file.

Would a single typedef file work with custom builds (restricted list of exports)? Do we need goog.requires?

I would name an eventual typedef file `typedefs` since constructors and enums are also types.

**Comment by probins** [comment]
> We could have a single types.js file to handle this (this would be prepended to a bundle before passing to the compiler)

if we had that, and it's documented that those creating custom builds should always include this file, then #4945 goes away, right?

**Comment by probins** [comment]
these unneeded requires are hard to spot, but it occurs to me that if we change to `goog.module` and the `var x = goog.require('x')` pattern, then these will be flagged as unused vars.

**Comment by gberaudo** [comment]
I experimented with using `goog.module` for typedefs but it was producing errors.
It seems more reasonable to keep `goog.provide` for typedefs since they bear no code, but are only instructions for the closure compiler.

**Comment by probins** [comment]
I'll close this, and include it in the PR for #5299

**Pull request closed without merging**
