### PR TITLE
Implement ol.renderer.Layer#forEachFeatureAtCoordinate

### PR DESCRIPTION
**Pull request by fredj**
And remove identical implementation in children classes.

### CODE REVIEW

**Comment by gberaudo** [comment]
Looks sensible to me.

**Comment by tschaub** [comment]
Looks good.  Please merge.

**Comment by elemoine** [comment]
For the record, that function was not on the base class for two reasons: (a) it should be a noop for tile layers, (b) it has a completely different implementation for vector layers.

Personally, I don't like adding a method to a base class that is completely overridden in child classes, because I find it confusing when reading the code, and because, if I don't use Image layers in my app, I don't want to pay for code I don't use.

**Comment by fredj** [comment]
I have not seen that the tile layers inherits from that base class ... will revert

**Pull request merged**
