### PR TITLE
Update canvastilelayerrenderer.js

### PR DESCRIPTION
**Pull request by bill-chadwick**
Fix for Issue 2314#
This fixes canvas tile rendering when tileSize changes with zoom (by using a tileSizes array with a TileGrid)

### CODE REVIEW

**Comment by bill-chadwick** [comment]
My first PR so I hope all is in order.

**Comment by elemoine** [comment]
I haven't yet looked into detail but I'm wondering if having the canvas size always be a multiple of the tile size is really necessary. With this patch we may resize the canvas each time the view resolution changes (because the tile grid uses different tile sizes for each zoom level). Just wondering at this point…

**Comment by bill-chadwick** [comment]
This issue is a bit of a blocker for using ol3 with the Ordnance Survey Openspace WMS (pseudo) in the UK.

This needs a TileGridlike this

var osTileGrid = new ol.tilegrid.TileGrid({
             tileSizes: [200, 200, 200, 200, 200, 200, 200, 200, 200, 250, 250],
             resolutions: [2500, 1000, 500, 200, 100, 50, 25, 10, 5, 2, 1],
             origin: [0, 0]});

I suspect that there are not that many source layers that use a change in tile size like this. 

If a layer uses a fixed tile size then the suggested patch will not trigger a resize on zoom/resolution change. As the code is currently broken for a layer with varying tile size, I would have thought the patch worth applying.

A performance upgrade where the canvas need not be a multiple of whole tiles in size could come later.

Bill

**Comment by tschaub** [comment]
Can you describe the broken behavior you are seeing?

I agree with you that applying the patch shouldn't have negative consequences, but I'd like to better understand what the problem is.

**Comment by tschaub** [comment]
I see #2314 now.

**Comment by tschaub** [comment]
Ok, I get it now.  The code assumes the canvas size is always a multiple of the tile size.  This assumption is not always met when the tile size changes.  I'm guessing the problem begins when the tile size changes (but the canvas size doesn't need to be updated) and `canvasTileRangeWidth` and `canvasTileRangeHeight` [become non-integer values](https://github.com/openlayers/ol3/blob/776ffa925fe1f3d53661ae49b27d66cd89411d8f/src/ol/renderer/canvas/canvastilelayerrenderer.js#L253-L254).

I would think that another solution would be to `Math.floor` the [range calculations](https://github.com/openlayers/ol3/blob/776ffa925fe1f3d53661ae49b27d66cd89411d8f/src/ol/renderer/canvas/canvastilelayerrenderer.js#L253-L254).  But I haven't tried any of this to confirm.

If the `Math.floor` solution works, it *might* mean a canvas resize could be avoided when tile sizes change.  But I don't think this is a significant performance concern (because it is infrequent).

So I'm in favor of merging this change.  @elemoine curious to hear more thoughts from you.

And it's hard not to point out that tests would be really helpful here.

**Comment by bill-chadwick** [comment]
Without the canvas being a multiple of the tile size an exception is thrown
for a non-integer array size later in the function. I will make a demo to
show the effects of that tonight.
Bill

**Comment by bill-chadwick** [comment]
I did not try the Math.floor or ciel approach as I was concerned that the
subsequent rendering might not complete the entire canvas.

**Comment by bill-chadwick** [comment]
Saving the rendered tile size in the class' state and checking at the next
render might read better in the code.

**Comment by tschaub** [comment]
> Saving the rendered tile size in the class' state and checking at the next
> render might read better in the code.

I agree this would make things easier to understand (and put us at less risk of regression when reworking this code).

**Comment by bill-chadwick** [comment]
I have changed the patch to use a state variable. The Travis build crashed with a SHA check error. I believe the build would pass if Travis had not crashed. Not sure how to re-trigger it without another commit.

**Comment by tschaub** [comment]
I created https://travis-ci.org/openlayers/ol3/builds/50114642.

**Comment by tschaub** [comment]
Thanks for the work on this @bill-chadwick.  I think this looks like the right solution.

It looks like we don't have a CLA on file for you.  Would you be able to submit one (ICLA if this work is on behalf of a corporation or CLA if an individual contribution)?  See the [CLA readme](https://github.com/openlayers/cla/blob/master/README.md) for details.

Finally, since the five commits in your branch are really attempts at the same thing, they should be squashed into one.  And we try to have meaningful commit messages, so you could reword the first commit message.  If you haven't rebased before, this looks like a decent guide: http://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

Basically, you would do this:

```
git rebase --interactive HEAD~5
```

In your editor, mark the first commit (fda54b31e728ebe0882fa92e4777683a04a062e1) as "reword" and mark the four subsequent commits with "squash."  When you save/close this interactive rebase file, the rebase will begin and you'll be prompted to reword the first commit message.  Something like "Track rendered tile size and resize canvas on change" makes sense to me.

After rewording the first commit, the rebase will squash the subsequent commits into the first, and you'll be done.  Now you have to force push to rewrite history on the remote.

```
git push --force origin master
```

(This assumes that your `origin` remote points to https://github.com/bill-chadwick/ol3.)

Typically, we create a branch based on master for submitting pull requests.  And in general you never want to force push to a shared development branch (like `master` or anything else where collaborators might be surprised by your force push).  But since you opened this pull request based on your master branch, you'll want to force push the new commit there.  When you do that, this pull request will be updated with the new commit.

Even if something goes awry during the rebase or force push, git rarely disposes of commit objects for good, so we can reconstruct things with your previous commits (fda54b31e728ebe0882fa92e4777683a04a062e1, cb0924e4f242198aa46b7ed0e105acac0a04cc85, 60d2eff78af5c06b9259d362c1cbacd769fccf01, 780709b52c12d218e55bfab5fef12baeed85c310, and 82ed150a50bfa0a1c1b57f11ebd78b50d1633f93).

I recognize this is a lot to tackle for a first time pull request.  Let me know if anything doesn't make sense.

**Comment by bill-chadwick** [comment]
Tim,

I have completed an individual CLA.

I have been working and testing on Windows. The ol3 build system is not too
good on Windows. *build lint, build test*, *build check* and *build ci* all
fail. I can lint an individual source file from the command line.
The committed changes were actually made using the GIT on line source
editor. I will have a go with your recipe above using Git for Windows.
Please be patient with me if I do not get it right first time.

Bill

**Comment by tschaub** [comment]
To avoid any more pain/suffering on your part, I've opened #3223 with a reworked version of the commits here.  Thanks for the CLA and the good work on this.  I'll close this in favor of the new pull request.

**Comment by bill-chadwick** [comment]
Many thanks !

**Pull request closed without merging**
