### PR TITLE
Update rbush to 2.0.1

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/openlayers/ol3/pull/5531

### CODE REVIEW

**Comment by ahocevar** [comment]
Looks good. Please merge.

**Comment by tsauerwein** [comment]
Thanks for the review

**Comment by bartvde** [comment]
this leads to 48 failing unit tests in Chrome and FF

**Comment by bartvde** [comment]
@tsauerwein I'm going to revert this so I can do the 3.17 release today. We can do more testing on this after that I guess?

**Comment by tsauerwein** [comment]
@bartvde Are you sure your local instance is updated correctly? The file `build/ol.ext/rbush.js` has changed. For me the tests pass both in FF and Chrome.

**Comment by bartvde** [comment]
ah you're right, I forgot to do npm i after this step, stupid, false alarm :)

**Comment by bartvde** [comment]
I did run make serve, but apparently it did not pick up the change

**Comment by bartvde** [comment]
confirmed all is fine, sorry about the noise. After a fresh npm i I do see that the % in the test page does not update anymore, is the same happening for anyone else?

screen shot 2016-07-01 at 14 09 00

**Comment by tsauerwein** [comment]
> After a fresh npm i I do see that the % in the test page does not update anymore, is the same happening for anyone else?

Same for me.

**Comment by ahocevar** [comment]
Same for me too. It's been like this for a while.

**Pull request merged**
