### PR TITLE
Keep transformed coordinates within valid y range

### PR DESCRIPTION
**Pull request by tschaub**
This clamps y-values in forward EPSG:3857 transforms.  Without this change, if people don't modify their data before rendering it, they face hard to debug problems.

### CODE REVIEW

**Comment by fredj** [comment]
See also https://github.com/openlayers/ol3/issues/4715#issuecomment-184210214 (ping @bartvde)

**Comment by tschaub** [comment]
By not clamping y-values in our forward transform (the one everybody uses), we end up with confusingly bad results.  For example, here is [a world-spanning polygon with a star shaped hole](http://bl.ocks.org/anonymous/raw/d27b206e3b4d2f2664365fb340645af2/):

image

And when rendered in OpenLayers:

image

(Here, the interior ring is incorrectly filled.)

**Comment by marcjansen** [comment]
Thanks for this, Tim. Please merge.

**Comment by bartvde** [comment]
Post merge thank you! Great to see this handled @tschaub

**Pull request merged**
