### PR TITLE
Add link to FAQ-document and fix internal links

### LINKED ISSUE #3666: Add link to FAQ
There is no link to the [FAQ](http://openlayers.org/en/v3.5.0/doc/faq.html) from the [doc page](http://openlayers.org/en/v3.5.0/doc/).
Additionally, the FAQ internal links are not working due to id mismatches (eg `why-is-the-order-of-a-coordinate-lonlat-and-not-latlon` != `why-is-the-order-of-a-coordinate-lon-lat-and-not-lat-lon-`).

### PR DESCRIPTION
**Pull request by marcjansen**
This PR suggests to add a link to the [FAQ](http://openlayers.org/en/v3.5.0/doc/faq.html) from the [doc page](http://openlayers.org/en/v3.5.0/doc/).

Additionally some internal links to sections and some tutorials have been corrected.

Fixes #3666

### CODE REVIEW

**Comment by marcjansen** [comment]
Wait a second, none of the internal links to sections work. I'll have to do a bit more work...

**Comment by marcjansen** [comment]
This is ready for review.

**Comment by marcjansen** [comment]
Ready for review now.

**Comment by gberaudo** [comment]
Very nice @marcjansen, thank you.

**Comment by marcjansen** [comment]
Thanks for the review and the report.

**Pull request merged**
