### PR TITLE
Determine ol.global in a way that works in more environments

### LINKED ISSUE #5572: Content Security Policy error (since v3.16.0, included)
In my project we have Content Security Policy setup (https://w3c.github.io/webappsec/specs/content-security-policy, https://developer.chrome.com/extensions/contentSecurityPolicy).

While trying to upgrade the OpenLayers I am getting the following error since v3.16.0 (included)

 ``Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'". ``

in the following line:

 `` ol.global = Function('return this')();  ``

Note that using unsafe-eval is strongly recommended against (https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval)

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #5572.

### CODE REVIEW

**Comment by marcjansen** [comment]
Is there any chance we can actually test this? I would be very happy then...

I read the SO answer, but would prefer the explanation inline.

**Comment by ahocevar** [comment]
> Is there any chance we can actually test this? I would be very happy then...

Not a practicable one I guess. A pragmatic alternative approach would be to always assume a browser environment first, because the way things stand now, OpenLayers instantiation will fail anyway if `ol.global` is something different than `window`:
```js
ol.global = typeof window == 'undefined' ? Function('return this')() : window;
```
@spatialillusions, does the above work in your environment?

**Comment by probins** [comment]
I think we should also be thinking ahead to ES6 modules, where `this` is undefined. Not sure how `goog.module` handles `this`.

**Comment by tschaub** [comment]
The "common" way to do this would be:
```js
if (typeof window !== 'undefined') {
  ol.global = window;
} else if (typeof global !== 'undefined') {
  ol.global = global;
} else if (typeof self !== 'undefined') {
  ol.global = self;
}
``

Yes, OpenLayers currently relies on many `window` properties, but these can be provided by something like jsdom (I'm currently doing this with a universal React app where OpenLayers is loaded in Node).

**Comment by probins** [comment]
see also https://github.com/tc39/proposal-global

**Comment by marcjansen** [comment]
Great link, @probins. I would favor sth. as shown there for as long as needed.

**Comment by ahocevar** [comment]
At first I was surprised that @tschaub did not submit an alternative pull request, but just commented with working code. Now I know why: copying and pasting @tschaub's code: 20 seconds, entertaining the Closure compiler: 10 minutes.

Pull request changed to @tschaub's solution.

**Comment by marcjansen** [comment]
Good to go, @ahocevar. Please merge. And many thanks for your long breath here.

**Comment by probins** [comment]
> Not sure how goog.module handles this.

To answer my own question, this has just recently been changed to be 'undefined' as with ES6 modules: https://github.com/google/closure-library/commit/ee292bc0b2216d4bf3fc819df2b2184618e975d9

So I think the merged proposal is the way forward here

**Pull request merged**
