### PR TITLE
Disallowed undefined rotation value

### PR DESCRIPTION
**Pull request by fredj**
See https://github.com/openlayers/ol3/pull/3174#issuecomment-71606896

### CODE REVIEW

**Comment by tsauerwein** [comment]
LGTM

**Comment by gberaudo** [comment]
+1

**Comment by fredj** [comment]
See also #3179

**Comment by elemoine** [comment]
Why treating `rotation` differently from `resolution` and `center`? I do not see any reason. We should also think about the case where no initial state passed to the View constructor: `new ol.View()`.

**Comment by bartvde** [comment]
Because rotation has a clear default value and resolution and center do not?

**Comment by fredj** [comment]
> Why treating `rotation` differently from `resolution` and `center`? I do not see any reason. 

Because `rotation` has a default value which is set in the constructor. The `rotation` is always a `number` (except if `view.setRotation(undefined)` or `view.setRotation(false)` is used)

> We should also think about the case where no initial state passed to the View constructor: `new ol.View()`.

In this case `rotation` is `0` and `center` is `null`. `resolution` is not set (`undefined`)

**Comment by elemoine** [comment]
> Because rotation has a clear default value and resolution and center do not?

Ok, that makes more sense now, and I agree.

So `resolution` and `center` have no natural default values, so `undefined`/`null` are possible values for them. Ok.

Thanks @bartvde and @fredj.

**Comment by fredj** [comment]
Thanks a lot for the review

**Pull request merged**
