### PR TITLE
Remove all remaining unnecessary casts

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
There is still such a cast in the goog library itself.
See https://github.com/google/closure-library/pull/637.

If/when the PR is merged in closure library, I will create a new PR to enable
unnecessary casts checks.

**Comment by gberaudo** [comment]
Travis timed out.

**Comment by gberaudo** [comment]
Rebased onto master. Any review?

**Comment by gberaudo** [comment]
@fredj found out there is a way to restrict the checks to our code.
I enabled this restriction and removed the `jscomp_off` for `unneccessaryCasts`.
Please review.

**Comment by tschaub** [comment]
This looks great.  Thanks @gberaudo.

**Comment by gberaudo** [comment]
Thanks for the review @tschaub.

**Pull request merged**
