### PR TITLE
Remove use of goog.object.getKeys

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
It was the last `goog.object.getKeys` in ol3, thanks for any review

**Comment by marcjansen** [comment]
This looks good, @fredj. Do you think we must mention that it'll never be null from now on?

Please merge, with or without a note.

Thanks.

**Comment by fredj** [comment]
`pointerMap` was already never `null` but the annotation was not precise.

**Comment by fredj** [comment]
Thanks for the review Marc

**Pull request merged**
