### PR TITLE
Warn when viewing an outdated example, and offer a redirect to latest

### LINKED ISSUE #5235: Add notice to old release examples about a newer release
There should be a notice that pops up on old release examples (and docs) that points people to the same for the latest release.

### PR DESCRIPTION
**Pull request by ahocevar**
This fixes #5235 for future releases.

### CODE REVIEW

**Comment by ahocevar** [comment]
Still work in progress. Should be a div at the top of the page rather than a confim/alert box.

**Comment by ahocevar** [comment]
This is now ready for review. 

The link to latest will be the same example for the latest version if it exists, and to the examples index otherwise. Once the dialog is dismissed, it will not show up again until the latest version was updated. The result will look like this:

warn-latest

**Comment by marcjansen** [comment]
This will also appear if one os viewing the latest, right? If doable, it'd only show the warning in case a newer version exists. Of you can find the time to change it like this, that'd be much appreciated.

**Comment by ahocevar** [comment]
@marcjansen See https://github.com/ahocevar/ol3/blob/19692ed60a6bf8388a3e7b8350d37bd9ed240902/config/examples/example.html#L104 - the regex test excludes any paths that do not include a version number. So the warning won't be shown for the latest. And it also won't be shown if the latest is v3.15.1 and you're viewing v3.15.1, because then `'{{ olVersion }}'` will not equal `latestVersion`.

**Comment by marcjansen** [comment]
Even better! Convinced, please merge. Thanks.

**Pull request merged**
