### PR TITLE
Check ol.source.UrlTile#urls property for null value

### LINKED ISSUE #4446: Cannot create ol.source.TileWMS with only tileLoadFunction in version 3.11.1
I just upgraded to version 3.11.1 from 3.10.1.
Unfortunately I cannot create ol.source.TileWMS without 'url' or 'urls' parameter in options.
The error comes from this method:
ol.source.TileWMS.prototype.resetCoordKeyPrefix_
It tries to iterate over 'this.urls' array which is actually null.
Previously this method iterated on 'this.urls_' and it worked fine.

### PR DESCRIPTION
**Pull request by fredj**
Fixes #4446

### CODE REVIEW

**Comment by ahocevar** [comment]
Very nice fix, thanks @fredj. Please merge.

**Comment by bartvde** [comment]
do we need a 3.11.2 release?

**Comment by ahocevar** [comment]
If so, then we should wait until I have a fix for #4441.

**Comment by tschaub** [comment]
I'll cherry pick these fixes for 3.11.2.

**Pull request merged**
