### PR TITLE
Release v3.5.0

### PR DESCRIPTION
**Pull request by tschaub**
This adds a changelog and bumps the package version.

### CODE REVIEW

**Comment by probins** [comment]
what's the process for updating the cdnjs version? The hosted examples source display is now using https://cdnjs.cloudflare.com/ajax/libs/ol3/3.5.0/ol.js but this doesn't exist. So created fiddles don't work either.

And how often is http://openlayers.org/en/master/build/ol.js regenerated? This is currently using a commit from last week, before 3.5

**Comment by ahocevar** [comment]
It is updated automatically by cdnjs, once a day I think. So examples should be working shortly.

**Comment by ahocevar** [comment]
The master examples are updated manually, without a regular schedule.

**Comment by probins** [comment]
cdnjs now updated - fiddles now work again, thanks

**Pull request merged**
