### PR TITLE
Close polygon sketch at all times

### LINKED ISSUE #6023: draw polygon
auxiliary shading is drawn from the second point

issue_openlayer

### PR DESCRIPTION
**Pull request by bjornharrtell**
Fixes #6023.

### CODE REVIEW

**Comment by marcjansen** [comment]
Thanks for tackling this. Would you be able to add a test for this regression?

**Comment by bjornharrtell** [comment]
Yes I think so (tomorrow or so) if it's ok to write tests that inspects private members?

**Comment by marcjansen** [comment]
Yes,  we do that elsewhere as well.

**Comment by bjornharrtell** [comment]
Added validation of sketch polygon to existing test.

**Comment by ahocevar** [comment]
Awesome, thanks for your effort @bjornharrtell!

**Pull request merged**
