### PR TITLE
Remove unnecessary map.render() calls

### PR DESCRIPTION
**Pull request by bartvde**
Supersedes #5078

### CODE REVIEW

**Comment by fredj** [comment]
Doesn't work when the kinetic effect is not active.

**Comment by fredj** [comment]
Please read the comments in #5078

**Comment by bartvde** [comment]
@fredj is https://github.com/fredj/ol3/commit/8c99fd596d06d67fb5fcccf1337931efe4768320 still relevant? I forgot about that one indeed.

**Comment by fredj** [comment]
To reproduce the issue:
open examples/simple.html and slowly pan so that the kinetic effect doesn't occur -> the tiles are not loaded

**Comment by bartvde** [comment]
thanks, confirmed it is still an issue indeed

**Comment by bartvde** [comment]
@fredj can you open up a PR for your fix? If we cannot think of a better solution, we should go ahead and merge your fix I think. What do you think? Ping @ahocevar as well.

**Pull request merged**
