### PR TITLE
Use fs-extra as fs, remove usage of graceful-fs

### PR DESCRIPTION
**Pull request by marcjansen**
This PR suggests to import `fs-extra` as fs and to no longer import either `fs` or `graceful-fs`.

Since [`v0.15.0`](https://github.com/jprichardson/node-fs-extra/releases/tag/0.15.0) `fs-extra` includes graceful-fs and should behave identically.

### CODE REVIEW

**Comment by fredj** [comment]
+1, thanks

**Comment by marcjansen** [comment]
#2833 by @tschaub introduced `graceful-fs` to ol3. Any chance @tschaub may chime in to say if `fs-extra` does what `graceful-fs` did?

**Comment by ahocevar** [comment]
@marcjansen As far as I can tell, fs-extra uses jsonfile's `readFile`, which does not handle the EMFILE and ENFILE errors mentioned in #3646. But I'm right now running all tasks with your branch to see if that is still an issue, now that we have much less files to handle thanks to the ongoing Closure library removal.

**Comment by ahocevar** [comment]
@marcjansen Everything works fine on my OSX with your branch.

**Comment by marcjansen** [comment]
> Everything works fine on my OSX with your branch.

So is this a `LGTM, please merge` ? :wink:

**Comment by ahocevar** [comment]
I would say so, yes :-). Thanks @marcjansen.

**Comment by marcjansen** [comment]
Thanks for the input and reviews, @ahocevar & @fredj.

**Pull request merged**
