### PR TITLE
Revert "Use offsetX and offsetY if available"

### LINKED ISSUE #3120: Feature hits overlay
Hello,

I have an issue when you modify a feature and it hits an overlay on the map.
http://jsfiddle.net/cp7a9phx/1/

Thank you.

### LINKED ISSUE #3121: ol.Overlay stopEvent is broken
http://openlayers.org/en/master/examples/icon.html open the popup by clicking the icon and try to zoom by using the mouse wheel.

#2975 is guilty

### LINKED ISSUE #3133: Feature drag outside map area
I think there is a bug in Openlayers with the Feature drag example at http://openlayers.org/en/v3.1.1/examples/drag-features.html

The Feature jumps around when being dragged outside the map area.

### PR DESCRIPTION
**Pull request by fredj**
This reverts commit fabf05977a7bd025ba68f53aa1a41dcdabe06925.

fixes #3120 
fixes #3121 
fixes #3133

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for any review

**Comment by bartvde** [comment]
didn't know reverting your own merged PR required review ;-)

please merge

**Comment by elemoine** [comment]
Do people think we need to release v3.1.2 for that?

**Comment by bartvde** [comment]
Personally I don't think this is needed. People can use master in the interim and 3.2 is just around the corner (2 weeks). But that's my 2cents.

**Comment by fredj** [comment]
I also don't think a new release is needed (3.2.0 is due by february 1 (?))

**Comment by elemoine** [comment]
Fine by me.

**Pull request merged**
