### PR TITLE
Add parsing of some WMS 1.1.1 specific nodes

### PR DESCRIPTION
**Pull request by oterral**
This PR add the parsing of `<SRS>` and `<LatLonBoundingBox>` nodes (WMS 1.1.1)

Adds also tests for parsing of a WMS  Getcapabilities 1.1.1 file

### CODE REVIEW

**Comment by ahocevar** [comment]
To keep things clean, I also think each version should have it's own class. This should be possible without much duplicated code, by sharing readers that are the same for both versions.

**Comment by adube** [comment]
I would be willing to carry on the efforts made here to support v1.1.1 in the next few weeks, if that's okay with everyone.

What would the files look like.  How about:

    ol/format/wmscapabilities/wmscapabilitiesv1format.js
    ol/format/wmscapabilities/wmscapabilitiesv1_1format.js
    ol/format/wmscapabilities/wmscapabilitiesv1_3format.js

What would the class names look like ?

**Comment by bartvde** [comment]
I think I'd go with the same convention as the GML versioned format so:

```
ol/format/wmscapabilities/wmscapabilitiesbaseformat.js
ol/format/wmscapabilities/wmscapabilities1_1format.js
ol/format/wmscapabilities/wmscapabilities1_3format.js
```

Class names:

```
ol.format.WMSCapabilitiesBase
ol.format.WMSCapabilities1_1
ol.format.WMSCapabilities1_3
```

?

**Comment by bartvde** [comment]
Although what we had before is closer to what you suggest, no strong preference here from me.

https://github.com/openlayers/ol3/pull/180

**Comment by adube** [comment]
Gotcha.  That makes more sense like this indeed.  Thanks.

@oterral would you please give me access to your branch for me to work on it directly ?  I'd let you know when I start.  Please, let me know if you agree with this.  Thank you.

**Comment by oterral** [comment]
Sorry @adube  totally miss your comment. Are you still interested to have access  to this branch ?

**Comment by oterral** [comment]
You should have acess now

**Comment by ahocevar** [comment]
@adube, are you still working on this?

**Comment by ahocevar** [comment]
Closing for now, due to lack of activity. @adube, please reopen when you continue working on it.

**Comment by jbelien** [comment]
I noticed that OL supports only WMS 1.3.0+ GetCapabilities !

Is there any reason older WMS version were never implemented ?
Would it be worth to submit a new PR to add this ? Quite a "lot" of issues asked for this but didn't find any reason why it has never be implemented !

Thanks :)

**Comment by ThomasG77** [comment]
Could be wrong but because you can
* use JSONIX for this intent http://bl.ocks.org/ThomasG77/cb12b00df3a5c117dbe5
* a more generic solution to convert XML to JSON in JavaScript and loop https://www.npmjs.com/package/xml-js

**Pull request closed without merging**
