### PR TITLE
Remove unused goog.require

### PR DESCRIPTION
**Pull request by fredj**
Found by the latest version of closure-compiler (v20150729)

### CODE REVIEW

**Comment by elemoine** [comment]
Excellent. Thanks @fredj.

**Comment by tschaub** [comment]
Nice!  What's your process for identifying these @fredj?  Can something in the latest version of the compiler be used to replace `check-requires.py`?

**Comment by fredj** [comment]
> Nice!  What's your process for identifying these @fredj?  Can something in the latest version of the compiler be used to replace `check-requires.py`?

With the new compiler version, wildcard are accepted for `jscomp` properties (that's what I used):
```
...
"jscomp_error": [
      "*"
],
...
```

**Comment by fredj** [comment]
See https://github.com/openlayers/ol3/compare/master...fredj:update_compiler

**Pull request merged**
