### PR TITLE
Release v3.4.0

### PR DESCRIPTION
**Pull request by bartvde**

### CODE REVIEW

**Comment by elemoine** [comment]
@bartvde You also need to add `### v3.4.0` to `changelog/upgrade-notes.md`, though the content of that section will be empty in this case. See https://github.com/openlayers/ol3/pull/3308.

**Comment by bartvde** [comment]
ah I thought if there is nothing it wouldn't be needed, will add it now

**Comment by elemoine** [comment]
> ah I thought if there is nothing it wouldn't be needed, will add it now

Hmm… You're right, it may not be not needed. But it may be less confusing to have it.

**Comment by bartvde** [comment]
@elemoine see #3407

**Pull request merged**
