### PR TITLE
Remove unused pruneTileRange function

### LINKED ISSUE #5524: ol.TileCache.prototype.pruneTileRange function can be optimized
After removing item from cache "i" counter variable can be decreased by 1. Currently system doing unnecessary iteration for every removed item.

Proposed code:
```
ol.TileCache.prototype.pruneTileRange = function(tileRange) {
   var i = this.getCount(),
       key;
   while (i-- > 0) {
     key = this.peekLastKey();
     if (tileRange.contains(ol.tilecoord.createFromString(key))) {
       this.pop().dispose();
       i--;
     } else {
       this.get(key);
     }
   }
};
```

### PR DESCRIPTION
**Pull request by bartvde**
Closes #5524 thanks to @gzhebrunov for pointing this out.

### CODE REVIEW

**Comment by bartvde** [comment]
I'll add a unit test.

**Comment by bartvde** [comment]
@ahocevar seems this function is not used anymore in the library?

**Comment by ahocevar** [comment]
Oh. Would be good to know since when it is unused. It seems to me that this function is important.

**Comment by bartvde** [comment]
Unless I'm misreading things, it was not even used in 3.0.0, which means it was never used?

**Comment by bartvde** [comment]
Can't find it used in any of the 3.x.0 releases

**Comment by ahocevar** [comment]
Ok cool, so let's get rid of it.

**Comment by fredj** [comment]
the function was added in #850 and removed in #1551

**Comment by bartvde** [comment]
thanks @fredj

**Pull request merged**
