### PR TITLE
Fix up failing KML test in Firefox

### LINKED ISSUE #3439: Test ol.format.KML#readNetworkLinks fails on Firefox
Test: "returns an array of network links"

    expected 'http://localhost:3000/test/bar/bar.kml' to equal 'bar/bar.kml'

### PR DESCRIPTION
**Pull request by bartvde**
fixes #3439 

TIA for any quick review

### CODE REVIEW

**Comment by bartvde** [comment]
What we are seeing in Firefox is to be expected given https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI

**Comment by ahocevar** [comment]
Try `.getAttribute('href')` instead of `.href`. Should be a nicer to read fix.

**Comment by bartvde** [comment]
Not sure I understand @ahocevar this is the result object from the KML parser, not an XML structure?

**Comment by ahocevar** [comment]
Ah I see. The test would be easier to read like this I think:
```js
expect(nl[0].href.replace(window.location.href, '').to.be('bar/bar.kml');
```

**Comment by bartvde** [comment]
Agreed ;-) made the change

**Comment by ahocevar** [comment]
Yep, looks good now. Please merge when Travis agrees.

**Pull request merged**
