### PR TITLE
Remove goog.fx.easing

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by ahocevar** [comment]
Nice. Please merge when Travis says so.

**Comment by bartvde** [comment]
@fredj we cannot simply copy code from an Apache 2.0 project and release it as BSD?

**Comment by ahocevar** [comment]
@bartvde Have you looked at the change? It's trivial code.

**Comment by bartvde** [comment]
@ahocevar yes, but it's still a copy action? Does the type of function you copy have any impact on the legal implications you think?

**Comment by ahocevar** [comment]
I'm not a legal expert, but the change that @fredj made is a change from goog.fx function references to function with trivial math in it. He probably hasn't even copied it, but knew from math class that this is standard cubic easing, which can be found in scientific literature and e.g. [here](http://gizma.com/easing/). But it may make sense to change the commit message and mention that this is cubic easing.

**Comment by fredj** [comment]
And I've found the same equations at http://joshondesign.com/2013/03/01/improvedEasingEquations (`easeInCubic` and `cubicOut`)

**Comment by fredj** [comment]
Commit message changed

**Comment by ahocevar** [comment]
> Has this already been discussed in general wrt getting rid of the Google closure library in ol3?

@bartvde, we won't copy code from Closure library directly. The biggest chunks are removal of goog.events, which we will replace with a custom simple events system (use browser events directly for MapBrowserEvent, and very simple events for anything else), and goog.Mat*, which we'll replace with a different 3rd party library that comes annotated for Closure compiler (like e.g. https://github.com/richardanaya/SylvesterClosure).

**Comment by bartvde** [comment]
okay good to go then

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
