### PR TITLE
Remove IE workarounds in src/ol/xml.js

### PR DESCRIPTION
**Pull request by fredj**
Remove workaround for IE < 9

### CODE REVIEW

**Comment by gberaudo** [comment]
Great work!

**Comment by fredj** [comment]
No more `goog.dom.xml` !

**Comment by tsauerwein** [comment]
> No more goog.dom.xml!

Have you tested if this reduces the build size significantly?

**Comment by bartvde** [comment]
I assume you've run unit tests in IE9 right?

**Comment by fredj** [comment]
> I assume you've run unit tests in IE9 right?

of course :-) but they are not passing because of #4947 (that's not related)
I still want to try the examples on IE9

**Comment by fredj** [comment]
> Have you tested if this reduces the build size significantly?

` build/ol.js`is 477K for this branch and 478K for master

**Comment by fredj** [comment]
ok, examples works on IE9 and IE10

**Comment by tschaub** [comment]
This looks like a great change to me.  Please merge @fredj.

**Pull request merged**
