### PR TITLE
DEVELOPING.md: add note on running Travis on development branches

### PR DESCRIPTION
**Pull request by probins**
just ran into this little issue :-)

### CODE REVIEW

**Comment by ahocevar** [comment]
You can either run `make ci` to run the same tests that Travis runs, or you can create a pull request. Once you have a pull request, Travis will check your branch.

That said, I do not think it is a good idea to advise devs to change `.travis.yml`, especially when they are newcomers and not so familiar with git to perform tasks like squash or amend.

**Comment by probins** [comment]
yes, but the point is that this file is out of date. Travis will no longer run on your fork (unless you always push to the master branch). Either DEVELOPER.md needs to be changed as I suggest, or this section about running Travis on your fork should be removed. The purpose of this section is that you can use Travis to run the ci without installing anything locally.

**Comment by ahocevar** [comment]
Ah I see. Maybe just say that Travis will check the branch as soon as the pull request is submitted, or really remove the section.

**Comment by probins** [comment]
replaced by #5088

**Pull request closed without merging**
