### PR TITLE
Remove extra provide causing a circular dependency

### PR DESCRIPTION
**Pull request by ahocevar**
Addresses https://github.com/openlayers/ol3/commit/bed95e3b5b3fbefaf4cb2e8b2bd9ffaad95f261f#commitcomment-18885169.

### CODE REVIEW

**Comment by ahocevar** [comment]
I think this does not require a formal review. I'll merge when green.

**Comment by bartvde** [comment]
+1

**Comment by ahocevar** [comment]
Feels even better with a revíew. Thanks @bartvde.

**Comment by marcjansen** [comment]
You'll get one nonetheless. Looks good to me, please merge when green.

Why didn't ci catch this?

**Comment by ahocevar** [comment]
Thanks, so many reviews :-)

> Why didn't ci catch this?

I think the way we build the dependency tree it does not matter, and we have no eslint rule checking if we require something that we provide in the same file.

**Pull request merged**
