### PR TITLE
Replace pake with make?

### PR DESCRIPTION
**Pull request by elemoine**
My `makefile` branch replaces `pake` by GNU `make`. The migration is not complete (but not so far either), but I'd like to know what people think about this before going further.

Replacing the `build.py` script by a `Makefile` would allow for a more compact file, and would make us rely on a mainstream tool instead of `pake`.

The question is: do people want to use a tool like `make`? Or do people think we'd do just fine with just `node`, `npm` and `npm` tasks? These questions are related to [my comment](https://github.com/openlayers/ol3/pull/3504#issuecomment-91015547) in #3504.

Personally, I'd like to use `make`, because it's very nice to do `make check` and have `make` figure out the minimum set of things that needs to be rebuilt.

### CODE REVIEW

**Comment by marcjansen** [comment]
I am personally not at all opposed to make. I don't know so much node / npm so that I could decide if they can be used to accomplish sth. similar than what we have with pake or what we would get with make.

**Comment by pagameba** [comment]
The biggest requirement in my mind is that the build system work reliably for users on all platforms that are supported.

**Comment by elemoine** [comment]
Current Makefile is very close to feature parity with `build.py`. It is also much more concise.

**Comment by elemoine** [comment]
> The biggest requirement in my mind is that the build system work reliably for users on all platforms that are supported.

I haven't tested it myself, but some people reported to me that http://gnuwin32.sourceforge.net/packages/make.htm worked great for them.

And, as indicated in https://github.com/openlayers/ol3/issues/3532, Windows users should be able to get by with `npm install`, `npm test`, and `npm start`. So I don't think this PR is incompatible with #3532.

**Comment by ThomasG77** [comment]
I would suggest to use [Shelljs](https://github.com/arturadib/shelljs). The official description is *Portable Unix shell commands for Node*.
It supports a syntax similar to Makefile. It's well supported (around 2300 stars on Github)

Best of both worlds:
* Unix like tools simplicity
* no limitations due to Make support difference between OS, thanks to Node

**Comment by tschaub** [comment]
+1 (with caveats)

As described in #3532, I'd like it if `npm install`, `npm test`, and `npm start` could be cross-platform with minimal system dependencies.  Specifically, I don't think these should run anything but Node based tasks.

The `generate-requires.js` task needs a bit of discussion if we are going to meet this objective.  As it is, it is not practical to run the task without `make` (and `find`).  One alternative would be to make it accept a directory path instead of a list of file paths.  I don't think we'd suffer that much without `make`'s `mtime` comparison here.  But I also don't think this task is necessary, so it may not be the best example.  Anyway, I'm in favor of using `make` instead of `pake`.  But I think this will involve a bit more reworking of tasks.

**Comment by elemoine** [comment]
> As described in #3532, I'd like it if npm install, npm test, and npm start could be cross-platform with minimal system dependencies. Specifically, I don't think these should run anything but Node based tasks.

Cool. 

> The generate-requires.js task needs a bit of discussion if we are going to meet this objective. As it is, it is not practical to run the task without make (and find). One alternative would be to make it accept a directory path instead of a list of file paths. I don't think we'd suffer that much without make's mtime comparison here. But I also don't think this task is necessary, so it may not be the best example.

Yep. I'll wait a bit to see what you come up with regarding the execution of the unit and rendering tests, and whether the `test_requires.js` and `test_rendering_requrires.js` files are required.

I'd be interested to know about the other tasks that you think need reworking. Except `generate-requires.js`, everything looks good to me.

Note that I also added `bin/check-requires.py` and `bin/check-whitespace.py` python scripts. These are extractions from `build.py`. They are now run from the `Makefile`. Later, we can possibly rewrite them in node/js, but that's certainly not something I want to do now.

**Comment by elemoine** [comment]
The `Makefile` is now feature-parity with `build.py`. All the `build.py` targets have been ported, and the Python functions that were in `build.py` are now separate Python scripts (placed in the `bin` directory).

I am going to watch @tschaub's work (https://github.com/openlayers/ol3/pull/3558 for example), and will port his changes to the `Makefile`.

We will also need to modify the `Makefile` when we make `npm test` work without generating "requires" files. This is related to @tschaub's comment [above](https://github.com/openlayers/ol3/pull/3527#issuecomment-92192443).

@tschaub, it sounds like we need to coordinate.

**Comment by elemoine** [comment]
Changes to `build.py` from https://github.com/openlayers/ol3/pull/3558 now ported to the `Makefile`.

Do people still agree with moving from `pake` to `make` as our "advanced" build tool?

**Comment by elemoine** [comment]
Anyone opposed to merging this? If/when this is merged I'll go ahead and change `openlayers.github.io` to use `make` instead of `build.py`. And when this is done I'll come with a new ol3 PR for removing `build.py` entirely.

**Comment by tonio** [comment]
not opposed at all.

**Comment by fredj** [comment]
+1

**Comment by elemoine** [comment]
There were remaining issues on OS X. They are not fixed.

**Comment by elemoine** [comment]
I updated `CONTRIBUTING.md` and other files to replace `build.py` by `make`. I also decided to remove `build.cmd`, `build.py` and `pake.py` as part of this pull request.

When this is merged I'll merge https://github.com/openlayers/openlayers.github.io/pull/51 and immediately re-build the website to verify that everything works as expected.

As [commented](https://github.com/openlayers/ol3/pull/3527#issuecomment-92192443) by @tschaub we ultimately want `npm install`, `npm test` and `npm serve` to be cross-platform with minimal system dependencies This, in particular, means that having the `serve.js` task, instead of the `Makefile`, generate the `test_requires.js` and `test_rendering_requires.js` files.

Using the `Makefile` is similar to using `build.py`. For example, to start the development server you'll just use `make serve` instead of `build.py serve`. And to run the code checkers you'll use `make check` instead of `build.py check`.

You can run `make help` (or just `make`) to get a list of the most common targets. This is the current output of `make help`:

```
$ make

The most common targets are:

- install                 Install node dependencies
- serve                   Start dev server for running examples and tests
- test                    Run unit tests in the console
- check                   Perform a number of checks on the code
- clean                   Remove generated files
- help                    Display this help message

Other less frequently used targets are:

- build                   Build ol.js, ol-debug.js, ol.js.map and ol.css
- lint                    Check the code with the linter
- ci                      Run the full continuous integration process
- apidoc                  Build the API documentation using JSDoc
- cleanall                Remove all the build artefacts
- check-deps              Check if the required dependencies are installed
```

**Pull request merged**
