### PR TITLE
Add in crossOrigin option

### PR DESCRIPTION
**Pull request by llambanna**
into ol.source.TileArcGISRest

### CODE REVIEW

**Comment by bartvde** [comment]
Can you get rid of the unneccessary whitespace changes and then please squashing your commits into a single commit?

**Comment by llambanna** [comment]
thanks, finally found time to do this, all rebased into a single commit

**Comment by bartvde** [comment]
thanks, this looks good now, have you signed a CLA already?

https://github.com/openlayers/cla

**Comment by llambanna** [comment]
Yes I have

**Comment by bartvde** [comment]
thanks for your contribution

**Comment by llambanna** [comment]
Thanks for your patience and help.

**Pull request merged**
