### PR TITLE
Snap to vertices or edges

### PR DESCRIPTION
**Pull request by drnextgis**
Fix for issue #3850

### CODE REVIEW

**Comment by drnextgis** [comment]
Demo: http://jsfiddle.net/_DR_/vjxzyqx5/

**Comment by ahocevar** [comment]
Thanks for this, great work! Can you please either add upgrade notes that snapping to edges is now active, or set edge snapping to false by default?

**Comment by drnextgis** [comment]
Maybe I misunderstood you but if I set edge snapping to false by default it will change current `ol.interaction.Snap` default behaviour.

**Comment by ahocevar** [comment]
@drnextgis Sorry, I understood you! I was under the impression that we currently have only vertex snapping, which is not true of course.

**Comment by drnextgis** [comment]
In API docs about `ol.interaction.Snap`:

> Handles snapping of vector features while modifying or drawing them.

But I've found that `ol.interaction.Modify` has own snapping part and `ol.interaction.Snap` doesn't affect it. Any thoughts how we can fix it? Related issue https://github.com/openlayers/ol3/issues/4177

**Comment by ahocevar** [comment]
I don't think #4177 is related. If I understand that issue correctly, it is about restricting the Modify interaction to disallow the addition of new vertices.

Regarding this issue, the Modify interaction has no snapping. What feels like snapping is only the positioning of the edit vertex and the decision whether to place it on an existing vertex or on an edge. Once you move that vertex, there is no snapping whatsoever. You can influence that behaviour with the `pixelTolerance` option.

**Pull request merged**
