### PR TITLE
overview map uses projection parameter or base projection before defaults

### LINKED ISSUE #2998: Overview map control ignores base map projection
..defaults to EPSG:3857. 

IMHO, it should default to the base map projection, and allow a view (or projection) parameter to assign a different view projection.

### PR DESCRIPTION
**Pull request by relet**
closes #2998 as per #3001, but the ol.Map object is only initialized when setMap makes the base map for this control known.

### CODE REVIEW

**Comment by ahocevar** [comment]
@relet Sorry that this got delayed for so long. Can you please update your pull request so it can be applied to current master? Also, it seems you haven't submitted a [CLA](https://github.com/openlayers/cla) yet. Can you please do so?

**Comment by bartvde** [comment]
@relet any chance you can rebase this PR and submit a CLA before the 3.5 release (end of April / early May)

**Comment by MrJH** [comment]
Give this thing a try today. Problems are in validateExtent_:
 * `view.getProjection()` is called where `view` is undefined
 * then, if i define `var view = map.getView();` from some lines below, `view.getProjection()` is throwing an undefined error, which i have not debugged yet.

**Comment by ahocevar** [comment]
Closing due to lack of activity. @MrJH, please reopen if you continue addressing the remaining issues.

**Pull request closed without merging**
