### PR TITLE
Combine standard coverage and rendering coverage

### PR DESCRIPTION
**Pull request by marcjansen**
This is open for discussion.

Wouldn't it be nice if we knew the code coverage of our rendering tests? And wouldn't it even be better if we knew the combined coverage of standard-tests and coverage ones?

This PR contains a commit that does that, it is open for your input. Just share what you think.

(PS: with rendering tests participating in the total coverage percentage, we're at ~86%, plus ~4.8%)

### CODE REVIEW

**Comment by marcjansen** [comment]
this needs more work... it'll take some time for me as i am offline now.

**Comment by marcjansen** [comment]
I think this is ready to be reviewed.

**Comment by marcjansen** [comment]
Anyone up for a review, @openlayers/ol3?

**Comment by bartvde** [comment]
looking at it now @marcjansen

**Comment by marcjansen** [comment]
Thanks for the review, Bart.

**Pull request merged**
