### PR TITLE
bing https logo fix

### PR DESCRIPTION
**Pull request by photostu**
If https is missing from bing logo uri, replace

### CODE REVIEW

**Comment by pagameba** [comment]
why not use a protocol-less URI (//...)?  No code required.

**Comment by bartvde** [comment]
@pagameba the bing Maps metadata sends back an explicit ```http://```

**Comment by photostu** [comment]
I like the idea of removing the protocol as well, apparently this is considered an anti-pattern now though.
I updated my PR to fix syntax for Travis, my first time submitting here, please be gentle.

**Comment by pagameba** [comment]
@bartvde ah :)

**Comment by tschaub** [comment]
Thanks for the contribution @photostu.  I think this looks like a sensible fix until Bing advertise the logo URL with the correct protocol.

**Comment by photostu** [comment]
No problem, glad I could contribute! :-)

**Comment by bartvde** [comment]
@photostu have you signed a CLA already? If not, please see: https://github.com/openlayers/cla for details. TIA.

**Comment by photostu** [comment]
I had not signed before, but just took care of it. Cheers.

**Comment by bartvde** [comment]
thanks!

**Pull request merged**
