### PR TITLE
Remove check-requires script

### PR DESCRIPTION
**Pull request by fredj**
The `missingProvide` and `missingRequire` compiler checks are already checking
if the `goog.require` and `goog.provide` are correct.

Replace #3988

### CODE REVIEW

**Comment by fredj** [comment]
There's something wrong with this; the compiler doesn't detect missing `goog.require`.
For example, if `goog.require('goog.array');`is removed from `src/ol/map.js` no error is raised

**Comment by ahocevar** [comment]
> if goog.require('goog.array');is removed from src/ol/map.js no error is raised

I think this is because no code path that calls `ol.Map#removePreRenderFunction()` is ever entered, and the compiler detects that.

That said, I'm still in favour of merging this.

**Comment by fredj** [comment]
`missingRequire` only checks the constructors

**Comment by ahocevar** [comment]
Does this mean that you can actually get a broken build from missing requires?

**Comment by fredj** [comment]
> Does this mean that you can actually get a broken build from missing requires?

I don't think so; the compiler will emit an error if something is missing.

Are you still ok to merge this?

**Comment by probins** [comment]
Can this be merged? I'm running into problems with `typedefs.js`, as it thinks the sub-namespaces need to be `require`d. I could add a condition to ignore `typedefs.js`, but it would be simpler if check-requires were removed.

**Comment by ahocevar** [comment]
+1 on merging this.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
