### PR TITLE
Use Array.isArray instead of goog.isArray

### PR DESCRIPTION
**Pull request by fredj**
Depends on https://github.com/google/closure-compiler/pull/1451

### CODE REVIEW

**Comment by tschaub** [comment]
It would be nice if the compiler understood `Array.isArray()` in the way it understands `goog.isArray()`.

**Comment by tschaub** [comment]
> It would be nice if the compiler understood Array.isArray() in the way it understands goog.isArray().

Left that comment before reading the associated issues.

**Comment by fredj** [comment]
Ready to be reviewed

**Comment by marcjansen** [comment]
I like this. +1 on merging. @tschaub?

**Pull request merged**
