### PR TITLE
Reprojected extent requests for WMS sources

### PR DESCRIPTION
**Pull request by geonux**
Add the capability to handle layers from WMS servers, event if theses layers are not available in the projection of the View.
This is an approximative raster reprojection using the WMS server capabilities, good enough at high zoom levels.

For exemple, with these modifications, it is possible to have a WMS layer only available in the EPSG:4326 projection inside of a Global Mercator view.

### CODE REVIEW

**Comment by klokan** [comment]
The true "On the fly raster reprojection for WMS sources" to be done in OL3 is described under #3785.

This ticket should be renamed - as @tschaub mentioned, and @geonux agreed.
I am renaming it to "Reprojected extent requests for WMS sources"

**Comment by tschaub** [comment]
Closing this due to lack of activity.

**Comment by geonux** [comment]
Changing the branch name to ```server_projection_approx```.

**Comment by elemoine** [comment]
Feel free to create a new PR based on your new branch. 

I am not a projection expert but why are you talking about an "approximation"?

**Pull request closed without merging**
