### PR TITLE
Fixed issue with multi option of ol.interaction.Select

### LINKED ISSUE #5856: ol.interaction.Select doesn't work correctly with multi option enabled
This line does not work with multi option enabled:
https://github.com/openlayers/ol3/blob/master/src/ol/interaction/select.js#L276
I will create a PR to fix it.

### PR DESCRIPTION
**Pull request by simonseyock**
This fixes #5856

### CODE REVIEW

**Comment by simonseyock** [comment]
The require needs to stay, I fix that soon.

**Comment by simonseyock** [comment]
@ahocevar: Even if you do not use ol.interaction.Select anymore, could you look into this PR or ping another core developer to check and merge it?

**Comment by ahocevar** [comment]
@tsauerwein or @fredj, would either of you be able to review this?

**Comment by fredj** [comment]
ok, code LGTM

**Comment by simonseyock** [comment]
Merge please?

**Comment by marcjansen** [comment]
Code is looking OK to me as well. Merging now. Thanks @simonseyok, keep up the good work.

**Pull request merged**
