### PR TITLE
Replace mouseMove event condition by pointerMove in Earthquake Cluster Example

### PR DESCRIPTION
**Pull request by frx08**
#3281 lacked this change

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks frx08 for catching this. Can you please submit a [CLA](https://github.com/openlayers/cla) so we can merge this?

**Comment by elemoine** [comment]
FYI I've noticed a problem on touch devices related to the replacement of mousemove by pointermove for the select interaction. I'll provide more details next week.

**Comment by frx08** [comment]
@ahocevar i've submitted my CLA.

**Comment by elemoine** [comment]
> FYI I've noticed a problem on touch devices related to the replacement of mousemove by pointermove for the select interaction. I'll provide more details next week.

See https://github.com/openlayers/ol3/pull/3281#issuecomment-77829716.

**Comment by ahocevar** [comment]
Closing due to lack of activity. @frx08 Are you able to address @elemoine's comment? If so, please reopen.

**Pull request closed without merging**
