### PR TITLE
Publish to bower repo

### PR DESCRIPTION
**Pull request by malaretv**
Regarding #3119

Added a sub-task to publish.sh that publishes to a specified bower repo.

With this in place would still need a few things for ol3 to be published to bower:
- Create `openlayers/bower-ol3` with a bower.json similar to that seen at malaretv/bower-ol3
- Register package with bower using `bower register` (see http://bower.io/docs/creating-packages/#register)

Note that this currently depends on bower being install globally via npm. If that is not acceptable bower could be added as dev dependency or the `bower version` task can be done manually by updating the json and adding the correct tag.

### CODE REVIEW

**Comment by ahocevar** [comment]
Nice, thanks for getting this started @malaretv! Can't we add a bower.json directly to the ol3 repo, like we do with package.json?

**Comment by malaretv** [comment]
My thinking was to avoid pulling down files unnecessary for production, but now I realize the bower.json provides an `ignore` field for that purpose. Will revise and remove the need for a separate repo.

**Comment by bartvde** [comment]
yeah but ignore only filters after they have been pulled in I think

**Comment by malaretv** [comment]
@bartvde ah yeah couldn't find any documentation on how the ignore works but looking at the source looks like you're right.

Also I take back what I said above it seems a separate repo actually does make sense here. Bower does not run any postinstall steps so it expects the built js to be in the repo. An alternative to keeping the bower distribution in it's own repository is include the `dist/` folder in the tagged releases. This would also eliminate the need to run the closure compiler as post install step for npm.

**Comment by ahocevar** [comment]
I think adding the `dist/`folder to tagged releases makes sense. Many other projects do that too.

**Comment by kahwooi** [comment]
OpenLayer 3 is an important JavaScript library that is not in Bower package.

**Comment by tschaub** [comment]
Can I convince anybody here just to add `openlayers` to their `package.json`?  If you've got Bower, you've already got npm.

I hope we can convince people *not* to use the full build of the library (the one published to the npm registry).  Publishing the same full build to the Bower registry will make this even harder.  If we agree on a useful set of custom profiles to publish, then I'd be more open to publishing them on additional registries, but I'm a bit dubious about being able to generate profiles that will satisfy a large enough group of users to be useful.

I want to make ol3 accessible to more users, but I'm not so hot on the idea of people thinking the full build is the right way to go.

**Comment by elemoine** [comment]
I understand and share @tschaub's concerns.

We need some good and official documentation describing how to download/install OpenLayers with node/npm and create a custom build. I think it would help if the OpenLayers node package included a build configuration file that people could use as a base.

**Comment by ThomasG77** [comment]
I've done some work for an *How To* about using Browserify and WebPack reusing my knowledge and feedback from #3162
We maybe can adapt it.  The repo for this purpose is https://github.com/webgeodatavore/demo_browserify_webpack_ol3
I didn't work on creating documentation on custom build as there are infos in https://github.com/openlayers/ol3/blob/master/tasks/readme.md but for most end users @elemoine, your viewpoint about custom build is valid IMO.

**Comment by elemoine** [comment]
Closing this as some of the OpenLayers 3 developers disagree with publishing OpenLayers 3 to bower.io. Please reopen if you think this is still worth discussing.

**Pull request closed without merging**
