### PR TITLE
Generate example index and rebuild examples on source changes

### LINKED ISSUE #3529: ./build.py check should run over the examples_src directory instead?
Currently it will report errors in the examples dir, but I think it makes more sense to run over the examples_src directory instead so that people don't get confused where they need to change the files?

### PR DESCRIPTION
**Pull request by tschaub**
With this change, `tasks/build-examples.js` generates the `example/index.js` file in addition to generating the rest of the examples.

When `tasks/serve.js` is run (which is launched by `npm start`), the examples are built before the server is started.  Then, whenever an example source file changes, the examples are rebuilt (and any attached clients reload).

This is one step toward #3532.

I'd like to move the generated `examples` directory out of the root, as I think all generated files should go in `build`.  But this will involve more changes to `build.py`, and I'd rather handle it separately.

Fixes #3529.

### CODE REVIEW

**Comment by tschaub** [comment]
This is ready for review.

**Comment by elemoine** [comment]
Very nice. Please merge!

**Comment by ahocevar** [comment]
:+1: from me as well - very nice work!

**Comment by bartvde** [comment]
@tschaub could there be an issue with swap files?

```
info serve Building examples.
ERR! serve Building examples failed.
ERR! serve Failed to read the file at: /Users/bartvandeneijnden/opengeo/git/ol3_bartvde/examples_src/.vector-esri.js.swp
ERR! serve 
ERR! serve ENOENT, stat '/Users/bartvandeneijnden/opengeo/git/ol3_bartvde/examples_src/.vector-esri.js.swp'
ERR! serve Use "verbose" logging to see the full stack trace.
```

**Comment by tschaub** [comment]
@bartvde try this:
```
node tasks/serve.js --loglevel=verbose
```

The trace might not have any more useful info.  I think it is worth opening a separate ticket if you are able to reproduce the issue.

**Pull request merged**
