### PR TITLE
Replace base symbols with overridden ones when generating info.json

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #3981.

### CODE REVIEW

**Comment by gberaudo** [comment]
Thank you very much @ahocevar for this PR.

Unfortunately it seems too many symbols are discarded and I get the following errors in OL3-Cesium:
```
node build/build.js build/ol3cesium.json dist/ol3cesium.js
info ol3-cesium Parsing dependencies
info ol3-cesium Compiling 47 sources
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:241: ERROR - Property getType never defined on ol.geom.Circle
ERR! compile   goog.asserts.assert(olGeometry.getType() == 'Circle');
ERR! compile                       ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:292: ERROR - Property getType never defined on ol.geom.LineString
ERR! compile   goog.asserts.assert(olGeometry.getType() == 'LineString');
ERR! compile                       ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:338: ERROR - Property getType never defined on ol.geom.Polygon
ERR! compile   goog.asserts.assert(olGeometry.getType() == 'Polygon');
ERR! compile                       ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:430: ERROR - Property getType never defined on ol.geom.Point
ERR! compile   goog.asserts.assert(geometry.getType() == 'Point');
ERR! compile                       ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:436: ERROR - Property load never defined on ol.style.Icon
ERR! compile     imageStyle.load();
ERR! compile     ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:529: ERROR - Property getType never defined on ol.geom.Geometry
ERR! compile   switch (geometry.getType()) {
ERR! compile           ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:561: ERROR - Property getType never defined on ol.geom.Geometry
ERR! compile       goog.asserts.fail('Unhandled multi geometry type' + geometry.getType());
ERR! compile                                                           ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:769: ERROR - Property getType never defined on ol.geom.Geometry
ERR! compile   switch (geom.getType()) {
ERR! compile           ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/featureconverter.js:820: ERROR - Property getType never defined on ol.geom.Geometry
ERR! compile       throw new Error('Ol geom type not handled : ' + geom.getType());
ERR! compile                                                       ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3-cesium/src/ol3cesium.js:227: ERROR - Property clear never defined on ol.Collection.<(null|ol.interaction.Interaction)>
ERR! compile       interactions.clear();
ERR! compile       ^
ERR! compile 
ERR! compile 10 error(s), 0 warning(s), 96,1% typed
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 10
```

These errors do not appear with #3981.

I checked ol/geom/geometry.js and it contains annotations for the `getType()` function.

**Comment by ahocevar** [comment]
Ok, I'll give it another try.

**Comment by ahocevar** [comment]
@gberaudo I had to dig a bit deeper. Can you please try the updated pull request?

**Comment by gberaudo** [comment]
There is no more error in OL3-Cesium and the number of generated externs are the same as with my method. So it looks good to me and I would be happy to see this merged.
Thank you @ahocevar.

**Comment by elemoine** [comment]
+1

**Pull request merged**
