### PR TITLE
Remove redundant code from ol.featureloader.tile

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request simplifies the tile feature loader by removing redundant code and not requiring to call the callback with a projection argument any more.

### CODE REVIEW

**Comment by ahocevar** [comment]
This is now ready for review. I had missed that gjslint was not happy with the original code.

**Comment by ahocevar** [comment]
@bartvde or @tsauerwein, since you reviewed #4518, you may want to have a look at this one as well - it is merely a cleanup.

**Comment by bartvde** [comment]
LGTM @ahocevar

**Comment by ahocevar** [comment]
Thanks for the review @bartvde.

**Pull request merged**
