### PR TITLE
Always pass on a compare function to sort

### LINKED ISSUE #4566: Tiles disappearing on pan when zoom level change is big
Found this out in a screenshare with @ahocevar just now, to reproduce go to:

http://openlayers.org/en/v3.12.0/examples/xyz-esri.html

Zoom in with a very small bbox, and then pan the map. The tiles will blur completely sometimes. In 3.11.2 you will see a small section blurred only, where no tiles are present as yet.

### PR DESCRIPTION
**Pull request by bartvde**
fixes #4566

### CODE REVIEW

**Comment by bartvde** [comment]
seeing if I can add some test cases to prevent this from happening again

**Comment by bartvde** [comment]
not easy to test unfortunately, if anybody has ideas for test cases let me know, I've added 2 unit tests for now that we're low hanging fruit.

**Comment by bartvde** [comment]
ready for review, this probably warrants a 3.12.1 release

**Comment by marcjansen** [comment]
This looks good to me, Bart. Plese merge.


 I think a patch release is appropriate. Maybe @tschaub, @ahocevar, @fredj or @tsauerwein have an opinion as well?

Thanks.

**Comment by bartvde** [comment]
thanks @marcjansen I'll probably wait a few days to see if another regression pops up. If nothing pops up, and nobody is against it, I'll likely do a 3.12.1 at the end of this week.

**Comment by ahocevar** [comment]
I think `defaultCompare` is a misleading name. What about `numberCompare`? And I agree that this warrants a patch release.

**Comment by bartvde** [comment]
I can change it to ```numberCompare``` @ahocevar

**Comment by ahocevar** [comment]
Or maybe `numberSafeCompare` would be even better.

**Comment by bartvde** [comment]
okay we settled on ```numberSafeCompareFunction``` ;-)

**Pull request merged**
