### PR TITLE
Add ol.style.Circle#setRadius

### PR DESCRIPTION
**Pull request by jonataswalker**
Replacing #5771 and addressing #5748.

### CODE REVIEW

**Comment by marcjansen** [comment]
This will need to be updated due to recent changes. Can you do that, @jonataswalker? TIA

**Comment by jonataswalker** [comment]
Yes, sir. Hang tight.

**Comment by jonataswalker** [comment]
Another rebase?

**Comment by marcjansen** [comment]
No need for another rebase. This simply got lost, sorry.

Thanks for this.

**Pull request merged**
