### PR TITLE
Revert "Implement ol.renderer.Layer#forEachFeatureAtCoordinate"

### PR DESCRIPTION
**Pull request by fredj**
This reverts commit dd07fd797730e7a25aac96562972010052ea951f.

See https://github.com/openlayers/ol3/pull/3637#issuecomment-98964364

### CODE REVIEW

**Comment by bartvde** [comment]
LGTM @fredj

**Comment by fredj** [comment]
Thanks @bartvde (forgot this one ...)

@elemoine is it good for you too?

**Comment by fredj** [comment]
@elemoine is it good for you too?

**Comment by fredj** [comment]
> @elemoine is it good for you too?

assuming yes

**Comment by elemoine** [comment]
Sorry for the delay responding @fredj! Looks good to me.

**Pull request merged**
