### PR TITLE
Remove externs in externs/closure-compiler.js

### PR DESCRIPTION
**Pull request by fredj**
Fixed upstream:
 * https://github.com/google/closure-compiler/pull/1139
 * https://github.com/google/closure-compiler/pull/1140

### CODE REVIEW

**Comment by elemoine** [comment]
Thanks a lot @fredj. I see that you prefer to keep the closure-compiler.js file around.

**Comment by fredj** [comment]
> Thanks a lot @fredj. I see that you prefer to keep the closure-compiler.js file around.

yes, for future use ...

**Comment by elemoine** [comment]
Makes sense. Please merge.

**Comment by fredj** [comment]
Should we update jquery-1.9.js as well?

**Comment by elemoine** [comment]
The externs file you mean? Yep, that would make sense.

**Comment by elemoine** [comment]
Please merge.

**Pull request merged**
