### PR TITLE
Add tooltip to show measure + help message while drawing

### PR DESCRIPTION
**Pull request by pgiraud**
The goal of this pull request is to update the measure example to show how to show the measurement while drawing. It relies on `ol.Overlay`.

Here's how it looks:
ol3_measure_tooltip

Please review.

### CODE REVIEW

**Comment by tsauerwein** [comment]
Very nice example! I added some minor comments.

**Comment by elemoine** [comment]
This is minor but don't you think we should change the style of the draw interaction's feature overlay? I find the "blue" too flashy for a measure tool. Yeah, certainly subjective.

**Comment by tschaub** [comment]
This is great!  With or without toning down the blue, I'm in favor or merging.

**Comment by pgiraud** [comment]
I changed the styling a bit. Merging.

**Comment by elemoine** [comment]
I love the new styling! Very nice work.

**Comment by carolgit** [comment]
how to show tooltip when drawing a geom.circle?

**Pull request merged**
