### PR TITLE
Source options fixes

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by tschaub** [comment]
Looks good to me.

**Comment by fredj** [comment]
post merge +1

**Comment by gberaudo** [comment]
Thanks for the quick review. I just found there are 3 more such casts in the code.
I will create a new PR for these.

**Comment by adube** [comment]
@gberaudo Is one of those the `ol.layer.VectorTile.prototype.getSource;` ?

**Comment by gberaudo** [comment]
No @adube. Actually there are 44 more, unrelated to the source state cast.
I will try to get some time for a PR eliminating them.

**Comment by adube** [comment]
Gotcha.  I'll keep a close eyes on that.  Thanks!

**Pull request merged**
