### PR TITLE
Listen for a 'change:geometry' event

### PR DESCRIPTION
**Pull request by fperucic**
geometry index will be updated correcly when using `feature.getGeometry().setCoordinates` but it won't be when using `feature.setGeometry`.

### CODE REVIEW

**Comment by fperucic** [comment]
you are right, it does. I missed that.

**Comment by fperucic** [comment]
sory, I rushed with this conclusion. Old geometry listener is properly removed since all listerers are index by feature uid. So when a feature is removed, listereners are removed by features uid.

**Comment by ahocevar** [comment]
That's true. But `ol.Feature#setGeometry()` triggers `change:geometry`, at which time the old geometry is no longer assigned to the feature, but still has a listener. The old geometry will be available as `evt.oldValue`, so you'll have to deal with that in `#handleGeometryChanged_()`

**Comment by fperucic** [comment]
I may be missing something. The way I see it is the old geometry is beeing unlistened on `#removeFeature(feature, true)` as well as the feature. After that, listeners are bind to the new geometry and again to the feature on `#addFeature(feature, true)`.

**Comment by ahocevar** [comment]
You're right - I was missing something. This is indeed handled in https://github.com/fperucic/ol3/blob/ol.interaction.Snap-fix/src/ol/interaction/snapinteraction.js#L308.

**Pull request merged**
