### PR TITLE
[WIP] Fix more missing requires

### PR DESCRIPTION
**Pull request by ahocevar**
This is a follow-up on #5702 to resolve all dependency problems by applying the rules outlined in https://github.com/openlayers/ol3/pull/5702#issuecomment-238585089.

This is a branch of the main repository so all core committers can contribute easily. Other contributors, please mention commits that can be cherry-picked in comments on this pull request.

Thanks in advance to anyone helping to get this done.

### CODE REVIEW

**Comment by ahocevar** [comment]
@tschaub When this is done, the new version of eslint-plugin-openlayers-internal will have to be published to npm. I temporarily changed back to 'file:rules'.

**Comment by ahocevar** [comment]
416 problems left - I'm done for today if anyone wants to pick it up while I'm asleep 😄.

**Comment by fredj** [comment]
@ahocevar is it ok if I remove 7744552 and rebase into master ? (with push --force)

**Comment by ahocevar** [comment]
Yes, please go ahead @fredj.

**Comment by fredj** [comment]
315 problems left ...

**Comment by tschaub** [comment]
> @tschaub When this is done, the new version of eslint-plugin-openlayers-internal (see 1bb287a) will have to be published to npm. I temporarily changed back to 'file:rules'.

@ahocevar - I published `eslint-plugin-openlayers-internal@2.2.0`, added collaborators so others can do the same, and updated the dependency in 162660ace1e3c977a30824ce7ce25b4a20351c08.

**Comment by tschaub** [comment]
Down to 180 problems. (The auto-generated WebGL modules could use some attention by someone interested.)

@ahocevar if you agree, I think it would be good to merge this as is.  I like the idea of a shared branch, but I think this invites conflicts if it goes on too long.

**Comment by tschaub** [comment]
This branch now has conflicts.  I'm rebasing.

**Comment by tschaub** [comment]
Hrm.  Same `TypeError: undefined is not a function (evaluating 'ArrayBuffer.b(a)')` we're seeing elsewhere (https://github.com/openlayers/ol3/pull/5815#issuecomment-243933337).

**Comment by tschaub** [comment]
I'll rebase this now to get the externs fix in #5819.

**Comment by tschaub** [comment]
When this is green, I think we should merge it and continue the work in subsequent pull requests.

**Comment by bartvde** [comment]
+1

**Pull request merged**
