### PR TITLE
Document how to use draw interaction

### PR DESCRIPTION
**Pull request by probins**
This wasn't clear to me, so after checking what it does I decided to write it up.

A related question: are there any plans to add methods to write drawn/modified features to a server, as with OL2's save strategy?

### CODE REVIEW

**Comment by probins** [comment]
The current docs for FeatureOverlay need updating too. If I can store drawn/modified features in a FO it is no longer just a temporary thing as described there.

**Comment by tschaub** [comment]
@probins we're talking about de-emphasizing `ol.FeatureOverlay`.  As far as the draw interaction is concerned, it is an implementation detail.  An alternative implementation would be for the draw interaction to use the immediate rendering API.  I don't think this implementation detail should be described as it is not relevant to using the draw interaction.

I think the docs should focus on the interface for the draw interaction (not the implementation details).  In particular, I think the docs should clearly describe the `source` and `features` options.  As it is not currently clear from the documentation that only one is used (and that one takes precedence).

**Comment by probins** [comment]
well, I can remove the first bit about the FO; as you say, it's not important. But I actually think the ability to use an FO so the drawn features remain on the screen is good. Tile/Image sources are read-only, but vector data can be write-only. In this case there is no 'source', so why create a layer and a source just to hold drawn features when any feature collection can be used? On the other hand, if I use any collection, features won't stay on the screen. Using an FO solves that issue, and is much simpler than layer/source. Even if you have a source, and are adding to it, being able to store the additions separately is useful. Then if the user makes a complete hash and wants to start again, you just clear from the FO without having to refresh the source from the server.

> it is not currently clear from the documentation that only one is used
you can have both (though I'm not sure what the use case would be)
https://github.com/openlayers/ol3/blob/master/src/ol/interaction/drawinteraction.js#L567-L573

**Comment by tschaub** [comment]
> and is much simpler than layer/source

Really?  All layers share a common set of methods for setting visibility, opacity, etc.  What do you do to toggle the visibility of a feature overlay or change its opacity?   All layers can be added to and removed from the map in the same way.  Feature overlays have a special/awkward way of being added to or removed from a map.  Vector sources have efficient methods for retrieving features by id or location.  Feature overlays don't.  When requesting all features at a pixel, you can control which layers are included - you don't have this control for feature overlays.

I don't think the docs need to be complicated by introducing feature overlays.  You can do more and use a more familiar interface with layers and sources.

**Comment by probins** [comment]
> Feature overlays have a special/awkward way of being added to or removed from a map

yes, I agree there. That is confusing. Don't get me wrong. I'm not saying that FOs are perfect. If there's a better way, fine. But for an app like geojson.io where you basically just have a bunch of draw tools and the ability to save the drawn features, then you don't need opacity/rotation/getAtPixel/whatever. Layer/source is powerful, I agree, but that means complexity. The newcomer has to look through, for example, the various source.Vector constructor options, none of which are relevant to a draw tool.

Coming back to this PR, how do you explain the draw-and-modify example without referring to FOs? And what is the use case for the `features` option if you don't have an FO?

If source.Vector is to be used as general storage for features, then its docs should say so. The current description (and name) is misleading; the data can come from more than 1 source, and can be changed. In some cases, like bbox loading, you probably want to reflect what's on a server. But if you're adding/changing/deleting features, then you maybe don't. Perhaps something like: 'Storage of features for vector layers; features can be loaded from an external source, be added/removed programmatically with addFeature/removeFeature, and/or by user action with the draw and modify interactions'. I can create a PR for that if you like.

**Comment by probins** [comment]
Another issue with FOs is you can't use the select interaction with them, so I think I now agree that FOs aren't the answer for storing vector data. The whole area of how create/update/delete/save of features should be handled is poorly documented at the moment, but I will close this issue, as it's only addressing a small and not very important part of that. I'll try and find time to put together a list of issues I have with the current vector handling.

**Pull request closed without merging**
