### PR TITLE
Note in docs that WebGL can render points

### PR DESCRIPTION
**Pull request by probins**
The current docs are a bit out of date, so this update may help answer an FAQ.

### CODE REVIEW

**Comment by fredj** [comment]
thanks

**Comment by ahocevar** [comment]
Post-merge comment: also the DOM renderer has full vector support.

**Comment by probins** [comment]
ah, does it - I must have missed that. Further PR coming up then

**Comment by probins** [comment]
Presumably, canvas is still the recommended renderer, though?

**Comment by probins** [comment]
is there an example using DOM for vectors?

**Comment by tsauerwein** [comment]
> is there an example using DOM for vectors?

E.g. http://openlayers.org/en/master/examples/icon.html?mode=raw&renderer=dom

**Comment by ahocevar** [comment]
> Presumably, canvas is still the recommended renderer, though?

Yes.

**Comment by probins** [comment]
> E.g. http://openlayers.org/en/master/examples/icon.html?mode=raw&renderer=dom

well, yes, but afaik the rendererfromquerystring thing is only used by some examples and isn't documented anywhere, so any newbie is not going to know about it.

In any case, that doesn't help someone who goes to the examples page and searches for 'dom vectors' or even just 'dom'

**Comment by tsauerwein** [comment]
Agree, it would make sense to have an example that directly uses the DOM renderer.

**Comment by tschaub** [comment]
Alternatively, we could remove the DOM renderer.

**Pull request merged**
