### PR TITLE
Remove the use of ol.format.KML.DEFAULT_IMAGE_SCALE_MULTIPLIER_ when …

### PR DESCRIPTION
**Pull request by oterral**
…it's not wanted

Fix regression #6044

### CODE REVIEW

**Comment by oterral** [comment]
@fredj can you review pls?

**Comment by oterral** [comment]
A review please ? an opinion at least?

**Comment by bartvde** [comment]
ping @tamarmot since he did the original change I think?

**Comment by bartvde** [comment]
Given that we have had another user report the issue, I'm going to merge this one
Thanks for your patience and work @oterral

**Comment by oterral** [comment]
You're welcome and thx for the review.

**Comment by tamarmot** [comment]
Thanks all, sorry I was out & couldn't look at this.

**Pull request merged**
