### PR TITLE
 Use the word "documentation"

### PR DESCRIPTION
**Pull request by ahocevar**
To get better search engine rankings, we should use our new /latest/ resources wherever we can.

### CODE REVIEW

**Comment by probins** [comment]
but it's already pointing to latest 😕

**Comment by ahocevar** [comment]
Oh, I had accidently sneaked parts of this change into #5575.

**Comment by ahocevar** [comment]
Updated the topic of this pull request - the change remaining is now only to use "the API documentation" instead of "API docs".

**Comment by fredj** [comment]
+1

**Pull request merged**
