### PR TITLE
Remove use of goog.isNull

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by marcjansen** [comment]
I have just restarted the build.

**Comment by marcjansen** [comment]
It looks as if 


```shell
node tasks/build.js config/examples-all.json build/compiled-examples/all.combined.js
```

doesn't work on travis …

**Comment by ahocevar** [comment]
Looks like something is or was wrong with the image-load-events example. I restarted the build again. Let's see if it finishes now.

**Comment by ahocevar** [comment]
Looks good, please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
