### PR TITLE
Make package.json compatible for npm frontend use

### PR DESCRIPTION
**Pull request by ThomasG77**
This PR augments package.json to ease OpenLayers 3 frontend development through NPM.
See [this post on NPM blog](http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm) to get more informations and evaluate if it's worth to accept.
If you use Browserify and/or Parcelify, you can use this informations out of the box.
`browser` part is in [this spec](https://gist.github.com/defunctzombie/4339901)

It's up to you to decide if providing paths to js and css is good.
In fact, it's quite similar to Bower but we don't create a new file, we only use existing `package.json`.

### CODE REVIEW

**Comment by tschaub** [comment]
Can you provide an example of the benefit this provides?

**Comment by ThomasG77** [comment]
I've updated my PR. A bit ashamed...

You will what additional thinks it can do for you looking at [this small demo project](https://github.com/ThomasG77/ol3-browser-style-addition)
The README should be clear. Feel free to ask more.
If you are convinced, I can submit a new PR with only one change.

**Comment by elemoine** [comment]
I have no problem with that change. @tschaub?

**Comment by ahocevar** [comment]
https://www.npmjs.com/package/parcelify does not seem to be that popular. What do you think @tschaub?

**Comment by tschaub** [comment]
This looks ok by me.  Thanks @ThomasG77.

**Comment by bartvde** [comment]
this breaks tools like dr-frankenstyle (used by Pivotal UI React) where style needs to be a string not an array:

```
> dr-frankenstyle css

TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at Object.callee$1$0$ (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/dr-frankenstyle-win/css-dependencies.js:81:39)
    at tryCatch (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/dr-frankenstyle-win/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/dr-frankenstyle-win/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/dr-frankenstyle-win/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/dr-frankenstyle-win/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at lib$es6$promise$$internal$$tryCatch (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/es6-promise/dist/es6-promise.js:326:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/es6-promise/dist/es6-promise.js:338:17)
    at lib$es6$promise$$internal$$publish (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/es6-promise/dist/es6-promise.js:309:11)
    at lib$es6$promise$asap$$flush (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/es6-promise/dist/es6-promise.js:120:9)
```

**Comment by bartvde** [comment]
I guess I can whitelist the directories though to have it ignore the openlayers directory

**Pull request merged**
