### PR TITLE
Add turf.js and JSTS example

### PR DESCRIPTION
**Pull request by tsauerwein**
This PR adds two examples showing the integration with turf.js and JSTS.

@bjornharrtell I saw that there is a `jsts.io.olParser` class, but I couldn't find an up-to-date build online that I could use in the example.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Thanks for the heads up @tsauerwein, I've made the 0.16.0 release available at:

https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/lib/0.16.0/javascript.util.min.js
https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/lib/0.16.0/jsts.min.js

**Comment by tsauerwein** [comment]
Thanks @bjornharrtell! I updated the example with `olparser`.

**Comment by elemoine** [comment]
Very cool! Please merge.

**Comment by bjornharrtell** [comment]
Thanks for doing this @tsauerwein :)

**Pull request merged**
