### PR TITLE
Fix vector tile rotation on HiDPI devices

### LINKED ISSUE #5791: Regression: Rotation of vector tile layers broken
This regression only affects HiDPI devices. Go to http://openlayers.org/en/v3.18.0/examples/mapbox-vector-tiles.html and rotate the map. Everything that is rendered to an image (hybrid modes, so lines and polygons) will be shifted to somewhere outside the map viewport. The same works fine in http://openlayers.org/en/v3.18.0/examples/mapbox-vector-tiles.html.

### PR DESCRIPTION
**Pull request by ahocevar**
This is a regression from 3.17.1, introduced by #5724: the tile images generated in hybrid and image mode disappear when rotating the map on retina displays, as can be seen in the mapbox-vector-tiles example.

Fixes #5791.

### CODE REVIEW

**Comment by bartvde** [comment]
@ahocevar the issue is not only on retina displays, I have it on my non-retina screen as well

**Comment by ahocevar** [comment]
Good to know @bartvde. Does this pull request fix things there as well?

**Comment by bartvde** [comment]
Will look at it soon and report back here.

**Comment by bartvde** [comment]
Yes fixes it as well on non-retina

**Comment by bartvde** [comment]
LGTM thanks for adding more rendering tests!

**Pull request merged**
